import{Search,Undo2,Redo2,Save,Download,Settings,RotateCcw,Database,LayoutDashboard,Bot,HardDrive,Paintbrush,UploadCloud}from'lucide-react';
import{useEffect,useState}from'react';
import{useStudio}from'../store';

const ACCENTS=[{name:'Corporate blue',value:'#2563eb'},{name:'Azure blue',value:'#0284c7'},{name:'Emerald green',value:'#16a34a'}];
const DEFAULT_PREFERENCES={autosave:true,rememberWorkspace:true,defaultPageSize:'HD 16:9',snapToGrid:true,defaultShowGrid:true,defaultFont:'Segoe UI',previewRows:500,queryCache:true,copilotEnabled:true,copilotContext:true};
type SettingsSection='general'|'save'|'report'|'data'|'copilot'|'about';
const APP_VERSION=import.meta.env.VITE_APP_VERSION||'5.0.15';

export default function Topbar(){
 const{project,undo,redo,canUndo,canRedo,update,setView,view,save,saveStatus,saveError}=useStudio() as any;
 const[settingsOpen,setSettingsOpen]=useState(false),[settingsSection,setSettingsSection]=useState<SettingsSection>('general');
 const[command,setCommand]=useState(''),[commandOpen,setCommandOpen]=useState(false);
 useEffect(()=>{const open=()=>setSettingsOpen(true);window.addEventListener('vtab:open-settings',open);return()=>window.removeEventListener('vtab:open-settings',open)},[]);
 useEffect(()=>{if(!settingsOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setSettingsOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[settingsOpen]);
 const theme=project?.appTheme||'vtab',rawAccent=project?.appAccent||'#2563eb',accent=rawAccent.toLowerCase()==='#22d3ee'?'#2563eb':rawAccent,density=project?.uiDensity||'comfortable';
 const preferences={...DEFAULT_PREFERENCES,...(project?.appPreferences||{})};
 const patchProject=(patch:any)=>{if(project)update((p:any)=>Object.assign(p,patch))};
 const setTheme=(value:'vtab'|'black'|'white')=>{const dark=value==='black';document.documentElement.dataset.theme='vtab';document.documentElement.dataset.colorMode=dark?'dark':'light';document.documentElement.style.colorScheme=dark?'dark':'light';patchProject({appTheme:value})};
 const setAccent=(value:string)=>{document.documentElement.style.setProperty('--brand-accent',value);patchProject({appAccent:value})};
 const setDensity=(value:'compact'|'comfortable'|'spacious')=>{document.documentElement.dataset.density=value;patchProject({uiDensity:value})};
 const setPreference=(key:string,value:any)=>patchProject({appPreferences:{...(project?.appPreferences||{}),[key]:value}});
 const resetSettings=()=>{document.documentElement.dataset.theme='vtab';document.documentElement.dataset.colorMode='light';document.documentElement.style.colorScheme='light';document.documentElement.dataset.density='comfortable';document.documentElement.style.setProperty('--brand-accent','#2563eb');patchProject({appTheme:'vtab',appAccent:'#2563eb',uiDensity:'comfortable',appPreferences:{...DEFAULT_PREFERENCES}})};
 const title=project?.report?.name||project?.name||'VTAB Project',reportContext=view==='report';
 const commands=[['data','Get Data'],['transform','Transform'],['model','Model'],['ai-measures','AI Measures'],['measures','Measures'],['report','Report Designer'],['publish','Publish'],['security','Security'],['packages','Packages'],['copilot','Assist'],['settings','Settings']];
 const matches=commands.filter(([,label])=>label.toLowerCase().includes(command.trim().toLowerCase())).slice(0,7);
 const openPublish=()=>window.dispatchEvent(new CustomEvent('vtab:open-publish'));
 const runCommand=(target:string)=>{if(target==='settings')setSettingsOpen(true);else if(target==='publish')openPublish();else setView(target);setCommand('');setCommandOpen(false)};
 const sections:Array<[SettingsSection,string,any]>= [['general','General',Paintbrush],['save','Save & recovery',HardDrive],['report','Report authoring',LayoutDashboard],['data','Data load',Database],['copilot','Assist',Bot],['about','About',Settings]];
 return <header className="topbarGlass powerBiTopbar">
   <div className="crumbGlass"><span className="productTitle">VTAB Reporting Studio</span><span className="titleDivider"/><span className="crumbTitle" title={title}>{title}</span><span className="buildBadgeGlass">{APP_VERSION}</span></div>
   <div className="topActionsGlass">
     <div className="commandSearch"><div className="searchGlass"><Search size={15} className="searchIcon"/><input value={command} onFocus={()=>setCommandOpen(true)} onBlur={()=>setTimeout(()=>setCommandOpen(false),140)} onChange={e=>{setCommand(e.target.value);setCommandOpen(true)}} onKeyDown={e=>{if(e.key==='Enter'&&matches[0])runCommand(matches[0][0]);if(e.key==='Escape')setCommandOpen(false)}} placeholder="Search commands and workspaces" aria-label="Search commands and workspaces"/></div>{commandOpen&&command.trim()&&<div className="commandMenu">{matches.map(([target,label])=><button key={target} onMouseDown={e=>e.preventDefault()} onClick={()=>runCommand(target)}><Search size={13}/><span>{label}</span><small>Open</small></button>)}{!matches.length&&<div className="commandEmpty">No matching workspace</div>}</div>}</div>
     <div className="actionGroupGlass"><button className="btnIconGlass" title="Undo" disabled={!canUndo} onClick={undo}><Undo2 size={15}/></button><button className="btnIconGlass" title="Redo" disabled={!canRedo} onClick={redo}><Redo2 size={15}/></button></div>
     <button className={'btnGlass saveState '+saveStatus} onClick={()=>void save().catch(()=>{})} title={saveError||'Save report'}><Save size={15}/>{saveStatus==='saving'?'Saving…':saveStatus==='pending'?'Changes pending':saveStatus==='error'?'Retry save':saveStatus==='saved'?'Saved':'Save'}</button>
     {reportContext&&<button className="btnGlass"><Download size={15}/>Export</button>}
     {project&&<button className="btnGlass primary publishTopbarButton" onClick={openPublish} title="Publish this report to VTAB Services"><UploadCloud size={15}/>Publish</button>}
   </div>
   {settingsOpen&&<div className="settingsModalBackdrop" onMouseDown={()=>setSettingsOpen(false)}><section className="settingsPowerBiDialog" role="dialog" aria-modal="true" aria-label="Settings" onMouseDown={e=>e.stopPropagation()}>
     <header><div><b>Options and settings</b><span>Settings apply immediately and are saved with this project.</span></div><button aria-label="Close settings" onClick={()=>setSettingsOpen(false)}>×</button></header>
     <div className="settingsDialogBody"><nav>{sections.map(([id,label,Icon])=><button key={id} className={settingsSection===id?'active':''} onClick={()=>setSettingsSection(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><main>
       {settingsSection==='general'&&<><h2>General</h2><p>Control the appearance and working density of the authoring application.</p><div className="settingsGroup"><h3>Application appearance</h3><label><span><b>Color mode</b><small>Changes all authoring screens immediately.</small></span><select value={theme==='black'?'black':'vtab'} onChange={e=>setTheme(e.target.value as any)}><option value="vtab">Light</option><option value="black">Dark</option></select></label><label><span><b>Accent color</b><small>Used for selected items and primary actions.</small></span><select value={ACCENTS.some(a=>a.value===accent)?accent:'#2563eb'} onChange={e=>setAccent(e.target.value)}>{ACCENTS.map(a=><option key={a.value} value={a.value}>{a.name}</option>)}</select></label><label><span><b>Interface density</b><small>Controls spacing in panes and command bars.</small></span><select value={density} onChange={e=>setDensity(e.target.value as any)}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="spacious">Spacious</option></select></label></div></>}
       {settingsSection==='save'&&<><h2>Save & recovery</h2><p>Choose how authoring changes and the last workspace are retained.</p><div className="settingsGroup"><label className="settingsToggle"><span><b>Automatically save changes</b><small>Writes report changes after a short delay. Turn this off to save manually.</small></span><input type="checkbox" checked={preferences.autosave} onChange={e=>setPreference('autosave',e.target.checked)}/></label><label className="settingsToggle"><span><b>Return to the last workspace</b><small>Reopens the last-used Data, Transform, Model, or Report view.</small></span><input type="checkbox" checked={preferences.rememberWorkspace} onChange={e=>setPreference('rememberWorkspace',e.target.checked)}/></label></div></>}
       {settingsSection==='report'&&<><h2>Report authoring</h2><p>Defaults below are applied to newly created pages and visuals.</p><div className="settingsGroup"><label><span><b>Default page size</b><small>Used when New page is selected.</small></span><select value={preferences.defaultPageSize} onChange={e=>setPreference('defaultPageSize',e.target.value)}><option>HD 16:9</option><option>Full HD 16:9</option><option>A4 Landscape</option></select></label><label><span><b>Default visual font</b><small>Used by visuals created after this change.</small></span><select value={preferences.defaultFont} onChange={e=>setPreference('defaultFont',e.target.value)}><option>Segoe UI</option><option>Arial</option><option>Inter</option></select></label><label className="settingsToggle"><span><b>Snap new pages to grid</b><small>Keeps visual movement aligned to the report grid.</small></span><input type="checkbox" checked={preferences.snapToGrid} onChange={e=>setPreference('snapToGrid',e.target.checked)}/></label><label className="settingsToggle"><span><b>Show grid on new pages</b><small>Displays authoring grid lines on new report pages.</small></span><input type="checkbox" checked={preferences.defaultShowGrid} onChange={e=>setPreference('defaultShowGrid',e.target.checked)}/></label></div></>}
       {settingsSection==='data'&&<><h2>Data load</h2><p>Control Transform preview volume and local preview reuse.</p><div className="settingsGroup"><label><span><b>Transform preview rows</b><small>Between 100 and 5,000 rows.</small></span><input type="number" min="100" max="5000" value={preferences.previewRows} onChange={e=>setPreference('previewRows',Math.max(100,Math.min(5000,+e.target.value||500)))}/></label><label className="settingsToggle"><span><b>Reuse local query previews</b><small>Speeds up unchanged Transform previews. Disable when source data changes frequently.</small></span><input type="checkbox" checked={preferences.queryCache} onChange={e=>setPreference('queryCache',e.target.checked)}/></label><button className="settingsSecondaryAction" onClick={()=>window.dispatchEvent(new CustomEvent('vtab:clear-query-cache'))}>Clear preview cache</button></div></>}
       {settingsSection==='copilot'&&<><h2>Assist</h2><p>Control whether AI assistance is available and what project context it can use.</p><div className="settingsGroup"><label className="settingsToggle"><span><b>Enable Assist</b><small>Allows Assist and AI-assisted transformation commands.</small></span><input type="checkbox" checked={preferences.copilotEnabled} onChange={e=>setPreference('copilotEnabled',e.target.checked)}/></label><label className="settingsToggle"><span><b>Use model and report context</b><small>Lets Assist use table, relationship, measure, page, and visual metadata.</small></span><input type="checkbox" disabled={!preferences.copilotEnabled} checked={preferences.copilotContext} onChange={e=>setPreference('copilotContext',e.target.checked)}/></label></div></>}
       {settingsSection==='about'&&<><h2>About</h2><div className="settingsAbout"><b>VTAB Reporting Studio</b><span>Version {APP_VERSION}</span><p>Desktop semantic modeling, transformation, and report authoring.</p></div><button className="settingsSecondaryAction" onClick={resetSettings}><RotateCcw size={15}/>Restore recommended settings</button></>}
     </main></div>
     <footer><button onClick={()=>setSettingsOpen(false)}>Close</button></footer>
   </section></div>}
 </header>
}
