import{useEffect,useState}from'react';
import{Users,Database,Mail,Plus,Pencil,Trash2,Save,PlugZap,Settings,ShieldCheck}from'lucide-react';
import{api}from'../api';

const ROLES=['Admin','Member','Contributor','Viewer'];
const CONNECTION_TYPES=[['sqlserver','SQL Server / Azure SQL'],['postgresql','PostgreSQL'],['mysql','MySQL'],['mariadb','MariaDB'],['oracle','Oracle Database'],['db2','IBM Db2'],['sqlite','SQLite'],['access','Microsoft Access'],['odbc','ODBC'],['jdbc','JDBC'],['snowflake','Snowflake'],['databricks','Databricks SQL / Lakehouse'],['bigquery','Google BigQuery'],['redshift','Amazon Redshift'],['synapse','Azure Synapse Analytics'],['fabric_warehouse','Microsoft Fabric Warehouse / Lakehouse'],['sharepoint','SharePoint'],['onedrive','OneDrive'],['google_sheets','Google Sheets'],['azure_blob','Azure Blob Storage'],['adls_gen2','ADLS Gen2'],['s3','Amazon S3'],['gcs','Google Cloud Storage'],['rest','REST API'],['odata','OData Feed'],['graphql','GraphQL API'],['salesforce','Salesforce'],['dynamics365','Dynamics 365 / Dataverse'],['servicenow','ServiceNow'],['jira','Jira'],['github','GitHub']];
export default function AdminWorkbench(){
 const[tab,setTab]=useState<'users'|'connections'|'settings'>('users');
 const[users,setUsers]=useState<any[]>([]),[connections,setConnections]=useState<any[]>([]),[settings,setSettings]=useState<any>({workspaceBaseUrl:'',smtpHost:'',smtpPort:587,smtpUsername:'',smtpPassword:'',smtpFrom:'',smtpSsl:false,smtpStartTls:true});
 const[userEdit,setUserEdit]=useState<any>(null),[connEdit,setConnEdit]=useState<any>(null),[msg,setMsg]=useState('');
 const load=()=>Promise.all([api<any[]>('/admin/users'),api<any[]>('/admin/connections'),api<any>('/admin/settings')]).then(([u,c,s])=>{setUsers(u);setConnections(c);setSettings((x:any)=>({...x,...s}))});
 useEffect(()=>{load()},[]);
 const saveUser=async()=>{await api('/admin/users',{method:'POST',body:JSON.stringify(userEdit)});setUserEdit(null);setMsg('User saved.');load()};
 const saveConn=async()=>{await api('/admin/connections',{method:'POST',body:JSON.stringify(connEdit)});setConnEdit(null);setMsg('Connection saved.');load()};
 const testConn=async(id:string)=>{try{const r=await api<any>(`/admin/connections/${id}/test`,{method:'POST'});alert(r.message||'Connection successful.')}catch(e:any){alert(e.message)}};
 const saveSettings=async()=>{await api('/admin/settings',{method:'POST',body:JSON.stringify(settings)});setMsg('Workspace/email settings saved.')};
 return <div className="page adminPage"><div className="panelHeader adminHero"><div><span className="eyebrow">ADMINISTRATION</span><h2>Workspace Administration</h2><p>Create users, assign workspace roles, manage reusable data connections, and configure workspace/email delivery.</p></div></div>
  <div className="adminTabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><Users size={16}/>Users & Roles</button><button className={tab==='connections'?'active':''} onClick={()=>setTab('connections')}><Database size={16}/>Connections</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Mail size={16}/>Email & Workspace</button></div>{msg&&<div className="adminMessage">{msg}</div>}
  {tab==='users'&&<section className="adminSection"><div className="adminSectionHead"><div><h3>User Accounts</h3><p>Workspace roles: Admin manages users/settings, Member consumes reports, Contributor authors/publishes, Viewer consumes published reports.</p></div><button className="primary" onClick={()=>setUserEdit({displayName:'',email:'',role:'Viewer',status:'active',workspaceId:'default'})}><Plus size={15}/>New User</button></div><div className="adminTable"><div className="adminTableHead"><span>User</span><span>Email</span><span>Role</span><span>Status</span><span>Actions</span></div>{users.map(u=><div className="adminTableRow" key={u.id}><span><b>{u.display_name}</b><small>{u.workspace_name||'Default Workspace'}</small></span><span>{u.email}</span><span><em className={'rolePill role-'+String(u.role).toLowerCase()}>{u.role||'Viewer'}</em></span><span>{u.status}</span><span className="rowActions"><button onClick={()=>setUserEdit({id:u.id,displayName:u.display_name,email:u.email,role:u.role||'Viewer',status:u.status,workspaceId:u.workspace_id||'default'})}><Pencil size={14}/>Edit</button><button onClick={async()=>{if(confirm('Delete this user?')){await api(`/admin/users/${u.id}`,{method:'DELETE'});load()}}}><Trash2 size={14}/></button></span></div>)}</div></section>}
  {tab==='connections'&&<section className="adminSection"><div className="adminSectionHead"><div><h3>Reusable Data Connections</h3><p>Save connection definitions once and reuse them during data extraction. Secrets remain backend-side.</p></div><button className="primary" onClick={()=>setConnEdit({name:'',type:'sqlserver',config:{server:'',host:'',database:'',user:'',password:'',url:''}})}><Plus size={15}/>New Connection</button></div><div className="connectionCards">{connections.map(c=><article key={c.id}><span className="connectionIcon"><Database/></span><div><b>{c.name}</b><small>{c.type}</small></div><div className="connectionActions"><button onClick={()=>testConn(c.id)}><PlugZap size={14}/>Test</button><button onClick={()=>setConnEdit(c)}><Pencil size={14}/>Edit</button><button onClick={async()=>{if(confirm('Delete connection?')){await api(`/admin/connections/${c.id}`,{method:'DELETE'});load()}}}><Trash2 size={14}/></button></div></article>)}</div></section>}
  {tab==='settings'&&<section className="adminSection settingsGrid"><div className="settingsCard"><Settings/><h3>Workspace Web Address</h3><p>Use the public/internal URL users should receive in shared report emails.</p><label>Workspace Base URL<input value={settings.workspaceBaseUrl||''} onChange={e=>setSettings({...settings,workspaceBaseUrl:e.target.value})} placeholder="https://reports.company.com"/></label></div><div className="settingsCard"><Mail/><h3>SMTP Email Delivery</h3><div className="twoCol"><label>SMTP Host<input value={settings.smtpHost||''} onChange={e=>setSettings({...settings,smtpHost:e.target.value})}/></label><label>Port<input type="number" value={settings.smtpPort||587} onChange={e=>setSettings({...settings,smtpPort:Number(e.target.value)})}/></label><label>Username<input value={settings.smtpUsername||''} onChange={e=>setSettings({...settings,smtpUsername:e.target.value})}/></label><label>Password<input type="password" value={settings.smtpPassword||''} onChange={e=>setSettings({...settings,smtpPassword:e.target.value})}/></label><label>From Email<input value={settings.smtpFrom||''} onChange={e=>setSettings({...settings,smtpFrom:e.target.value})}/></label></div><label className="checkLine"><input type="checkbox" checked={settings.requireAuthoringLogin!==false} onChange={e=>setSettings({...settings,requireAuthoringLogin:e.target.checked})}/>Require user sign-in for Desktop Authoring</label><label className="checkLine"><input type="checkbox" checked={settings.requireWorkspaceLogin!==false} onChange={e=>setSettings({...settings,requireWorkspaceLogin:e.target.checked})}/>Require user sign-in for Workspace (deployment setting)</label><label className="checkLine"><input type="checkbox" checked={settings.smtpStartTls!==false} onChange={e=>setSettings({...settings,smtpStartTls:e.target.checked})}/>Use STARTTLS</label><button className="primary" onClick={saveSettings}><Save size={15}/>Save Settings</button></div></section>}
  {userEdit&&<div className="modalBackdrop"><div className="adminDialog"><h2>{userEdit.id?'Edit User':'Create User'}</h2><label>Display name<input value={userEdit.displayName} onChange={e=>setUserEdit({...userEdit,displayName:e.target.value})}/></label><label>Email<input value={userEdit.email} onChange={e=>setUserEdit({...userEdit,email:e.target.value})}/></label><label>Password<input type="password" value={userEdit.password||''} onChange={e=>setUserEdit({...userEdit,password:e.target.value})} placeholder={userEdit.id?'Leave blank to keep current password':'Set initial password'}/></label><label>Workspace role<select value={userEdit.role} onChange={e=>setUserEdit({...userEdit,role:e.target.value})}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><label>Status<select value={userEdit.status} onChange={e=>setUserEdit({...userEdit,status:e.target.value})}><option value="active">Active</option><option value="disabled">Disabled</option></select></label><div className="dialogActions"><button onClick={()=>setUserEdit(null)}>Cancel</button><button className="primary" onClick={saveUser}><Save size={15}/>Save User</button></div></div></div>}
  {connEdit&&<div className="modalBackdrop"><div className="adminDialog wide"><h2>{connEdit.id?'Edit Connection':'New Connection'}</h2><label>Connection name<input value={connEdit.name||''} onChange={e=>setConnEdit({...connEdit,name:e.target.value})}/></label><label>Type<select value={connEdit.type} onChange={e=>setConnEdit({...connEdit,type:e.target.value})}>{CONNECTION_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{['sharepoint','onedrive','google_sheets','azure_blob','adls_gen2','s3','gcs','rest','odata','graphql','salesforce','dynamics365','servicenow','jira','github'].includes(connEdit.type)?<><label>HTTPS endpoint / URL<input value={connEdit.config?.url||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,url:e.target.value}})} placeholder="https://..."/></label><div className="twoCol"><label>Client/User<input value={connEdit.config?.user||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,user:e.target.value}})}/></label><label>Secret / Token<input type="password" value={connEdit.config?.token||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,token:e.target.value}})}/></label></div></>:connEdit.type==='sqlite'?<label>Database file path<input value={connEdit.config?.path||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,path:e.target.value}})}/></label>:connEdit.type==='odbc'?<label>ODBC connection string<input type="password" value={connEdit.config?.connectionString||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,connectionString:e.target.value}})}/></label>:<div className="twoCol"><label>Server / Host<input value={connEdit.config?.server||connEdit.config?.host||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,host:e.target.value,server:e.target.value}})}/></label><label>Database / Catalog<input value={connEdit.config?.database||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,database:e.target.value}})}/></label><label>User<input value={connEdit.config?.user||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,user:e.target.value}})}/></label><label>Password / Secret<input type="password" value={connEdit.config?.password||''} onChange={e=>setConnEdit({...connEdit,config:{...connEdit.config,password:e.target.value}})}/></label></div>}<div className="dialogActions"><button onClick={()=>setConnEdit(null)}>Cancel</button><button className="primary" onClick={saveConn}><Save size={15}/>Save Connection</button></div></div></div>}
 </div>
}
