import{useEffect,useMemo,useState}from'react';
import{Sparkles,Search,CheckSquare,Square,Save,RefreshCcw,Pencil,Plus,Filter,Table2,Calculator,ShieldCheck,ChevronRight,X}from'lucide-react';
import{api}from'../api';
import{useStudio}from'../store';

type Candidate={id:string,name:string,expression:string,category:string,description:string,table:string,fields:string[],confidence:number,compiledPreview?:string};

export default function AIMeasureCatalog(){
 const{project,replaceProject,setView}=useStudio() as any;
 const[items,setItems]=useState<Candidate[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<Candidate|null>(null),[generated,setGenerated]=useState(false),[saveResult,setSaveResult]=useState<any>(null);
 const load=async()=>{setBusy(true);setError('');setSaveResult(null);try{const r=await api<any>('/measures/catalog',{method:'POST',body:JSON.stringify({limit:360})});setItems(r.suggestions||[]);setGenerated(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[project?.model?.id]);
 const cats=useMemo(()=>['All',...Array.from(new Set(items.map(x=>x.category)))],[items]);
 const filtered=useMemo(()=>items.filter(x=>(category==='All'||x.category===category)&&(!search.trim()||`${x.name} ${x.description} ${x.table} ${x.fields.join(' ')}`.toLowerCase().includes(search.toLowerCase()))),[items,search,category]);
 const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
 const selectFiltered=()=>setSelected(s=>{const n=new Set(s);filtered.forEach(x=>n.add(x.id));return n});
 const clear=()=>setSelected(new Set());
 const applyEdit=(c:Candidate)=>{setItems(xs=>xs.map(x=>x.id===c.id?c:x));setEditing(null)};
 const saveSelected=async()=>{const chosen=items.filter(x=>selected.has(x.id));if(!chosen.length)return;setBusy(true);setError('');try{const r=await api<any>('/measures/bulk-save',{method:'POST',body:JSON.stringify({measures:chosen.map(x=>({name:x.name,expression:x.expression}))})});replaceProject(r.project);setSaveResult(r);setSelected(new Set())}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const existingCount=Object.keys(project?.model?.measures||{}).length;
 return <div className="aiCatalogPage">
   <div className="aiCatalogHero"><div><span className="eyebrow">AI SEMANTIC MEASURE DESIGNER</span><h1>Business Measure Intelligence Catalog</h1><p>VTAB interprets Fact tables, Dimension tables, Calendar/Date tables, relationships and business-like fields to recommend up to 360 business measures. The catalog prioritizes Overall Sales, Revenue, Profit, Customers, Orders, margins, YTD/MTD/QTD, Last Year and rolling 7/14/21/30/60/90/365-day KPIs instead of technical formatting measures.</p></div><div className="catalogHeroStats"><div><b>{items.length}</b><span>Business measures</span></div><div><b>{Object.keys(project?.model?.tables||{}).length}</b><span>Model tables</span></div><div><b>{existingCount}</b><span>Existing measures</span></div></div></div>
   <div className="catalogWorkflow"><span className="done">1</span><b>Model complete</b><ChevronRight/><span className="active">2</span><b>Review AI catalog</b><ChevronRight/><span>3</span><b>Create selected measures</b><ChevronRight/><span>4</span><b>Report Designer</b></div>
   <div className="catalogToolbar"><div className="catalogSearch"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search measure name, table, field or business meaning..."/></div><div className="catalogCategory"><Filter size={14}/><select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><button onClick={selectFiltered}><CheckSquare size={15}/>Select visible</button><button onClick={clear}><Square size={15}/>Clear</button><button onClick={load} disabled={busy}><RefreshCcw size={15}/>Regenerate Business Catalog</button><button onClick={()=>setView('measures')}><Plus size={15}/>Create New Measure</button><button className="primary" disabled={busy||!selected.size} onClick={saveSelected}><Save size={15}/>Create Selected ({selected.size})</button></div>
   {error&&<div className="catalogMessage error">{error}</div>}{saveResult&&<div className="catalogMessage success"><ShieldCheck size={16}/><b>{saveResult.saved?.length||0} measures created.</b>{saveResult.errors?.length>0&&<span>{saveResult.errors.length} were skipped because validation failed.</span>}</div>}
   <div className="catalogContent"><aside className="catalogSummary"><div className="catalogSummaryHead"><Sparkles size={19}/><div><b>AI Catalog</b><span>{filtered.length} currently shown</span></div></div>{cats.filter(c=>c!=='All').map(c=>{const n=items.filter(x=>x.category===c).length;return <button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}><span>{c}</span><b>{n}</b></button>})}<div className="catalogPolicy"><ShieldCheck/><b>Model-grounded</b><span>Fact/Dimension/Calendar roles are inferred from the model. Each business measure is compiled against the current semantic model before it appears here; invalid formulas are excluded.</span></div></aside>
     <section className="catalogGrid">{busy&&!items.length?<div className="catalogLoading"><Sparkles/>Reading Fact, Dimension and Calendar semantics and generating business KPIs…</div>:filtered.map(c=><article className={'catalogCard '+(selected.has(c.id)?'selected':'')} key={c.id} onClick={()=>toggle(c.id)}><button className="catalogCheck" onClick={e=>{e.stopPropagation();toggle(c.id)}}>{selected.has(c.id)?<CheckSquare/>:<Square/>}</button><div className="catalogCardTop"><span className="catalogCategoryPill">{c.category}</span><span className="catalogConfidence">{Math.round(c.confidence*100)}% confidence</span></div><h3>{c.name.replaceAll('_',' ')}</h3><p>{c.description}</p><div className="catalogRefs">{c.fields.slice(0,3).map(f=><span key={f}>{f}</span>)}</div><code>{c.expression.split('\n').slice(1).join(' ')}</code><div className="catalogCardActions"><span><Table2 size={12}/>{c.table}</span><button onClick={e=>{e.stopPropagation();setEditing(structuredClone(c))}}><Pencil size={13}/>Edit</button></div></article>)}</section>
   </div>
   {editing&&<div className="modalShade" onMouseDown={()=>setEditing(null)}><div className="modalCard catalogEditModal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">EDIT SUGGESTED MEASURE</span><h3>{editing.name}</h3></div><button onClick={()=>setEditing(null)}><X/></button></div><label>Measure name<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value.replace(/\s+/g,'_')})}/></label><label>Description<input value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>DAX-style expression<textarea rows={12} value={editing.expression} onChange={e=>setEditing({...editing,expression:e.target.value})}/></label><div className="catalogEditHelp"><Calculator size={15}/>You can alter the AI suggestion before creating it. The backend validates it again during Create Selected.</div><div className="dialogActions"><button onClick={()=>setEditing(null)}>Cancel</button><button className="primary" onClick={()=>applyEdit(editing)}><Save size={14}/>Use Edited Measure</button></div></div></div>}
 </div>
}
