import {useEffect,useRef,useState} from 'react';
import {Database,FileSpreadsheet,FileJson,UploadCloud,RefreshCcw,Plus,Cloud,Table2,CheckCircle2,Zap,Gauge,PanelLeftClose,PanelLeftOpen,Trash2,FolderOpen,Combine,FileCode2,Layers3,PlugZap,ShieldCheck,Eye,EyeOff,List,ChevronDown,ChevronUp} from 'lucide-react';
import {api,apiForm} from '../api';import {useStudio} from '../store';

type Meta={schema:string,name:string,type:string,rowCount?:number,managed?:boolean,storage?:any,columns:{name:string,type:string,nullable:boolean,pk:boolean}[]};
type StorageStats={engine:string,tables:number,sourceBytes:number,compressedBytes:number,compressionRatio?:number|null,target:string,threads:number,memoryLimit:string,queryCache?:any};
type ExcelSheet={name:string;cols?:number;fields?:string[]};
function conciseSourceName(value:string){
 const raw=String(value||'Table').replace(/^(Imported_|ETL_)+/i,'').replace(/\.(csv|tsv|txt|xlsx?|jsonl?|parquet|xml)$/i,'').replace(/[_ ]+\d{3,}$/,'').replace(/[^A-Za-z0-9_ ]+/g,'_').replace(/_+/g,'_').trim();
 return (raw||'Table').slice(0,48);
}
function importedQueryName(result:any){return String(result?.displayName||conciseSourceName(result?.table||'Table'));}
export default function DataWorkbench(){
 const{load,setView,project}=useStudio();const[sourcesVisible,setSourcesVisible]=useState(true);const[activeSource,setActiveSource]=useState('none');const[storage,setStorage]=useState<StorageStats|null>(null);const[meta,setMeta]=useState<Meta[]>([]);const[selected,setSelected]=useState<Meta|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[fileRef]=[useRef<HTMLInputElement>(null)];const[folderRef]=[useRef<HTMLInputElement>(null)];const mainRef=useRef<HTMLDivElement>(null);const[cloud,setCloud]=useState<string>('google_sheets');const[url,setUrl]=useState('');const[accessToken,setAccessToken]=useState('');const[showSecret,setShowSecret]=useState(false);const[sheetRange,setSheetRange]=useState('A:ZZ');const[showManualRange,setShowManualRange]=useState(false);const[connectorCatalog,setConnectorCatalog]=useState<any[]>([]);const[pendingExcel,setPendingExcel]=useState<{file:File;sheets:ExcelSheet[];selected:string[]}|null>(null);const[pendingSheets,setPendingSheets]=useState<{url:string;accessToken:string|undefined;sheets:{title:string;sheetId:number;index:number;fallback?:boolean}[];selected:string[]}|null>(null);const[pendingTables,setPendingTables]=useState<{tables:{name:string}[];selected:string[]}|null>(null);const[db,setDb]=useState<any>({server:'',host:'',port:'',database:'',user:'',password:'',driver:'ODBC Driver 18 for SQL Server',sslmode:'prefer',encrypt:true,trustServerCertificate:false,trustedConnection:false});const[dbQuery,setDbQuery]=useState('SELECT * FROM ');const[dbName,setDbName]=useState('');const[connectionOk,setConnectionOk]=useState(false);
 const refresh=()=>api<Meta[]>('/metadata').then(x=>{setMeta(x);if(selected)setSelected(x.find(z=>z.name===selected.name)||null)});
 const refreshStorage=()=>api<StorageStats>('/storage/stats').then(setStorage).catch(()=>{});
 const optimizeStorage=async()=>{setBusy(true);setMsg('Optimizing local columnar storage…');try{const r=await api<StorageStats>('/storage/optimize',{method:'POST'});setStorage(r);setMsg(`Storage optimized. ${r.compressionRatio?`${r.compressionRatio}× actual compression across measured imports.`:'ZSTD columnar files rewritten.'}`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const startTransform=async(table:string,queryName?:string)=>{const existing=project?.transform.queries.find((q:any)=>q.source===table);if(existing){setView('transform');return;}const r=await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:table,queryName})});await load();setMsg(`${r.queryName} added to Transform. Build ETL steps, then Close & Apply to create this report's model table.`);setView('transform')};
 useEffect(()=>{refresh();refreshStorage();api<any[]>('/connectors').then(setConnectorCatalog).catch(()=>{})},[]);
 useEffect(()=>{mainRef.current?.scrollTo({top:0});mainRef.current?.querySelector<HTMLElement>('.connectorFocusGlass')?.scrollTo({top:0});setMsg('');setConnectionOk(false)},[activeSource]);
 async function importOneFile(file:File,uploadName?:string,sheet?:string){const fd=new FormData();fd.append('file',file,uploadName||file.name);if(sheet)fd.append('sheet',sheet);return await apiForm<any>('/files/import',fd)}
 function openFilePicker(accept:string){const el=fileRef.current;if(!el)return;el.accept=accept;el.value='';el.click()}
 async function inspectOrUpload(files:File[]){if(files.length===1&&/\.xlsx?$/i.test(files[0].name)){setBusy(true);setMsg('Reading workbook sheets…');try{const fd=new FormData();fd.append('file',files[0]);const info=await apiForm<any>('/files/excel/sheets',fd);const sheets:ExcelSheet[]=(info.sheets||[]).map((s:any)=>typeof s==='string'?{name:s}:s).filter((s:any)=>s?.name);if(sheets.length>1){setPendingExcel({file:files[0],sheets,selected:sheets.map(s=>s.name)});setMsg('Choose the worksheets to import.');return}}catch(e:any){setMsg('Workbook inspection failed: '+e.message);return}finally{setBusy(false)}}await uploadFiles(files)}
 async function importSelectedExcelSheets(){if(!pendingExcel||!pendingExcel.selected.length)return;setBusy(true);setPendingExcel(null);const selected=pendingExcel.selected;const importedAll:any[]=[];const seenTables=new Set<string>();const failures:string[]=[];try{for(let i=0;i<selected.length;i++){const sheetTitle=selected[i];setMsg(`Importing worksheet ${i+1}/${selected.length}: ${sheetTitle}…`);try{const d=await importOneFile(pendingExcel.file,undefined,sheetTitle);if(seenTables.has(d.table))throw new Error(`The backend returned the duplicate table id "${d.table}". Rebuild the bundled backend before importing multiple worksheets.`);seenTables.add(d.table);importedAll.push(d);if(!project?.transform.queries.find((q:any)=>q.source===d.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:d.table,queryName:importedQueryName(d)})})};}catch(e:any){failures.push(`${sheetTitle}: ${e.message}`);}}if(importedAll.length)await showImportedInData(importedAll,`${importedAll.length} worksheet${importedAll.length===1?'':'s'} imported as separate tables and added to Transform.${failures.length?` ${failures.length} failed: ${failures.join(' | ')}`:''}`);else throw new Error(failures.join(' | ')||'No worksheets were imported.');}catch(e:any){setMsg('Import failed: '+e.message);}finally{setBusy(false);}}
 async function showImportedInData(imported:any[],message:string){const fresh=await api<Meta[]>('/metadata');setMeta(fresh);const first=imported[0]?.table;setSelected(fresh.find(x=>x.name===first)||null);setActiveSource('workspace');await refreshStorage();await load();setMsg(message)}
 async function uploadFiles(files:File[]){if(!files.length)return;setBusy(true);setMsg('');try{const imported:any[]=[];for(const file of files){setMsg(`Importing ${file.name} (${imported.length+1}/${files.length})…`);const d=await importOneFile(file);imported.push(d);if(!project?.transform.queries.find((q:any)=>q.source===d.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:d.table,queryName:importedQueryName(d)})})}}await showImportedInData(imported,`${imported.length} data source${imported.length===1?'':'s'} imported. The new table${imported.length===1?' is':'s are'} visible here in Data and already available in Transform.`)}catch(e:any){setMsg('Import failed: '+e.message)}finally{setBusy(false)}}
 function openFolderPicker(){const el=folderRef.current;if(!el)return;el.setAttribute('webkitdirectory','');el.setAttribute('directory','');el.value='';el.click()}
 async function appendFolderFiles(files:File[]){const supported=files.filter(f=>/\.(csv|tsv|txt|xlsx|xls|json|jsonl|parquet|xml)$/i.test(f.name));if(!supported.length){setMsg('No supported CSV, Excel, or JSON files were found in the selected folder.');return}setBusy(true);setMsg('');try{const staged:any[]=[];const root=((supported[0] as any).webkitRelativePath||'Folder').split('/')[0]||'Folder';for(let i=0;i<supported.length;i++){const f=supported[i];const rel=((f as any).webkitRelativePath||f.name).replace(/[\\/]+/g,'_');setMsg(`Folder import: ${i+1}/${supported.length} · ${rel}`);staged.push(await importOneFile(f,rel))}setMsg(`Appending ${staged.length} imported files into one table…`);const result=await api<any>('/files/append-tables',{method:'POST',body:JSON.stringify({tables:staged.map(x=>x.table),name:`${root}_Combined`,schemaMode:'by_name',removeSources:true})});if(!project?.transform.queries.find((q:any)=>q.source===result.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:result.table,queryName:importedQueryName(result)})})}await showImportedInData([result],`${supported.length} file${supported.length===1?'':'s'} from ${root} were appended into ${result.table} (${Number(result.rows||0).toLocaleString()} rows). ${result.warnings?.length?result.warnings.join(' '):'Columns were aligned safely by name.'}`)}catch(e:any){setMsg('Folder append failed: '+e.message)}finally{setBusy(false)}}
 async function importCloud(overrideSheetRange?:string){if(!url)return;setBusy(true);setMsg('Connecting securely and downloading data…');try{const d=await api<any>('/cloud/import',{method:'POST',body:JSON.stringify({sourceType:cloud,url,accessToken:accessToken||undefined,sheetRange:cloud==='google_sheets'?(overrideSheetRange||sheetRange||undefined):undefined})});if(!project?.transform.queries.find((q:any)=>q.source===d.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:d.table,queryName:importedQueryName(d)})})}await showImportedInData([d],`${d.table} imported (${Number(d.rows||0).toLocaleString()} rows) and is ready in Transform.`)}catch(e:any){setMsg('Cloud import failed: '+e.message)}finally{setBusy(false)}}
 async function detectSheets(){if(!url)return;setBusy(true);setMsg('Detecting sheets in the spreadsheet…');try{const r=await api<any>('/cloud/sheets-list',{method:'POST',body:JSON.stringify({url,accessToken:accessToken||undefined})});const sheets=(r.sheets||[]);const isFallback=sheets.length===1&&sheets[0]?.fallback;setPendingSheets({url,accessToken:accessToken||undefined,sheets,selected:sheets.map((s:any)=>s.title)});setMsg(isFallback?'No OAuth token — only the default sheet is available. Add a token to see all tabs.':'Found '+sheets.length+' sheet'+(sheets.length===1?'':'s')+'. Select which to import.');}catch(e:any){setMsg('Sheet detection failed: '+(e.message||String(e))+'  — You can still type a range manually below.')}finally{setBusy(false)}}
 async function importSelectedSheets(){if(!pendingSheets||!pendingSheets.selected.length)return;setBusy(true);setPendingSheets(null);const selected=pendingSheets.selected;const importedAll:any[]=[];try{for(let i=0;i<selected.length;i++){const sheetTitle=selected[i];const range=`'${sheetTitle.replace(/'/g,"''")}!A:ZZ`;setMsg(`Importing sheet ${i+1}/${selected.length}: ${sheetTitle}…`);try{const d=await api<any>('/cloud/import',{method:'POST',body:JSON.stringify({sourceType:'google_sheets',url:pendingSheets.url,accessToken:pendingSheets.accessToken,sheetRange:range,name:sheetTitle})});importedAll.push(d);if(!project?.transform.queries.find((q:any)=>q.source===d.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:d.table,queryName:importedQueryName(d)})})};}catch(e:any){setMsg(`Sheet "${sheetTitle}" failed: ${e.message}`);}}if(importedAll.length)await showImportedInData(importedAll,`${importedAll.length} sheet${importedAll.length===1?'':'s'} imported from Google Sheets and ready in Transform.`);}catch(e:any){setMsg('Import failed: '+e.message);}finally{setBusy(false);}}
 function databaseConfig(){return activeSource==='sqlserver'?{...db,server:db.server||db.host,port:db.port?Number(db.port):undefined}:{...db,host:db.host||db.server,port:db.port?Number(db.port):5432}}
 async function testDatabase(){setBusy(true);setConnectionOk(false);setMsg('Testing encrypted connection…');try{const r=await api<any>('/connections/test',{method:'POST',body:JSON.stringify({type:activeSource,config:databaseConfig()})});setConnectionOk(!!r.ok);setMsg(r.message||'Connection successful.')}catch(e:any){setMsg('Connection test failed: '+e.message)}finally{setBusy(false)}}
 async function detectTables(){setBusy(true);setConnectionOk(false);setMsg('Detecting tables…');try{const r=await api<any>('/database/tables-list',{method:'POST',body:JSON.stringify({sourceType:activeSource,config:databaseConfig()})});const tables=r.tables||[];setPendingTables({tables,selected:tables.map((t:any)=>t.name)});setConnectionOk(true);setMsg('Found '+tables.length+' table'+(tables.length===1?'':'s')+'. Select which to import.');}catch(e:any){setMsg('Table detection failed: '+e.message)}finally{setBusy(false)}}
 async function importSelectedTables(){if(!pendingTables||!pendingTables.selected.length)return;setBusy(true);setPendingTables(null);const selected=pendingTables.selected;const importedAll:any[]=[];try{for(let i=0;i<selected.length;i++){const tableTitle=selected[i];setMsg(`Importing table ${i+1}/${selected.length}: ${tableTitle}…`);try{const query = activeSource==='sqlserver'? `SELECT * FROM [${tableTitle}]` : `SELECT * FROM "${tableTitle}"`;const d=await api<any>('/database/import',{method:'POST',body:JSON.stringify({sourceType:activeSource,config:databaseConfig(),query:query,name:tableTitle})});importedAll.push(d);if(!project?.transform.queries.find((q:any)=>q.source===d.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:d.table,queryName:importedQueryName(d)})})};}catch(e:any){setMsg(`Table "${tableTitle}" failed: ${e.message}`);}}if(importedAll.length)await showImportedInData(importedAll,`${importedAll.length} table${importedAll.length===1?'':'s'} imported from database and ready in Transform.`);}catch(e:any){setMsg('Import failed: '+e.message);}finally{setBusy(false);}}
 async function importDatabase(){setBusy(true);setMsg('Running read-only query and importing result…');try{const d=await api<any>('/database/import',{method:'POST',body:JSON.stringify({sourceType:activeSource,config:databaseConfig(),query:dbQuery,name:dbName||undefined})});if(!project?.transform.queries.find((q:any)=>q.source===d.table)){await api<any>('/transform/add-source',{method:'POST',body:JSON.stringify({physicalTable:d.table,queryName:importedQueryName(d)})})}await showImportedInData([d],`${d.table} imported from ${activeSource==='sqlserver'?'SQL Server':'PostgreSQL'} (${Number(d.rows||0).toLocaleString()} rows).`)}catch(e:any){setMsg('Database import failed: '+e.message)}finally{setBusy(false)}}
 async function useInTransform(){if(!selected)return;setBusy(true);try{await startTransform(selected.name,conciseSourceName(selected.name))}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function deleteTable(){if(!selected)return;if(!selected.managed){setMsg('Reference/demo tables are protected. Only imported, processed, or generated tables can be deleted.');return}if(!confirm(`Delete ${selected.name}? This also removes ETL queries and semantic-model tables that depend directly on it.`))return;setBusy(true);try{const r=await api<any>('/data/tables/'+encodeURIComponent(selected.name),{method:'DELETE'});setSelected(null);await refresh();await refreshStorage();await load();setMsg(`Deleted ${r.table}. Related queries/model tables were removed.`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}

 return <div className={'workspaceGlass '+(!sourcesVisible?'dataSourcesHidden':'')}>
  {sourcesVisible&&<div className="paneGlass leftPaneGlass">
    <div className="paneTitleGlass"><span>Get Data</span><button className="iconGlass paneCollapseBtn" onClick={()=>setSourcesVisible(false)} title="Hide source navigation"><PanelLeftClose size={15}/></button></div>
    <div className="sourceGroupGlass">
      <small>WORKSPACE</small>
      <button className={'sourceGlass '+(activeSource==='workspace'?'active':'')} onClick={()=>{setActiveSource('workspace');setSelected(null)}}><Table2 size={16}/>Workspace Data</button>
    </div>
    <div className="sourceGroupGlass">
      <small>DATABASES</small>
      <button className={'sourceGlass '+(activeSource==='sqlserver'?'active':'')} onClick={()=>{setActiveSource('sqlserver');setSelected(null)}}><Database size={16}/>SQL Server / Azure SQL</button>
      <button className={'sourceGlass '+(activeSource==='postgresql'?'active':'')} onClick={()=>{setActiveSource('postgresql');setSelected(null)}}><Database size={16}/>PostgreSQL</button>
    </div>
    <div className="sourceGroupGlass">
      <small>FILES</small>
      <button className="sourceGlass" onClick={()=>openFilePicker('.csv,.tsv,.txt,.xlsx,.xls')}><FileSpreadsheet size={16}/>CSV / Excel</button>
      <button className="sourceGlass" onClick={()=>openFilePicker('.json,.jsonl')}><FileJson size={16}/>JSON / JSONL</button>
      <button className="sourceGlass" onClick={()=>openFilePicker('.parquet')}><Layers3 size={16}/>Parquet</button>
      <button className="sourceGlass" onClick={()=>openFilePicker('.xml')}><FileCode2 size={16}/>XML</button>
      <button className="sourceGlass folderAppendSource" onClick={openFolderPicker}><FolderOpen size={16}/>Folder → Append</button>
      <input ref={fileRef} hidden multiple type="file" accept=".csv,.tsv,.txt,.xlsx,.xls,.json,.jsonl,.parquet,.xml" onChange={e=>{inspectOrUpload(Array.from(e.target.files||[]));e.currentTarget.value=''}}/>
      <input ref={folderRef} hidden multiple type="file" accept=".csv,.tsv,.txt,.xlsx,.xls,.json,.jsonl,.parquet,.xml" onChange={e=>{appendFolderFiles(Array.from(e.target.files||[]));e.currentTarget.value=''}}/>
    </div>
    <div className="sourceGroupGlass">
      <small>CLOUD</small>
      <button className={'sourceGlass '+(activeSource==='sharepoint'?'active':'')} onClick={()=>{setCloud('sharepoint');setActiveSource('sharepoint');setSelected(null)}}><Cloud size={16}/>SharePoint</button>
      <button className={'sourceGlass '+(activeSource==='onedrive'?'active':'')} onClick={()=>{setCloud('onedrive');setActiveSource('onedrive');setSelected(null)}}><Cloud size={16}/>OneDrive</button>
      <button className={'sourceGlass '+(activeSource==='google_sheets'?'active':'')} onClick={()=>{setCloud('google_sheets');setActiveSource('google_sheets');setSelected(null)}}><Cloud size={16}/>Google Sheets</button>
    </div>
    <div className="sourceGroupGlass enterpriseSources">
      <small>ENTERPRISE / MORE SOURCES</small>
      {connectorCatalog.filter((c:any)=>!['sqlserver','postgresql','csv','excel','json','sharepoint','onedrive','google_sheets','folder'].includes(c.id)).map((c:any)=><button key={c.id} className={'sourceGlass '+(activeSource===c.id?'active':'')} onClick={()=>{setActiveSource(c.id);setSelected(null)}} title={c.mode}><Database size={16}/>{c.name}</button>)}
    </div>
  </div>}

  <div className="mainPanelGlass" ref={mainRef}>
    {activeSource==='none'?<div className="connectorFocusGlass">
      <div className="connectorFocusCardGlass">
        <div className="landingTitleRowGlass"><div><span className="eyebrowGlass">GET DATA</span>
        <h2>Choose a Data Source</h2></div>{!sourcesVisible&&<button className="panelRestoreBtnGlass" onClick={()=>setSourcesVisible(true)}><PanelLeftOpen size={15}/>Show Sources</button>}</div>
        <p>Start with one or several sources. Multi-file import keeps each file as a separate managed table. <b>Folder → Append</b> selects all supported files and builds one combined table. After every import, VTAB returns here to the Data page.</p>
        <div className="dataBatchHintGlass"><b>Folder append:</b> files are streamed into columnar staging tables, schemas aligned by column name, and appended into one Parquet/ZSTD table.</div>
        <div className="sourceLandingGridGlass">
          <button className="sourceCardGlass" style={{'--source-accent':'#2563eb'} as any} onClick={()=>setActiveSource('sqlserver')}><span className="sourceCardIconGlass"><Database size={24}/></span><span className="sourceTypeBadge">DATABASE</span><b>SQL Server</b><small>Server, Azure SQL, and Windows authentication</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#336791'} as any} onClick={()=>setActiveSource('postgresql')}><span className="sourceCardIconGlass"><Database size={24}/></span><span className="sourceTypeBadge">DATABASE</span><b>PostgreSQL</b><small>Secure import with SSL configuration</small></button>
          <button className="sourceCardGlass excelCard" style={{'--source-accent':'#16834a'} as any} onClick={()=>openFilePicker('.csv,.tsv,.txt,.xlsx,.xls')}><span className="sourceCardIconGlass"><FileSpreadsheet size={24}/></span><span className="sourceTypeBadge">FILE</span><b>CSV / Excel</b><small>Worksheet selection and multi-file loading</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#d97706'} as any} onClick={()=>openFilePicker('.json,.jsonl')}><span className="sourceCardIconGlass"><FileJson size={24}/></span><span className="sourceTypeBadge">FILE</span><b>JSON / JSONL</b><small>Nested records flattened automatically</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#7c3aed'} as any} onClick={()=>openFilePicker('.parquet')}><span className="sourceCardIconGlass"><Layers3 size={24}/></span><span className="sourceTypeBadge">COLUMNAR</span><b>Parquet</b><small>Fast schema-aware analytical import</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#ea580c'} as any} onClick={()=>openFilePicker('.xml')}><span className="sourceCardIconGlass"><FileCode2 size={24}/></span><span className="sourceTypeBadge">FILE</span><b>XML</b><small>Elements, attributes, and repeated records</small></button>
          <button className="sourceCardGlass folderAppendCard" style={{'--source-accent':'#4f46e5'} as any} onClick={openFolderPicker}><span className="sourceCardIconGlass"><Combine size={24}/></span><span className="sourceTypeBadge">BATCH</span><b>Folder → Append</b><small>Combine similarly structured files by column name</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#038387'} as any} onClick={()=>{setCloud('sharepoint');setActiveSource('sharepoint')}}><span className="sourceCardIconGlass"><Cloud size={24}/></span><span className="sourceTypeBadge">CLOUD</span><b>SharePoint</b><small>Public links or private OAuth access</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#0369a1'} as any} onClick={()=>{setCloud('onedrive');setActiveSource('onedrive')}}><span className="sourceCardIconGlass"><Cloud size={24}/></span><span className="sourceTypeBadge">CLOUD</span><b>OneDrive</b><small>Microsoft cloud files and shared links</small></button>
          <button className="sourceCardGlass" style={{'--source-accent':'#0f9d58'} as any} onClick={()=>{setCloud('google_sheets');setActiveSource('google_sheets')}}><span className="sourceCardIconGlass"><FileSpreadsheet size={24}/></span><span className="sourceTypeBadge">CLOUD</span><b>Google Sheets</b><small>Public exports or private sheet ranges</small></button>
        </div>
        <div className="storageAccelerationCardGlass">
          <div className="storageIcon"><Zap size={20}/></div>
          <div><small>LOCAL ACCELERATION ENGINE</small><b>{storage?.engine||'DuckDB + Parquet ZSTD'}</b><span>Columnar storage, filter/projection pushdown, and query caching.</span></div>
          <div className="storageMetric"><strong>{storage?.compressionRatio?`${storage.compressionRatio}×`:'—'}</strong><span>measured compression</span></div>
          <button className="btnGlass" onClick={optimizeStorage} disabled={busy}><Gauge size={14}/>Optimize</button>
        </div>
        <button className="btnGlass primary" style={{marginTop:24}} onClick={()=>setActiveSource('workspace')}><Table2 size={16}/>Browse Workspace Data</button>
      </div>
    </div>:activeSource==='workspace'?<>
      <div className="panelHeaderGlass">
        <div><span className="eyebrowGlass">DATA NAVIGATOR</span><h2>Workspace Data</h2><p>Existing workspace tables are reusable sources. Use them in Transform to add to the model.</p></div>
        <div className="toolbarGlass">{!sourcesVisible&&<button className="btnGlass" onClick={()=>setSourcesVisible(true)}><PanelLeftOpen size={15}/>Show Sources</button>}<button className="btnGlass" onClick={()=>{refresh();refreshStorage()}}><RefreshCcw size={15}/>Refresh</button><button className="btnGlass" onClick={optimizeStorage}><Zap size={15}/>Optimize</button><button className="btnGlass" onClick={openFolderPicker}><FolderOpen size={15}/>Folder Append</button><button className="btnGlass primary" onClick={()=>fileRef.current?.click()}><Plus size={15}/>Add Files</button></div>
      </div>
      {msg&&<div className={'successBannerGlass '+(/failed|error/i.test(msg)?'error':'')}><CheckCircle2 size={16}/>{msg}</div>}
      <div className="navigatorGlass">
        <div className="objectListGlass">{meta.map(t=><button key={t.name} onClick={()=>setSelected(t)} className={selected?.name===t.name?'selected':''}><Table2 size={16}/><div><b>{t.name}</b><small>{t.rowCount?.toLocaleString()||0} rows · {t.columns.length} cols {t.managed?'· Columnar':''}</small></div></button>)}</div>
        <div className="objectDetailsGlass">{selected?<><div className="objectHeroGlass"><div><small>{selected.schema} · {selected.managed?'MANAGED IMPORT':'TABLE'}</small><h3>{selected.name}</h3></div><div className="toolbarGlass"><span className="pillGlass">{selected.managed?'ZSTD Columnar':'Reference'}</span>{selected.storage?.compressedBytes&&<span className="pillGlass">{(selected.storage.compressedBytes/1024/1024).toFixed(2)} MB</span>}<button className="btnGlass primary" onClick={useInTransform}>Use in Transform</button>{selected.managed&&<button className="btnGlass danger" onClick={deleteTable}><Trash2 size={14}/>Delete Table</button>}</div></div><table className="tableGlass"><thead><tr><th>Column</th><th>Type</th><th>Nullable</th><th>Key</th></tr></thead><tbody>{selected.columns.map(c=><tr key={c.name}><td>{c.name}</td><td><span className="typeBadgeGlass">{c.type||'TEXT'}</span></td><td>{c.nullable?'Yes':'No'}</td><td>{c.pk?'PK':''}</td></tr>)}</tbody></table></>:<div className="emptyGlass">Select a workspace table to inspect it.</div>}</div>
      </div>
    </>:<div className="connectorFocusGlass">
      <div className="connectorFocusCardGlass">
        <span className="eyebrowGlass">GET DATA</span>
        <h2>{connectorCatalog.find((c:any)=>c.id===activeSource)?.name || (activeSource==='google_sheets'?'Google Sheets':activeSource==='sharepoint'?'SharePoint':activeSource==='onedrive'?'OneDrive':activeSource==='sqlserver'?'SQL Server':activeSource==='postgresql'?'PostgreSQL':'Data Source')}</h2>
        {(['sqlserver','postgresql'].includes(activeSource))?<div className="connectorFormGlass">
          <div className="connectorStepsGlass"><span className="active">1 <b>Connect</b></span><i/><span className={connectionOk?'active':''}>2 <b>Query</b></span><i/><span>3 <b>Load</b></span></div>
          <p>Credentials remain on this device and are used only for this import. Test the connection, then run a read-only SELECT query.</p>
          <div className="formGridGlass">
            <label><span>{activeSource==='sqlserver'?'Server':'Host'}</span><input className="inputGlass" value={activeSource==='sqlserver'?db.server:db.host} onChange={e=>setDb({...db,[activeSource==='sqlserver'?'server':'host']:e.target.value})} placeholder={activeSource==='sqlserver'?'server\\instance or hostname':'db.example.com'}/></label>
            <label><span>Port</span><input className="inputGlass" value={db.port} onChange={e=>setDb({...db,port:e.target.value})} placeholder={activeSource==='sqlserver'?'1433':'5432'}/></label>
            <label><span>Database</span><input className="inputGlass" value={db.database} onChange={e=>setDb({...db,database:e.target.value})} placeholder="Database name"/></label>
            <label><span>User</span><input className="inputGlass" value={db.user} onChange={e=>setDb({...db,user:e.target.value})} disabled={activeSource==='sqlserver'&&db.trustedConnection}/></label>
            <label className="secretFieldGlass"><span>Password</span><div><input className="inputGlass" type={showSecret?'text':'password'} value={db.password} onChange={e=>setDb({...db,password:e.target.value})} disabled={activeSource==='sqlserver'&&db.trustedConnection}/><button onClick={()=>setShowSecret(!showSecret)} title="Show or hide password">{showSecret?<EyeOff size={15}/>:<Eye size={15}/>}</button></div></label>
            {activeSource==='sqlserver'?<label><span>ODBC driver</span><input className="inputGlass" value={db.driver} onChange={e=>setDb({...db,driver:e.target.value})}/></label>:<label><span>SSL mode</span><select className="inputGlass" value={db.sslmode} onChange={e=>setDb({...db,sslmode:e.target.value})}><option>prefer</option><option>require</option><option>verify-ca</option><option>verify-full</option><option>disable</option></select></label>}
          </div>
          {activeSource==='sqlserver'&&<div className="optionRowGlass"><label><input type="checkbox" checked={db.trustedConnection} onChange={e=>setDb({...db,trustedConnection:e.target.checked})}/> Windows authentication</label><label><input type="checkbox" checked={db.encrypt} onChange={e=>setDb({...db,encrypt:e.target.checked})}/> Encrypt connection</label><label><input type="checkbox" checked={db.trustServerCertificate} onChange={e=>setDb({...db,trustServerCertificate:e.target.checked})}/> Trust server certificate</label></div>}
          <div className="queryBoxGlass"><div><label><span>Imported table name</span><input className="inputGlass" value={dbName} onChange={e=>setDbName(e.target.value)} placeholder="Sales_Import"/></label><span className="readOnlyBadge"><ShieldCheck size={13}/>Read-only SQL enforced</span></div><textarea value={dbQuery} onChange={e=>setDbQuery(e.target.value)} spellCheck={false}/></div>
          {msg&&<div className={'connectorMessageGlass '+(/failed|error/i.test(msg)?'error':'')}><PlugZap size={16}/>{msg}</div>}
          <div className="connectorActionsGlass"><button className="btnGlass" onClick={testDatabase} disabled={busy}><PlugZap size={15}/>Test connection</button><button className="btnGlass primary" onClick={detectTables} disabled={busy||!db.database}><List size={15}/>Detect Tables</button><button className="btnGlass" onClick={importDatabase} disabled={busy||!db.database||!dbQuery.trim()}><Database size={15}/>Run query</button></div>
        </div>:(['google_sheets','sharepoint','onedrive','rest','odata','graphql'].includes(activeSource))?<div className="connectorFormGlass">
          <div className="cloudProviderBadgeGlass"><Cloud size={22}/><div><b>{activeSource==='google_sheets'?'Google Sheets':activeSource==='sharepoint'?'Microsoft SharePoint':activeSource==='onedrive'?'Microsoft OneDrive':'Secure web source'}</b><span>Public links work without a token. Private files require an OAuth access token.</span></div></div>
          <label><span>Shared, export, or API URL</span><input className="inputGlass" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label>
          {activeSource==='google_sheets'&&<>
            <div className="gsheetDetectRow">
              <button className="btnGlass primary gsheetDetectBtn" onClick={detectSheets} disabled={busy||!url} title="Fetch sheet tab names from the spreadsheet">
                <List size={15}/>Detect Sheets
              </button>
              <span className="gsheetDetectHint">Detect all tabs, then pick which to import</span>
            </div>
            <div className="gsheetAdvancedToggle">
              <button className="btnGlass" onClick={()=>setShowManualRange(v=>!v)} style={{gap:4}}>
                {showManualRange?<ChevronUp size={13}/>:<ChevronDown size={13}/>}
                {showManualRange?'Hide':'Advanced'}: enter range manually
              </button>
            </div>
            {showManualRange&&<label><span>Worksheet / cell range <small>e.g. Sheet1!A:ZZ</small></span><input className="inputGlass" value={sheetRange} onChange={e=>setSheetRange(e.target.value)} placeholder="Sheet1!A:ZZ"/></label>}
          </>}
          <label className="secretFieldGlass"><span>OAuth access token <small>optional for public files</small></span><div><input className="inputGlass" type={showSecret?'text':'password'} value={accessToken} onChange={e=>setAccessToken(e.target.value)} placeholder="Paste a current bearer token"/><button onClick={()=>setShowSecret(!showSecret)}>{showSecret?<EyeOff size={15}/>:<Eye size={15}/>}</button></div></label>
          {msg&&<div className={'connectorMessageGlass '+(/failed|error/i.test(msg)?'error':'')}><UploadCloud size={16}/>{msg}</div>}
          <div className="connectorActionsGlass">{activeSource==='google_sheets'?<><button className="btnGlass primary" onClick={detectSheets} disabled={busy||!url}><List size={14}/>Detect Sheets</button><button className="btnGlass" onClick={()=>importCloud()} disabled={busy||!url}><UploadCloud size={14}/>Import / Refresh</button></>:<button className="btnGlass primary" onClick={()=>importCloud()} disabled={busy||!url}><UploadCloud size={14}/>Import / Refresh</button>}</div>
        </div>:<><p>This connector uses an optional vendor driver or endpoint configuration.</p><div className="connectorPlaceholderGlass"><Database size={28}/><b>Enterprise connection</b><span>{connectorCatalog.find((c:any)=>c.id===activeSource)?.mode||'DirectQuery / Import'}</span></div></>}
      </div>
    </div>}
  </div>
  {pendingExcel&&<div className="fancyDialogOverlay" onClick={e=>{if(e.target===e.currentTarget)setPendingExcel(null)}}><div className="fancyDialogContent gsheetPickerDialog"><div className="fancyDialogHeader"><span className="eyebrowGlass">EXCEL NAVIGATOR</span><h3>Choose worksheets to import</h3><p>{pendingExcel.file.name} contains {pendingExcel.sheets.length} worksheets. Select one or more to load as separate tables.</p></div><div className="gsheetPickerControls"><button className="btnGlass" onClick={()=>setPendingExcel({...pendingExcel,selected:pendingExcel.sheets.map((s:any)=>s.name||s)})}>Select all</button><button className="btnGlass" onClick={()=>setPendingExcel({...pendingExcel,selected:[]})}>Clear</button></div><div className="sheetChoiceGridGlass gsheetMultiGrid">{pendingExcel.sheets.map((sheetObj:any)=>{const sheet=sheetObj.name||sheetObj;const cols=sheetObj.cols;const isSelected=pendingExcel.selected.includes(sheet);return(<button key={sheet} className={isSelected?'selected':''} onClick={()=>{const next=isSelected?pendingExcel.selected.filter(t=>t!==sheet):[...pendingExcel.selected,sheet];setPendingExcel({...pendingExcel,selected:next})}}><span className="gsheetTabIcon"><FileSpreadsheet size={17}/></span><div style={{display:'flex',flexDirection:'column',alignItems:'flex-start',textAlign:'left'}}><span>{sheet}</span>{cols!==undefined&&<small style={{opacity:0.7,fontSize:11}} title={sheetObj.fields?.join(', ')}>{cols} columns {sheetObj.fields?.length?`(${sheetObj.fields.slice(0,2).join(', ')}${sheetObj.fields.length>2?', ...':''})`:''}</small>}</div>{isSelected&&<CheckCircle2 size={15}/>}</button>)})}</div><div className="fancyDialogActions"><button className="btnGlass" onClick={()=>setPendingExcel(null)}>Cancel</button><button className="btnGlass primary" onClick={importSelectedExcelSheets} disabled={busy||!pendingExcel.selected.length}><UploadCloud size={14}/>Import Selected ({pendingExcel.selected.length})</button></div></div></div>}
  {pendingSheets&&<div className="fancyDialogOverlay" onClick={e=>{if(e.target===e.currentTarget)setPendingSheets(null)}}><div className="fancyDialogContent gsheetPickerDialog"><div className="fancyDialogHeader"><span className="eyebrowGlass">GOOGLE SHEETS NAVIGATOR</span><h3>Select sheets to import</h3><p>{pendingSheets.sheets[0]?.fallback?'No OAuth token provided — only the default sheet is available. Provide a token to unlock all tabs.':pendingSheets.sheets.length+' sheet'+(pendingSheets.sheets.length===1?'':'s')+' found. Select one or more to import each as a separate table.'}</p></div><div className="gsheetPickerControls"><button className="btnGlass" onClick={()=>setPendingSheets({...pendingSheets,selected:pendingSheets.sheets.map(s=>s.title)})}>Select all</button><button className="btnGlass" onClick={()=>setPendingSheets({...pendingSheets,selected:[]})}>Clear</button></div><div className="sheetChoiceGridGlass gsheetMultiGrid">{pendingSheets.sheets.map(sheet=>{const isSelected=pendingSheets.selected.includes(sheet.title);return(<button key={sheet.sheetId} className={isSelected?'selected':''} onClick={()=>{const next=isSelected?pendingSheets.selected.filter(t=>t!==sheet.title):[...pendingSheets.selected,sheet.title];setPendingSheets({...pendingSheets,selected:next})}}><span className="gsheetTabIcon"><FileSpreadsheet size={17}/></span><span>{sheet.title}</span>{isSelected&&<CheckCircle2 size={15}/>}</button>)})}</div><div className="fancyDialogActions"><button className="btnGlass" onClick={()=>setPendingSheets(null)}>Cancel</button><button className="btnGlass primary" onClick={importSelectedSheets} disabled={busy||!pendingSheets.selected.length}><UploadCloud size={14}/>Import Selected ({pendingSheets.selected.length})</button></div></div></div>}
  {pendingTables&&<div className="fancyDialogOverlay" onClick={e=>{if(e.target===e.currentTarget)setPendingTables(null)}}><div className="fancyDialogContent gsheetPickerDialog"><div className="fancyDialogHeader"><span className="eyebrowGlass">DATABASE NAVIGATOR</span><h3>Choose tables to import</h3><p>Found {pendingTables.tables.length} tables. Select one or more to load as separate tables.</p></div><div className="gsheetPickerControls"><button className="btnGlass" onClick={()=>setPendingTables({...pendingTables,selected:pendingTables.tables.map(t=>t.name)})}>Select all</button><button className="btnGlass" onClick={()=>setPendingTables({...pendingTables,selected:[]})}>Clear</button></div><div className="sheetChoiceGridGlass gsheetMultiGrid">{pendingTables.tables.map(table=>{const isSelected=pendingTables.selected.includes(table.name);return(<button key={table.name} className={isSelected?'selected':''} onClick={()=>{const next=isSelected?pendingTables.selected.filter(t=>t!==table.name):[...pendingTables.selected,table.name];setPendingTables({...pendingTables,selected:next})}}><span className="gsheetTabIcon"><Database size={17}/></span><span>{table.name}</span>{isSelected&&<CheckCircle2 size={15}/>}</button>)})}</div><div className="fancyDialogActions"><button className="btnGlass" onClick={()=>setPendingTables(null)}>Cancel</button><button className="btnGlass primary" onClick={importSelectedTables} disabled={busy||!pendingTables.selected.length}><UploadCloud size={14}/>Import Selected ({pendingTables.selected.length})</button></div></div></div>}
 </div>

}
