import{useRef,useState}from'react';
import{Archive,AppWindow,Database,Download,FileArchive,FolderInput,ShieldCheck,Upload,CheckCircle2,AlertTriangle}from'lucide-react';
import{apiDownload,apiForm}from'../api';
import{useStudio}from'../store';

type PackageType='app'|'complete'|'data';
const cards=[
 {type:'app' as PackageType,ext:'.vtabapp',title:'Application Definition',contains:'UI + Model + ETL · NO DATA',icon:AppWindow,desc:'Portable report design, pages, visuals, semantic model, measures, relationships, transformations and RLS definitions. Business data is excluded.'},
 {type:'complete' as PackageType,ext:'.vtabpkg',title:'Complete Application',contains:'UI + Model + ETL + DATA',icon:FileArchive,desc:'Complete portable VTAB application including the processed data needed to open and work with the report on another machine.'},
 {type:'data' as PackageType,ext:'.vtabdata',title:'Data Package',contains:'DATA ONLY · NO REPORT UI',icon:Database,desc:'Portable managed tables and schemas only. Use it to reuse prepared data while building a different report experience.'},
];

export default function PackageWorkbench(){
 const{project,setView}=useStudio();
 const input=useRef<HTMLInputElement|null>(null);
 const[busy,setBusy]=useState('');const[msg,setMsg]=useState<{ok:boolean,text:string}|null>(null);const[inspection,setInspection]=useState<any>(null);
 const exportPkg=async(type:PackageType,ext:string)=>{try{setBusy(type);setMsg(null);const name=(project?.report?.name||project?.name||'VTAB_Application').replace(/[^a-z0-9_-]+/gi,'_');await apiDownload(`/packages/export/${type}`,`${name}${ext}`);setMsg({ok:true,text:`${ext} package created successfully.`})}catch(e:any){setMsg({ok:false,text:e.message||String(e)})}finally{setBusy('')}};
 const choose=()=>input.current?.click();
 const onFile=async(file?:File)=>{if(!file)return;setBusy('import');setMsg(null);setInspection(null);let browserWindow:Window|null=null;try{const inspectForm=new FormData();inspectForm.append('file',file);const info=await apiForm<any>('/packages/inspect',inspectForm);setInspection(info);const proceed=confirm(`Validated ${info.format}\n\nType: ${info.kind}\nTables: ${(info.tables||[]).length}\nCredentials included: No\n\nImport this package?`);if(!proceed){setMsg({ok:true,text:'Package validated. Import was cancelled.'});return}const desktop=(window as any).__VTAB_DESKTOP__;if(info.kind!=='data-only'&&!desktop?.openApplicationWindow)browserWindow=window.open('about:blank','_blank');const form=new FormData();form.append('file',file);const result=await apiForm<any>('/packages/import',form);if(result.project&&result.openReportId){const url=new URL(window.location.href);url.search='';url.hash='';url.searchParams.set('editReport',result.openReportId);if(desktop?.openApplicationWindow)await desktop.openApplicationWindow(url.toString());else if(browserWindow)browserWindow.location.href=url.toString();else window.open(url.toString(),'_blank');setMsg({ok:true,text:`Imported ${result.format} in a separate VTAB application window. This window and its current report were left unchanged.`})}else{browserWindow?.close();setView('data');setMsg({ok:true,text:`Imported ${result.tables?.length||0} data table(s) from ${result.format}. Open Data to inspect them.`})}}catch(e:any){browserWindow?.close();setMsg({ok:false,text:e.message||String(e)})}finally{setBusy('');if(input.current)input.current.value=''}};
 return <div className="page packagePage"><div className="packageHero"><div><span className="eyebrow">PORTABLE APPLICATION FORMAT</span><h1>Import & Export VTAB Packages</h1><p>VTAB Desktop uses exactly three standardized portable formats. Package manifests are checksum-validated and connection credentials are never exported.</p></div><button className="primary lg" onClick={choose} disabled={!!busy}><FolderInput size={18}/>Import VTAB Package</button><input ref={input} hidden type="file" accept=".vtabapp,.vtabpkg,.vtabdata" onChange={e=>onFile(e.target.files?.[0])}/></div>
 <div className="packageSecurity"><ShieldCheck size={19}/><div><b>Portable by design, credentials excluded</b><span>Passwords, OAuth tokens, API keys and secrets are not included. Imported applications must map or re-enter credentials on the destination environment.</span></div></div>
 <div className="packageCards">{cards.map(c=>{const Icon=c.icon;return <article className="packageCard" key={c.ext}><div className="packageCardTop"><span className="packageIcon"><Icon size={25}/></span><code>{c.ext}</code></div><h2>{c.title}</h2><strong>{c.contains}</strong><p>{c.desc}</p><button onClick={()=>exportPkg(c.type,c.ext)} disabled={!!busy}><Download size={16}/>{busy===c.type?'Creating package…':`Export ${c.ext}`}</button></article>})}</div>
 <div className="packageFlow"><div><Archive/><b>.vtabapp</b><span>Move/reuse report definition</span></div><i>or</i><div><FileArchive/><b>.vtabpkg</b><span>Move complete application</span></div><i>or</i><div><Database/><b>.vtabdata</b><span>Move data without UI</span></div></div>
 {inspection&&<div className="packageInspection"><CheckCircle2 size={18}/><div><b>Package validated</b><span>{inspection.format} · {inspection.kind} · {(inspection.tables||[]).length} table(s) · SHA-256 payload validation</span></div></div>}
 {msg&&<div className={'packageMessage '+(msg.ok?'ok':'bad')}>{msg.ok?<CheckCircle2 size={17}/>:<AlertTriangle size={17}/>}<span>{msg.text}</span></div>}
 <div className="packageRules"><h3>Format contract</h3><table><thead><tr><th>Format</th><th>Report UI</th><th>Model / ETL / Measures / RLS</th><th>Business Data</th><th>Credentials</th></tr></thead><tbody><tr><td><code>.vtabapp</code></td><td>Yes</td><td>Yes</td><td>No</td><td>Never</td></tr><tr><td><code>.vtabpkg</code></td><td>Yes</td><td>Yes</td><td>Yes</td><td>Never</td></tr><tr><td><code>.vtabdata</code></td><td>No</td><td>No</td><td>Yes</td><td>Never</td></tr></tbody></table></div>
 </div>
}
