import{useEffect,useMemo,useState}from'react';
import{CheckCircle2,Download,LoaderCircle,Play,RefreshCw}from'lucide-react';
import{api,apiDownloadPost}from'../api';

type ParameterOption={value:any;label:string};
const mm=(value:any,scale:number)=>Math.max(0,Number(value)||0)*scale;
const leaf=(field:string)=>String(field||'').split('.').pop()||String(field||'');
const rowValue=(row:any,field:string)=>row?.[field]??row?.[leaf(field)]??row?.[Object.keys(row||{}).find(key=>key.endsWith(`.${leaf(field)}`))||''];
const filename=(report:any)=>String(report?.rendering?.fileNameTemplate||report?.name||'Paginated_Report').replace(/\{\{[^}]+\}\}/g,'Report').replace(/[^A-Za-z0-9_.-]+/g,'_').replace(/\.pdf$/i,'')+'.pdf';
const staticOptions=(parameter:any):ParameterOption[]=>parameter?.availableValues?.staticValues?.length?parameter.availableValues.staticValues:(parameter?.values||[]).map((value:any)=>({value,label:String(value)}));
const rawParameterValue=(parameter:any,values:Record<string,any>)=>Object.prototype.hasOwnProperty.call(values,parameter.name)?values[parameter.name]:parameter.defaultValue;
const optionKey=(value:any)=>JSON.stringify(value);
const isEmpty=(value:any)=>value===undefined||value===null||value===''||(Array.isArray(value)&&!value.length);
const parameterLabel=(parameter:any,values:Record<string,any>,available:Record<string,ParameterOption[]>)=>{const raw=rawParameterValue(parameter,values),items=Array.isArray(raw)?raw:[raw],options=available[parameter.id]||staticOptions(parameter);return items.filter(value=>!isEmpty(value)).map(value=>options.find(option=>optionKey(option.value)===optionKey(value))?.label??String(value)).join(', ')};
const queryFilter=(parameter:any,value:any)=>({field:parameter.queryField||parameter.availableValues?.valueField,operator:parameter.filterOperator||(parameter.allowMultiple||parameter.type==='multi'?'in':'equals'),value});
const expression=(source:any,report:any,parameters:Record<string,any>,available:Record<string,ParameterOption[]>,rows:any[],page='1',total='…')=>String(source??'').replace(/\{\{\s*([^}]+?)\s*\}\}/g,(_match,key:string)=>{const now=new Date(),builtins:Record<string,string>={'Report.Name':report?.name||'Paginated Report','Report.ExecutionDate':now.toISOString().slice(0,10),'Report.ExecutionTime':now.toLocaleString(),'Report.PageNumber':page,'Report.TotalPages':total,'Report.RenderFormat':'PDF','Dataset.RecordCount':String(rows.length)};if(Object.prototype.hasOwnProperty.call(builtins,key))return builtins[key];const parameterMatch=key.match(/^Parameters?\.([^.]+)(?:\.(Value|Label))?$/);if(parameterMatch){const parameter=(report?.parameters||[]).find((item:any)=>item.name===parameterMatch[1]);if(!parameter)return'';const raw=rawParameterValue(parameter,parameters);return parameterMatch[2]==='Label'?parameterLabel(parameter,parameters,available):Array.isArray(raw)?raw.join(', '):String(raw??'')}if(key.startsWith('Dataset.First.'))return String(rowValue(rows[0],key.slice('Dataset.First.'.length))??'');if(key.startsWith('Filter.'))return'—';return''});
const fontWeight=(bold:any)=>bold?'700':'400';

function BandItems({items,report,parameters,available,rows,scale}:{items:any[];report:any;parameters:Record<string,any>;available:Record<string,ParameterOption[]>;rows:any[];scale:number}){
  return <>{(items||[]).map((item:any,index:number)=>{const positioned=item.xMm!==undefined||item.yMm!==undefined||item.widthMm!==undefined;const style:any={position:'absolute',left:mm(positioned?item.xMm:0,scale),top:mm(positioned?item.yMm:index*7,scale),width:mm(positioned?(item.widthMm||40):((item.widthPercent||100)/100)*(report?._sectionWidthMm||100),scale),height:mm(item.heightMm||8,scale),boxSizing:'border-box',display:'flex',alignItems:'center',overflow:'hidden',justifyContent:item.align==='center'?'center':item.align==='right'?'flex-end':'flex-start',textAlign:item.align||'left',fontFamily:item.fontFamily||'Segoe UI',fontSize:Math.max(5,Number(item.fontSize)||9)*scale/3.78,fontWeight:fontWeight(item.bold),fontStyle:item.italic?'italic':'normal',textDecoration:item.underline?'underline':'none',color:item.color||'#111827',background:item.background||'transparent',opacity:item.opacity??1,border:item.borderWidth?`${Math.max(1,item.borderWidth*scale/3.78)}px solid ${item.borderColor||'#cbd5e1'}`:'none',borderRadius:mm(item.borderRadius,scale),padding:mm(item.padding,scale)};
    if(item.type==='image')return <div key={item.id||index} style={style}><img src={item.value} alt="" style={{width:'100%',height:'100%',objectFit:item.imageFit||'contain',objectPosition:item.imagePosition||'center'}}/></div>;
    if(item.type==='line')return <div key={item.id||index} style={{...style,height:0,top:mm(item.yMm||0,scale)+mm((item.heightMm||1)/2,scale),border:0,borderTop:`${Math.max(1,Number(item.borderWidth)||1)}px ${item.lineStyle||'solid'} ${item.color||item.borderColor||'#64748b'}`}}/>;
    if(item.type==='shape')return <div key={item.id||index} style={style}/>;
    return <div key={item.id||index} style={style}>{expression(item.dynamicToken||item.value,report,parameters,available,rows)}</div>})}</>;
}

function ReportPaper({report,parameters,available,rows}:{report:any;parameters:Record<string,any>;available:Record<string,ParameterOption[]>;rows:any[]}){
  const page=report?.page||{},orientation=page.orientation||'portrait',dims=orientation==='landscape'?[Math.max(page.widthMm||210,page.heightMm||297),Math.min(page.widthMm||210,page.heightMm||297)]:[Math.min(page.widthMm||210,page.heightMm||297),Math.max(page.widthMm||210,page.heightMm||297)];
  const scale=Math.min(3.2,1050/dims[0]),margins=page.margins||{},innerWidth=dims[0]-(Number(margins.left)||12)-(Number(margins.right)||12),headerHeight=report.header?.visible===false?0:Number(page.headerHeightMm)||24,footerHeight=report.footer?.visible===false?0:Number(page.footerHeightMm)||16,contentHeight=Math.max(20,dims[1]-(Number(margins.top)||12)-(Number(margins.bottom)||12)-headerHeight-footerHeight),decorated={...report,_sectionWidthMm:innerWidth};
  const columns=report.table?.columns||[],layout=report.contentLayout||{},tableWidth=Math.min(innerWidth-(Number(layout.tableXmm)||0),columns.reduce((sum:number,column:any)=>sum+(Number(column.widthMm)||30),0)||innerWidth),columnTemplate=columns.map((column:any)=>`${Math.max(8,Number(column.widthMm)||30)}fr`).join(' '),visibleRows=rows.length?rows.slice(0,Math.max(1,Math.floor((contentHeight-(Number(layout.tableYmm)||0)-10)/(Number(report.table?.rowHeightMm)||8)))):Array.from({length:4},()=>null);
  return <div className="paginatedServicePaper" style={{width:dims[0]*scale,height:dims[1]*scale,padding:`${mm(margins.top||12,scale)}px ${mm(margins.right||12,scale)}px ${mm(margins.bottom||12,scale)}px ${mm(margins.left||12,scale)}px`}}>
    {headerHeight>0&&<section className="paginatedServiceSection" style={{height:mm(headerHeight,scale)}}><BandItems items={report.header?.items||[]} report={decorated} parameters={parameters} available={available} rows={rows} scale={scale}/></section>}
    <section className="paginatedServiceSection paginatedServiceBody" style={{height:mm(contentHeight,scale)}}><BandItems items={report.bodyItems||[]} report={decorated} parameters={parameters} available={available} rows={rows} scale={scale}/>{!!columns.length&&<div className="paginatedServiceTable" style={{position:'absolute',left:mm(layout.tableXmm,scale),top:mm(layout.tableYmm,scale),width:mm(tableWidth,scale),borderColor:report.table?.borderColor||'#cbd5e1'}}>
      <div className="paginatedServiceTableHead" style={{gridTemplateColumns:columnTemplate,minHeight:mm(report.table?.headerHeightMm||9,scale),background:report.table?.headerBackground||'#e8eef7',color:report.table?.headerColor||'#111827',fontFamily:report.table?.headerFontFamily||'Segoe UI',fontSize:Math.max(6,Number(report.table?.headerFontSize)||9)*scale/3.78,fontWeight:fontWeight(report.table?.headerBold!==false),fontStyle:report.table?.headerItalic?'italic':'normal'}}>{columns.map((column:any)=><span key={column.id} style={{textAlign:column.headerAlign||column.align||'left',background:column.headerBackground,color:column.headerColor,fontFamily:column.headerFontFamily,fontSize:column.headerFontSize?column.headerFontSize*scale/3.78:undefined,fontWeight:column.headerBold===undefined?undefined:fontWeight(column.headerBold),fontStyle:column.headerItalic?'italic':undefined}}>{column.label}</span>)}</div>
      {visibleRows.map((row:any,index:number)=><div className="paginatedServiceTableRow" key={index} style={{gridTemplateColumns:columnTemplate,minHeight:mm(report.table?.rowHeightMm||8,scale),background:index%2&&report.table?.alternateRows!==false?report.table?.alternateBackground||'#f8fafc':'#fff',color:report.table?.bodyColor||'#1f2937',fontFamily:report.table?.bodyFontFamily||'Segoe UI',fontSize:Math.max(6,Number(report.table?.fontSize)||9)*scale/3.78,fontWeight:fontWeight(report.table?.bodyBold),fontStyle:report.table?.bodyItalic?'italic':'normal'}}>{columns.map((column:any)=><span key={column.id} style={{textAlign:column.valueAlign||column.align||'left',background:column.valueBackground,color:column.valueColor,fontFamily:column.valueFontFamily,fontSize:column.valueFontSize?column.valueFontSize*scale/3.78:undefined,fontWeight:column.valueBold===undefined?undefined:fontWeight(column.valueBold),fontStyle:column.valueItalic?'italic':undefined}}>{row?String(rowValue(row,column.field)??''):'—'}</span>)}</div>)}
    </div>}</section>
    {footerHeight>0&&<section className="paginatedServiceSection" style={{height:mm(footerHeight,scale)}}><BandItems items={report.footer?.items||[]} report={decorated} parameters={parameters} available={available} rows={rows} scale={scale}/></section>}
  </div>;
}

export default function PaginatedReportViewer({reportId,project,filters,cloudMode,initialDefinitionId}:{reportId:string;project:any;filters:any[];cloudMode:boolean;initialDefinitionId?:string}){
  const reports=project?.paginatedReports||[];const[activeId,setActiveId]=useState(initialDefinitionId||reports[0]?.id||''),[parameters,setParameters]=useState<Record<string,any>>({}),[available,setAvailable]=useState<Record<string,ParameterOption[]>>({}),[optionBusy,setOptionBusy]=useState(false),[rows,setRows]=useState<any[]>([]);const[busy,setBusy]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState(''),[complete,setComplete]=useState(false),[hasRun,setHasRun]=useState(false);const active=reports.find((item:any)=>item.id===activeId)||reports[0];
  const query=async(payload:any)=>api<any>(cloudMode?'/published/query-snapshot':`/published/${reportId}/query`,{method:'POST',body:JSON.stringify(cloudMode?{...payload,project}:payload)});
  useEffect(()=>{const defaults:Record<string,any>={};(active?.parameters||[]).forEach((parameter:any)=>{defaults[parameter.name]=parameter.defaultValue??(parameter.allowMultiple||parameter.type==='multi'?[]:'')});setParameters(defaults);setAvailable({});setRows([]);setHasRun(false);setComplete(false);setError('')},[active?.id]);
  const visibleParameters=useMemo(()=>(active?.parameters||[]).filter((parameter:any)=>(parameter.visibility||'visible')==='visible'),[active]);
  const missingRequired=visibleParameters.some((parameter:any)=>parameter.required&&isEmpty(rawParameterValue(parameter,parameters)));
  const dependencyKey=JSON.stringify(visibleParameters.map((parameter:any)=>[parameter.name,rawParameterValue(parameter,parameters)]));
  const parameterFilters=()=>visibleParameters.filter((parameter:any)=>parameter.usedInQuery&&parameter.queryField&&!isEmpty(rawParameterValue(parameter,parameters))).map((parameter:any)=>queryFilter(parameter,rawParameterValue(parameter,parameters)));
  const loadAvailableValues=async()=>{if(!active)return;setOptionBusy(true);try{const next:Record<string,ParameterOption[]>={};for(const parameter of active.parameters||[]){const mode=parameter.availableValues?.mode||(parameter.values?.length?'static':'none');if(mode==='static'){next[parameter.id]=staticOptions(parameter);continue}if(mode!=='dataset'||!parameter.availableValues?.valueField)continue;const dependencyFilters:any[]=[];let ready=true;for(const dependencyId of parameter.dependencies||[]){const dependency=(active.parameters||[]).find((item:any)=>item.id===dependencyId),value=dependency&&rawParameterValue(dependency,parameters),field=dependency?.queryField||dependency?.availableValues?.valueField;if(!dependency||!field||isEmpty(value)){ready=false;break}dependencyFilters.push({field,operator:Array.isArray(value)?'in':'equals',value})}if(!ready){next[parameter.id]=[];continue}const valueField=parameter.availableValues.valueField,labelField=parameter.availableValues.labelField||valueField,result=await query({dimensions:Array.from(new Set([valueField,labelField])),measures:[],filters:[...filters,...dependencyFilters],sort:[],limit:5000,roleId:project.security?.activeRoleId}),seen=new Set<string>();next[parameter.id]=[];for(const row of result.rows||[]){const value=rowValue(row,valueField);if(value===undefined||value===null||seen.has(optionKey(value)))continue;seen.add(optionKey(value));next[parameter.id].push({value,label:String(rowValue(row,labelField)??value)})}}setAvailable(next)}catch(reason:any){setError(`Could not load report parameter values. ${reason?.message||reason}`)}finally{setOptionBusy(false)}};
  useEffect(()=>{const timer=setTimeout(()=>void loadAvailableValues(),120);return()=>clearTimeout(timer)},[active?.id,dependencyKey]);
  const run=async()=>{if(!active||missingRequired)return;setRunning(true);setError('');try{const columns=active.table?.columns||[],measuresRegistry=project?.model?.measures||{},dimensions=columns.map((column:any)=>column.field).filter((field:string)=>!Object.prototype.hasOwnProperty.call(measuresRegistry,field)),measures=columns.map((column:any)=>column.field).filter((field:string)=>Object.prototype.hasOwnProperty.call(measuresRegistry,field)),result=await query({dimensions,measures,filters:[...filters,...parameterFilters()],sort:active.table?.sort||[],limit:500,roleId:project.security?.activeRoleId});setRows(result.rows||[]);setHasRun(true)}catch(reason:any){setError(reason?.message||String(reason))}finally{setRunning(false)}};
  const generate=async()=>{if(!active||busy||missingRequired)return;setBusy(true);setError('');setComplete(false);try{const payload={definitionId:active.id,filters,parameters,roleId:project.security?.activeRoleId,...(cloudMode?{project}:{})};await apiDownloadPost(cloudMode?'/published/paginated/pdf-snapshot':`/published/${reportId}/paginated/pdf`,filename(active),payload);setComplete(true)}catch(reason:any){setError(reason?.message||String(reason))}finally{setBusy(false)}};
  const setParameter=(parameter:any,value:any)=>{setParameters(current=>({...current,[parameter.name]:value}));setHasRun(false)};
  if(!active)return <div className="paginatedServiceEmpty">No paginated report was included in this publication.</div>;
  return <div className="paginatedService paginatedServiceModern"><main><div className="paginatedServiceHeading"><div>{reports.length>1?<label className="paginatedReportSelector"><span>Paginated report</span><select value={active.id} onChange={event=>setActiveId(event.target.value)}>{reports.map((report:any)=><option key={report.id} value={report.id}>{report.name}</option>)}</select></label>:<><small>PUBLISHED PAGINATED REPORT</small><h2>{active.name}</h2></>}</div><button onClick={generate} disabled={busy||missingRequired}>{busy?<LoaderCircle className="spin" size={17}/>:<Download size={17}/>} {busy?'Generating PDF…':'Download PDF'}</button></div>
    <section className="paginatedParameterBar"><div className="paginatedParameterBarTitle"><b>Report parameters</b><small>Select values and run the report.</small></div><div className="paginatedParameterFields">{!visibleParameters.length?<span className="paginatedNoParameters">No visible parameters</span>:visibleParameters.map((parameter:any)=>{const options=available[parameter.id]||staticOptions(parameter),multiple=parameter.allowMultiple||parameter.type==='multi',value=rawParameterValue(parameter,parameters),mode=parameter.availableValues?.mode||(parameter.values?.length?'static':'none');return <label key={parameter.id}><span>{parameter.prompt||parameter.label||parameter.name}{parameter.required?' *':''}</span>{mode!=='none'?<select multiple={multiple} disabled={optionBusy} value={multiple?(Array.isArray(value)?value.map(optionKey):[]):isEmpty(value)?'':optionKey(value)} onChange={event=>setParameter(parameter,multiple?Array.from(event.target.selectedOptions).map(option=>JSON.parse(option.value)):event.target.value?JSON.parse(event.target.value):'')}>{!multiple&&<option value="">{optionBusy?'Loading values…':'Select…'}</option>}{options.map(option=><option key={optionKey(option.value)} value={optionKey(option.value)}>{option.label}</option>)}</select>:parameter.dataType==='boolean'||parameter.type==='boolean'?<select value={String(value??'')} onChange={event=>setParameter(parameter,event.target.value===''?'':event.target.value==='true')}><option value="">Select…</option><option value="true">True</option><option value="false">False</option></select>:<input type={parameter.dataType==='date'||parameter.type==='date'?'date':parameter.dataType==='integer'||parameter.dataType==='decimal'||parameter.type==='number'?'number':'text'} value={String(value??'')} onChange={event=>setParameter(parameter,event.target.value)}/>}</label>})}</div><div className="paginatedParameterActions"><button className="paginatedRefreshValues" title="Refresh parameter values" onClick={()=>void loadAvailableValues()} disabled={optionBusy}><RefreshCw size={15}/></button><button className="paginatedRunButton" onClick={()=>void run()} disabled={running||missingRequired}>{running?<LoaderCircle className="spin" size={15}/>:<Play size={15}/>} {running?'Running…':'Run report'}</button></div></section>
    {error&&<div className="paginatedServiceError">{error}</div>}{complete&&<div className="paginatedServiceSuccess"><CheckCircle2 size={15}/>PDF generated successfully.</div>}{hasRun&&<div className="paginatedRunSummary"><CheckCircle2 size={14}/>{rows.length} row{rows.length===1?'':'s'} loaded using the selected parameter values.</div>}
    <section className="paginatedServicePreview"><ReportPaper report={active} parameters={parameters} available={available} rows={rows}/></section>
  </main></div>;
}
