import { useEffect, useState } from 'react';
import { api } from '../api';

type Job={id:string;source_type:string;interval_label:string;status:string;next_run?:string;last_run?:string;error_message?:string};
type Run={id:string;status:string;created_at?:string;trigger_type?:string;rows_processed?:number;duration_ms?:number;error_message?:string};

export default function RefreshCenterDialog({reportId,reportName,onClose}:{reportId:string;reportName:string;sourceType?:string;onClose:()=>void;supabaseSession?:any}){
  const[jobs,setJobs]=useState<Job[]>([]),[runs,setRuns]=useState<Run[]>([]),[preflight,setPreflight]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{setBusy(true);setError('');try{const results=await Promise.allSettled([api<Job[]>(`/scheduler/jobs?report_id=${encodeURIComponent(reportId)}`),api<Run[]>(`/scheduler/runs?report_id=${encodeURIComponent(reportId)}`),api<any>(`/scheduler/preflight?report_id=${encodeURIComponent(reportId)}`)]);setJobs(results[0].status==='fulfilled'?results[0].value:[]);setRuns(results[1].status==='fulfilled'?results[1].value:[]);setPreflight(results[2].status==='fulfilled'?results[2].value:null);const failures=results.filter(x=>x.status==='rejected') as PromiseRejectedResult[];if(failures.length)setError(failures.map(x=>x.reason?.message||String(x.reason)).join(' '))}finally{setBusy(false)}};
  useEffect(()=>{void load()},[reportId]);
  const mutate=async(path:string,method:string,body?:any)=>{setBusy(true);setError('');try{await api(path,{method,body:body?JSON.stringify(body):undefined});await load()}catch(e:any){setError(e.message||String(e));setBusy(false)}};
  return <div style={backdrop} onMouseDown={onClose}><section style={dialog} onMouseDown={e=>e.stopPropagation()}><header style={header}><div style={{flex:1}}><b style={{fontSize:17}}>Refresh status</b><small style={{display:'block',color:'#64748b',marginTop:3}}>{reportName}</small></div><button onClick={onClose} style={close}>×</button></header><main style={{padding:22,overflow:'auto'}}>{error&&<Notice error>{error}</Notice>}<Notice><b>Connection setup has moved to the semantic model.</b><span> Open the connected semantic model → Settings to configure each source, select the Desktop Data Bridge for localhost/private data, and manage the refresh schedule. Gateway clusters, table mapping and snapshot-version controls are no longer shown here.</span></Notice><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:9,margin:'16px 0'}}>{(preflight?.checks||[]).map((item:any)=><div key={item.id} style={{padding:12,border:`1px solid ${item.ok?'#bbf7d0':'#fde68a'}`,background:item.ok?'#f0fdf4':'#fffbeb',borderRadius:7}}><b style={{display:'block',fontSize:12,color:item.ok?'#166534':'#92400e'}}>{item.ok?'✓ Ready':'Setup needed'}</b><span style={{fontSize:11,color:'#475569'}}>{item.message}</span></div>)}</div><div style={titleRow}><h3>Schedules</h3><button style={secondary} disabled={busy} onClick={()=>void load()}>{busy?'Refreshing…':'Refresh status'}</button></div>{jobs.length?jobs.map(job=><div key={job.id} style={row}><div><b>{job.interval_label||job.source_type}</b><small>Status: {job.status} · Next: {when(job.next_run)} · Last: {when(job.last_run)}</small>{job.error_message&&<small style={{color:'#b91c1c'}}>{job.error_message}</small>}</div><div style={{display:'flex',gap:6}}><button style={primary} disabled={busy} onClick={()=>void mutate(`/scheduler/jobs/${job.id}/run-now`,'POST')}>Run now</button><button style={secondary} disabled={busy} onClick={()=>void mutate(`/scheduler/jobs/${job.id}/status`,'PATCH',{status:job.status==='paused'?'active':'paused'})}>{job.status==='paused'?'Resume':'Pause'}</button></div></div>):<Empty text="No refresh schedule is configured."/>}<h3 style={{fontSize:14,margin:'22px 0 8px'}}>Refresh history</h3>{runs.length?runs.map(run=><div key={run.id} style={historyRow}><b style={{color:run.status==='succeeded'?'#15803d':'#b91c1c'}}>{run.status}</b><span>{when(run.created_at)} · {run.trigger_type||'manual'}</span><span>{run.duration_ms?`${(run.duration_ms/1000).toFixed(1)}s`:''}</span>{run.error_message&&<small style={{gridColumn:'2/-1',color:'#b91c1c'}}>{run.error_message}</small>}</div>):<Empty text="No refresh runs are available."/>}</main><footer style={footer}><button style={primary} onClick={onClose}>Close</button></footer></section></div>;
}

const when=(value?:string)=>value?new Date(value).toLocaleString():'—';
function Notice({children,error=false}:{children:any;error?:boolean}){return <div style={{padding:12,border:`1px solid ${error?'#fecaca':'#bfdbfe'}`,background:error?'#fef2f2':'#eff6ff',color:error?'#991b1b':'#1e3a8a',borderRadius:7,fontSize:12,lineHeight:1.55}}>{children}</div>}
function Empty({text}:{text:string}){return <div style={{padding:18,textAlign:'center',border:'1px dashed #cbd5e1',borderRadius:7,color:'#64748b',fontSize:12}}>{text}</div>}
const backdrop:React.CSSProperties={position:'fixed',inset:0,zIndex:1300,background:'rgba(15,23,42,.42)',display:'grid',placeItems:'center',padding:16};
const dialog:React.CSSProperties={width:'min(850px,97vw)',height:'min(700px,92vh)',background:'#fff',borderRadius:10,boxShadow:'0 24px 65px rgba(0,0,0,.28)',display:'flex',flexDirection:'column',overflow:'hidden'};
const header:React.CSSProperties={padding:'15px 20px',borderBottom:'1px solid #e5e7eb',display:'flex',alignItems:'center'};
const close:React.CSSProperties={border:0,background:'transparent',fontSize:23,cursor:'pointer'};
const titleRow:React.CSSProperties={display:'flex',alignItems:'center',justifyContent:'space-between',margin:'19px 0 9px'};
const row:React.CSSProperties={display:'flex',alignItems:'center',gap:12,justifyContent:'space-between',padding:13,border:'1px solid #e5e7eb',borderRadius:7,marginBottom:8,fontSize:12};
const historyRow:React.CSSProperties={display:'grid',gridTemplateColumns:'100px 1fr auto',gap:9,padding:'10px 12px',borderBottom:'1px solid #eee',fontSize:12};
const secondary:React.CSSProperties={border:'1px solid #cbd5e1',borderRadius:6,padding:'7px 11px',background:'#fff',fontWeight:700,cursor:'pointer'};
const primary:React.CSSProperties={...secondary,background:'#6d28d9',borderColor:'#6d28d9',color:'#fff'};
const footer:React.CSSProperties={padding:'10px 18px',borderTop:'1px solid #e5e7eb',display:'flex',justifyContent:'flex-end'};
