import { useEffect, useMemo, useState } from "react";
import { api } from "../api";

type Props={reportId:string;reportName:string;sourceType?:string;onClose:()=>void;supabaseSession:any};
type Source="postgresql"|"sqlserver"|"mysql"|"mariadb"|"google_sheets";
type Location="cloud"|"service_network"|"gateway";
type Mapping={table:string;query?:string;url?:string;sheet?:string};
type SourceInfo={id:Source;label:string;port:string;connectionExample:string;cloudSteps:string[];networkSteps:string[]};
const SOURCES:SourceInfo[]=[
 {id:"postgresql",label:"PostgreSQL",port:"5432",connectionExample:"postgresql://report_reader:password@db.example.com:5432/sales",cloudSteps:["Create a read-only PostgreSQL login for reporting.","Allow inbound PostgreSQL traffic from the VTAB Services backend network or static outbound IP.","Require SSL, then enter the host, database, port and login below.","Test the connection, select source tables, map report tables and activate the schedule."],networkSteps:["Run the VTAB Services backend on a machine that can reach PostgreSQL.","Confirm PostgreSQL accepts that machine's IP and port 5432 is reachable.","Use a read-only login and the server's private DNS name or IP.","Test, select tables and activate the refresh schedule."]},
 {id:"sqlserver",label:"SQL Server / Azure SQL",port:"1433",connectionExample:"DRIVER={ODBC Driver 18 for SQL Server};SERVER=tcp:server,1433;DATABASE=Sales;UID=reader;PWD=...;Encrypt=yes",cloudSteps:["Create a read-only SQL login or Azure SQL account.","Allow the VTAB Services backend address through the Azure SQL/server firewall.","Install Microsoft ODBC Driver 18 on the Services host and require encryption.","Enter server and database, test, select tables, map them and schedule refresh."],networkSteps:["Install Microsoft ODBC Driver 18 on the VTAB Services backend machine.","Ensure the machine can resolve the SQL Server instance and reach TCP 1433.","Enable SQL authentication with a read-only login (or provide a complete supported ODBC string).","Test, select tables and activate the schedule."]},
 {id:"mysql",label:"MySQL",port:"3306",connectionExample:"mysql://report_reader:password@db.example.com:3306/sales",cloudSteps:["Create a read-only MySQL user restricted to the reporting database.","Allow TCP 3306 from the VTAB Services backend address.","Enable TLS on the database and select Require SSL below.","Test, select source tables, map them and schedule refresh."],networkSteps:["Run VTAB Services where the private MySQL host is reachable.","Allow the Services machine through the MySQL host firewall.","Grant a read-only user SELECT access to the required schema.","Test, select tables and activate the schedule."]},
 {id:"mariadb",label:"MariaDB",port:"3306",connectionExample:"mariadb://report_reader:password@db.example.com:3306/sales",cloudSteps:["Create a read-only MariaDB user.","Allow TCP 3306 from the VTAB Services backend.","Enable TLS and use the public/private cloud hostname supplied by your provider.","Test, select tables, map them and activate refresh."],networkSteps:["Place the Services backend on a machine or network that can reach MariaDB.","Allow that host through the database firewall.","Use a user with SELECT-only access.","Test, select tables and activate the schedule."]},
 {id:"google_sheets",label:"Google Sheets",port:"",connectionExample:"https://docs.google.com/spreadsheets/d/.../edit",cloudSteps:["Open the Sheet's Share dialog.","For this connector, choose Anyone with the link can view (do not grant edit access).","Paste the complete Google Sheets URL below.","Test the real CSV download, map it to a report table and schedule refresh."],networkSteps:["Google Sheets is a cloud source, so select Cloud-hosted source.","The Services backend must have outbound HTTPS access.","Share the Sheet as view-only using a link.","Test and activate the schedule."]},
];
const SCHEDULES=[{label:"Hourly",cron:"0 * * * *"},{label:"Daily at 09:00",cron:"0 9 * * *"},{label:"Weekdays at 09:00",cron:"0 9 * * 1-5"},{label:"Monday at 09:00",cron:"0 9 * * 1"}];
const control:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #cbd5e1",borderRadius:6,padding:"9px 10px",fontSize:13,background:"#fff",color:"#111827"};
const btn=(primary=false):React.CSSProperties=>({border:`1px solid ${primary?"#6d28d9":"#cbd5e1"}`,background:primary?"#6d28d9":"#fff",color:primary?"#fff":"#374151",borderRadius:6,padding:"8px 13px",fontWeight:700,cursor:"pointer"});
const showTime=(value?:string)=>value?new Date(value).toLocaleString():"—";
const isLoopbackHost=(value?:string)=>{const host=String(value||"").trim().toLowerCase().replace(/^\[|\]$/g,"");return host==="localhost"||host==="127.0.0.1"||host==="::1"||host.startsWith("127.")};

export default function RefreshCenterDialog({reportId,reportName,sourceType,onClose}:Props){
 const normalized=(sourceType==="postgres"?"postgresql":sourceType) as Source;
 const [tab,setTab]=useState<"overview"|"setup"|"guide">("overview"),[step,setStep]=useState(1);
 const [jobs,setJobs]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[reportTables,setReportTables]=useState<any[]>([]),[sourceTables,setSourceTables]=useState<any[]>([]);
 const [preflight,setPreflight]=useState<any>(null),[loadIssues,setLoadIssues]=useState<string[]>([]);
 const [source,setSource]=useState<Source>(SOURCES.some(x=>x.id===normalized)?normalized:"postgresql"),[location,setLocation]=useState<Location>("cloud");
 const [credentials,setCredentials]=useState<any>({}),[mappings,setMappings]=useState<Mapping[]>([]),[schedule,setSchedule]=useState(SCHEDULES[1]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const timezone=useMemo(()=>Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",[]),sourceInfo=SOURCES.find(x=>x.id===source)!;
 const load=async()=>{setLoadIssues([]);const results=await Promise.allSettled([api<any>("/scheduler/preflight"),api<any[]>(`/scheduler/jobs?report_id=${encodeURIComponent(reportId)}`),api<any[]>(`/scheduler/history?report_id=${encodeURIComponent(reportId)}`),api<any>(`/scheduler/reports/${encodeURIComponent(reportId)}/schema`)]);const issues:string[]=[];if(results[0].status==="fulfilled")setPreflight(results[0].value);else issues.push(`Service setup: ${results[0].reason?.message||results[0].reason}`);if(results[1].status==="fulfilled")setJobs(results[1].value||[]);else issues.push(`Schedules: ${results[1].reason?.message||results[1].reason}`);if(results[2].status==="fulfilled")setRuns(results[2].value||[]);else issues.push(`History: ${results[2].reason?.message||results[2].reason}`);if(results[3].status==="fulfilled"){const tables=results[3].value.tables||[];setReportTables(tables);setMappings(old=>old.length?old:tables.map((t:any)=>({table:t.name,query:""})))}else issues.push(`Report model: ${results[3].reason?.message||results[3].reason}`);setLoadIssues(issues)};
 useEffect(()=>{load()},[reportId]);
 useEffect(()=>{setCredentials(source==="google_sheets"?{}:{port:sourceInfo.port,sslmode:"require"});setSourceTables([]);setMappings(reportTables.map(t=>({table:t.name,query:""})));setStep(1);setError("");setSuccess("")},[source]);
 const field=(label:string,key:string,type="text",placeholder="")=><label style={{fontSize:12,fontWeight:700,color:"#4b5563"}}>{label}<input style={{...control,marginTop:5}} type={type} placeholder={placeholder} value={credentials[key]||""} onChange={e=>setCredentials({...credentials,[key]:e.target.value})}/></label>;
 const chooseLocation=(next:Location)=>{setLocation(next);if(source!=="google_sheets"&&!String(credentials.connectionString||"").trim()){setCredentials((current:any)=>({...current,sslmode:next==="cloud"?"require":source==="postgresql"?"prefer":"disable"}))}};
 const testAndDiscover=async()=>{setBusy(true);setError("");setSuccess("");try{const localPostgres=source==="postgresql"&&!String(credentials.connectionString||"").trim()&&isLoopbackHost(credentials.host);const effectiveCredentials=localPostgres&&credentials.sslmode==="require"?{...credentials,sslmode:"prefer"}:credentials;if(effectiveCredentials!==credentials)setCredentials(effectiveCredentials);const result=await api<any>("/scheduler/jobs/_new/test-connection",{method:"POST",body:JSON.stringify({source_type:source,credentials:effectiveCredentials})});if(!result.ok)throw new Error(result.message);const discovered=await api<any[]>("/scheduler/discover-tables",{method:"POST",body:JSON.stringify({source_type:source,credentials:effectiveCredentials})});setSourceTables(discovered||[]);if(source==="google_sheets"){setMappings(reportTables.map(t=>{const exact=(discovered||[]).find((s:any)=>String(s.name||"").toLowerCase()===String(t.name||"").toLowerCase());return exact?{table:t.name,url:exact.url||credentials.sheet_url,sheet:exact.sheet||exact.name}:{table:t.name,query:""}}))}setSuccess(`${result.message} ${discovered?.length||0} source item${discovered?.length===1?"":"s"} available.`);setStep(3)}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}};
 const selectMapping=(index:number,value:string)=>{const selected=sourceTables.find(t=>t.qualifiedName===value);setMappings(mappings.map((m,i)=>i===index?source==="google_sheets"?{table:m.table,url:selected?.url||credentials.sheet_url,sheet:selected?.sheet||selected?.name||""}:{table:m.table,query:selected?.query||""}:m))};
 const save=async()=>{if(!preflight?.ok){setError("Complete the Services readiness checklist before saving credentials or a schedule.");return}if(!mappings.length||mappings.some(m=>!((m.query||m.url||"").trim()))){setError("Map every report table to a source table first.");return}setBusy(true);setError("");try{await api("/scheduler/jobs",{method:"POST",body:JSON.stringify({report_id:reportId,source_type:source,cron_expr:schedule.cron,interval_label:schedule.label,timezone,credentials,source_config:{location,mappings},notify_on_failure:true})});setSuccess("Refresh schedule activated successfully.");setCredentials({});setTab("overview");await load()}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}};
 const mutate=async(path:string,method:string,body?:any)=>{setBusy(true);setError("");try{await api(path,{method,body:body?JSON.stringify(body):undefined});await load()}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}};
 const readinessOk=preflight?.ok===true;
 return <div style={{position:"fixed",inset:0,zIndex:1300,background:"rgba(15,23,42,.42)",display:"grid",placeItems:"center",padding:16}} onMouseDown={onClose}><div style={{width:"min(980px,97vw)",height:"min(760px,94vh)",background:"#fff",borderRadius:10,boxShadow:"0 24px 65px rgba(0,0,0,.28)",display:"flex",flexDirection:"column",overflow:"hidden"}} onMouseDown={e=>e.stopPropagation()}>
  <header style={{padding:"16px 20px",borderBottom:"1px solid #e5e7eb",display:"flex",alignItems:"center"}}><div style={{flex:1}}><b style={{fontSize:17}}>Refresh settings</b><div style={{fontSize:12,color:"#6b7280",marginTop:2}}>{reportName}</div></div><button style={{border:0,background:"none",fontSize:22,cursor:"pointer"}} onClick={onClose}>×</button></header>
  <div style={{display:"flex",minHeight:0,flex:1}}><nav style={{width:210,borderRight:"1px solid #e5e7eb",padding:10}}>{[["overview","Refresh status"],["setup","Configure connection"],["guide","Deployment guide"]].map(x=><button key={x[0]} onClick={()=>setTab(x[0] as any)} style={{width:"100%",border:0,borderLeft:tab===x[0]?"3px solid #7c3aed":"3px solid transparent",background:tab===x[0]?"#f5f3ff":"transparent",padding:"10px 12px",textAlign:"left",fontWeight:tab===x[0]?700:500,color:tab===x[0]?"#5b21b6":"#374151",cursor:"pointer"}}>{x[1]}</button>)}</nav>
  <main style={{flex:1,padding:24,overflow:"auto",background:"#fafafa"}}>
   {loadIssues.length>0&&<Notice color="red" title="Some refresh services could not load">{loadIssues.map(x=><div key={x}>{x}</div>)}</Notice>}{error&&<Notice color="red" title="Action required">{error}</Notice>}{success&&<Notice color="green" title="Success">{success}</Notice>}
   {tab==="overview"&&<><h2 style={{margin:"0 0 5px",fontSize:20}}>Refresh status</h2><p style={{fontSize:13,color:"#6b7280",marginTop:0}}>Service readiness, active schedules and recent runs.</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,margin:"18px 0"}}>{(preflight?.checks||[]).map((c:any)=><div key={c.id} style={{padding:13,border:`1px solid ${c.ok?"#bbf7d0":"#fecaca"}`,background:c.ok?"#f0fdf4":"#fef2f2",borderRadius:7}}><b style={{display:"block",fontSize:12,color:c.ok?"#166534":"#991b1b"}}>{c.ok?"✓ Ready":"! Setup needed"}</b><span style={{fontSize:11,color:"#4b5563",lineHeight:1.45}}>{c.message}</span></div>)}</div>{!preflight&&<p style={{fontSize:13,color:"#b91c1c"}}>The backend readiness endpoint could not be reached. Confirm VITE_API_URL and restart both services.</p>}
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",margin:"22px 0 10px"}}><h3 style={{margin:0,fontSize:15}}>Schedules</h3><button style={btn(true)} onClick={()=>setTab("setup")}>＋ New schedule</button></div>{jobs.map(j=><div key={j.id} style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:7,padding:14,marginBottom:8,display:"grid",gridTemplateColumns:"1fr auto",gap:12}}><div><b style={{fontSize:13}}>{SOURCES.find(x=>x.id===j.source_type)?.label||j.source_type} · {j.interval_label}</b><div style={{fontSize:12,color:"#6b7280",marginTop:5}}>Status: {j.status} · Next: {showTime(j.next_run)} · Last: {showTime(j.last_run)}</div>{j.error_message&&<div style={{fontSize:12,color:"#b91c1c",marginTop:5}}>{j.error_message}</div>}</div><div style={{display:"flex",gap:6}}><button style={btn(true)} onClick={()=>mutate(`/scheduler/jobs/${j.id}/run-now`,"POST")}>Run now</button><button style={btn()} onClick={()=>mutate(`/scheduler/jobs/${j.id}/status`,"PATCH",{status:j.status==="paused"?"active":"paused"})}>{j.status==="paused"?"Resume":"Pause"}</button><button style={{...btn(),color:"#b91c1c"}} onClick={()=>confirm("Delete this refresh schedule?")&&mutate(`/scheduler/jobs/${j.id}`,"DELETE")}>Delete</button></div></div>)}{!jobs.length&&<div style={{padding:24,textAlign:"center",background:"#fff",border:"1px dashed #cbd5e1",color:"#6b7280",fontSize:13}}>No refresh schedule is configured.</div>}
   <h3 style={{fontSize:15,margin:"24px 0 9px"}}>Refresh history</h3>{runs.map(r=><div key={r.id} style={{display:"grid",gridTemplateColumns:"100px 1fr auto",gap:10,padding:"10px 12px",background:"#fff",borderBottom:"1px solid #eee",fontSize:12}}><b style={{color:r.status==="succeeded"?"#15803d":"#b91c1c"}}>{r.status}</b><span>{showTime(r.created_at)} · {r.trigger_type} · {Number(r.rows_processed||0).toLocaleString()} rows</span><span>{r.duration_ms?`${(r.duration_ms/1000).toFixed(1)}s`:""}</span>{r.error_message&&<span style={{gridColumn:"2/-1",color:"#b91c1c"}}>{r.error_message}</span>}</div>)}</>}
   {tab==="setup"&&<><h2 style={{margin:"0 0 5px",fontSize:20}}>Configure connection</h2><p style={{fontSize:13,color:"#6b7280",marginTop:0}}>Follow each step. VTAB validates the real source before credentials can be saved.</p><Steps current={step}/>
    <Card title="Step 1 — Choose where the source runs"><label style={{fontSize:12,fontWeight:700}}>Data source<select style={{...control,marginTop:5}} value={source} onChange={e=>setSource(e.target.value as Source)}>{SOURCES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:13}}>{([['cloud','Cloud-hosted','Reachable from Services over the internet'],['service_network','Same network','Reachable directly from the backend machine'],['gateway','Private via Gateway','Outbound gateway tunnel (not installed)']] as any[]).map(x=><button key={x[0]} onClick={()=>setLocation(x[0])} style={{...btn(location===x[0]),textAlign:"left",padding:11}}><b style={{display:"block",fontSize:12}}>{x[1]}</b><small style={{fontWeight:400}}>{x[2]}</small></button>)}</div>{location==="gateway"&&<Notice color="amber" title="VTAB Gateway is required">A public connection string cannot securely reach a database on a laptop or private office network. Install/deploy the gateway package when available, or run the Services backend inside that network. This build will not pretend the gateway connection is active.</Notice>}</Card>
    <Card title="Step 2 — Prepare and enter the connection"><ol style={{paddingLeft:20,fontSize:12,color:"#4b5563",lineHeight:1.6}}>{(location==="cloud"?sourceInfo.cloudSteps:sourceInfo.networkSteps).map(x=><li key={x}>{x}</li>)}</ol>{source==="google_sheets"?field("Shared Google Sheets URL","sheet_url","url",sourceInfo.connectionExample):<><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:10}}>{field("Host / server","host","text","db.example.com")}{field("Port","port","number")}{field("Database","database")}{field("Username (read-only)","username")}{field("Password","password","password")}</div><label style={{display:"block",fontSize:12,fontWeight:700,marginTop:10}}>Connection string (optional; overrides fields)<textarea style={{...control,marginTop:5,minHeight:55,fontFamily:"monospace"}} placeholder={sourceInfo.connectionExample} value={credentials.connectionString||""} onChange={e=>setCredentials({...credentials,connectionString:e.target.value})}/></label><label style={{display:"flex",gap:8,alignItems:"center",fontSize:12,marginTop:10}}><input type="checkbox" checked={credentials.sslmode==="require"} onChange={e=>setCredentials({...credentials,sslmode:e.target.checked?"require":source==="postgresql"?"prefer":"disable"})}/>Require an encrypted database connection</label>{source==="postgresql"&&isLoopbackHost(credentials.host)&&<Notice color="amber" title="Local PostgreSQL detected">127.0.0.1 / localhost is on the same machine as the Services backend. VTAB will use PostgreSQL SSL mode <b>prefer</b> for this local connection, so it can fall back to non-SSL when your local PostgreSQL server does not have TLS enabled. Cloud or remote PostgreSQL hosts still keep SSL required unless you explicitly change it.</Notice>}</>}<div style={{marginTop:14}}><button disabled={busy||location==="gateway"} style={btn(true)} onClick={testAndDiscover}>{busy?"Connecting…":"Test connection & load tables"}</button></div></Card>
    {step>=3&&<Card title="Step 3 — Map report tables">{!reportTables.length?<Notice color="amber" title="No report tables found">Republish the report after loading data into its semantic model.</Notice>:reportTables.map((t,index)=><label key={t.name} style={{display:"grid",gridTemplateColumns:"1fr 30px 1.4fr",gap:10,alignItems:"center",fontSize:12,fontWeight:700,marginBottom:10}}><span>{t.name}</span><span>→</span><select style={control} value={source==="google_sheets"?(sourceTables.find(s=>s.sheet===mappings[index]?.sheet||s.name===mappings[index]?.sheet)?.qualifiedName||""):(sourceTables.find(s=>s.query===mappings[index]?.query)?.qualifiedName||"")} onChange={e=>selectMapping(index,e.target.value)}><option value="">Select source table…</option>{sourceTables.map(s=><option key={s.qualifiedName} value={s.qualifiedName}>{s.qualifiedName}</option>)}</select></label>)}</Card>}
    {step>=3&&<Card title="Step 4 — Schedule and activate"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label style={{fontSize:12,fontWeight:700}}>Frequency<select style={{...control,marginTop:5}} value={schedule.cron} onChange={e=>setSchedule(SCHEDULES.find(x=>x.cron===e.target.value)||SCHEDULES[1])}>{SCHEDULES.map(x=><option key={x.cron} value={x.cron}>{x.label}</option>)}</select></label><label style={{fontSize:12,fontWeight:700}}>Timezone<input readOnly style={{...control,marginTop:5,background:"#f3f4f6"}} value={timezone}/></label></div><div style={{marginTop:15,display:"flex",justifyContent:"flex-end"}}><button disabled={busy||!readinessOk||location==="gateway"} style={btn(true)} onClick={save}>{busy?"Saving…":"Save credentials & activate"}</button></div>{!readinessOk&&<p style={{fontSize:12,color:"#b91c1c"}}>Activation is disabled until all readiness checks on Refresh status are green.</p>}</Card>}</>}
   {tab==="guide"&&<><h2 style={{margin:"0 0 5px",fontSize:20}}>Deployment guide</h2><p style={{fontSize:13,color:"#6b7280"}}>Select any connector to see its complete cloud and private-network process.</p><select style={{...control,maxWidth:340}} value={source} onChange={e=>setSource(e.target.value as Source)}>{SOURCES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><Guide title="Cloud-hosted source" steps={sourceInfo.cloudSteps}/><Guide title="Database on the Services network" steps={sourceInfo.networkSteps}/><Guide title="Database on a laptop or private office network" steps={["Do not expose the database directly to the internet or paste localhost into the cloud service.","Install an outbound VTAB Gateway agent on a machine that can reach the database.","Register that gateway with the VTAB Services workspace, then create a connection mapped to it.","Map the semantic model and schedule refresh. Until the gateway package is installed, run the Services backend inside the database network instead."]}/></>}
  </main></div>
 </div></div>
}
function Steps({current}:{current:number}){return <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:5,margin:"18px 0"}}>{["Location","Credentials","Tables","Schedule"].map((x,i)=><div key={x} style={{borderTop:`3px solid ${current>=i+1?"#7c3aed":"#d1d5db"}`,paddingTop:6,fontSize:11,color:current>=i+1?"#5b21b6":"#6b7280",fontWeight:700}}>{i+1}. {x}</div>)}</div>}
function Card({title,children}:{title:string;children:any}){return <section style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:8,padding:17,marginBottom:12}}><h3 style={{fontSize:14,margin:"0 0 13px"}}>{title}</h3>{children}</section>}
function Guide({title,steps}:{title:string;steps:string[]}){return <Card title={title}><ol style={{paddingLeft:20,fontSize:13,color:"#4b5563",lineHeight:1.75}}>{steps.map(x=><li key={x}>{x}</li>)}</ol></Card>}
function Notice({color,title,children}:{color:"red"|"green"|"amber";title:string;children:any}){const p=color==="red"?["#fef2f2","#fecaca","#991b1b"]:color==="green"?["#f0fdf4","#bbf7d0","#166534"]:["#fffbeb","#fde68a","#92400e"];return <div style={{background:p[0],border:`1px solid ${p[1]}`,color:p[2],borderRadius:7,padding:11,margin:"10px 0",fontSize:12,lineHeight:1.5}}><b style={{display:"block",marginBottom:3}}>{title}</b>{children}</div>}
