import {useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Play,Filter,Trash2,Rows3,Link2,ArrowDownAZ,Wand2,Group,CopyPlus,Undo2,Redo2,Scissors,Combine,CalendarDays,Sparkles,ChevronDown,ChevronUp,Eye,EyeOff,GripVertical,Type,Search,PanelTop,Columns3,Check,Info,MoveUp,MoveDown,Settings2,PanelLeftClose,PanelLeftOpen,PanelRightClose,PanelRightOpen,Braces,Pencil,Save,CalendarPlus,TextCursorInput,XCircle,MoreVertical,Hash,ToggleLeft} from 'lucide-react';
import {api} from '../api';
import {useStudio} from '../store';

type Step=Record<string,any>;
type ModalType=null|'query'|'columns'|'split'|'merge'|'replace'|'date'|'text'|'calendar'|'conditional'|'calculated'|'join'|'append'|'group'|'filter'|'bulktypes'|'unpivot';
const DATA_TYPES=[['ABC','text'],['123','integer'],['1.2','decimal'],['$','currency'],['📅','date'],['◷','datetime'],['✓','boolean']];
const DELIMS=[['Comma',','],['Pipe','|'],['Semicolon',';'],['Space',' '],['Tab','\t']];

function Modal({title,children,onClose,wide=false}:{title:string,children:any,onClose:()=>void,wide?:boolean}){
 return <div className="modalShade" onMouseDown={onClose}><div className={'modalCard '+(wide?'wide':'')} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><h3>{title}</h3><button onClick={onClose}>×</button></div>{children}</div></div>
}
function FieldSelect({label,value,onChange,cols,allowBlank=false}:{label:string,value:string,onChange:(v:string)=>void,cols:string[],allowBlank?:boolean}){
 return <label className="formField"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{allowBlank&&<option value="">—</option>}{cols.map(c=><option key={c}>{c}</option>)}</select></label>
}
function MiniTable({rows,limit=10}:{rows:any[],limit?:number}){const cols=rows[0]?Object.keys(rows[0]):[];return <div className="miniTable"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,limit).map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></div>}
function currentToken(text:string,cursor:number){const left=text.slice(0,cursor);const m=left.match(/([A-Za-z0-9_ ]{1,50})$/);return (m?.[1]||'').trim().split(/\s+/).pop()||''}
function compactQueryName(name:string,source?:string){const raw=String(name||source||'Table').replace(/^(Imported_|ETL_)+/i,'').replace(/\.(csv|tsv|txt|xlsx?|jsonl?|parquet|xml)$/i,'').replace(/[_ ]+\d{3,}$/,'').trim();return (raw||'Table').slice(0,36)}
function compactSourceName(source:string){return String(source||'').replace(/^(Imported_|ETL_)+/i,'').slice(0,40)}
function previewLimitFor(steps:Step[],fallback=200){const requested=steps.filter(s=>s.enabled!==false&&s.type==='top_n').map(s=>Number(s.value)||0).filter(Boolean);return requested.length?Math.max(1,Math.min(5000,fallback,...requested)):fallback}
function configuredColumnType(steps:Step[]|undefined,column:string){let dataType='',currency='USD';for(const step of steps||[]){if(step.enabled===false)continue;if(step.type==='change_type'&&step.field===column){dataType=step.dataType||'text';currency=step.currency||currency}if(step.type==='bulk_change_type'){const mapping=(step.mappings||[]).find((m:any)=>m.field===column);if(mapping){dataType=mapping.dataType||'text';currency=mapping.currency||currency}}}return{dataType,currency}}
function inferredColumnGroup(rows:any[],column:string){const values=rows.slice(0,100).map(row=>row[column]).filter(value=>value!==null&&value!==undefined&&value!=='');if(!values.length)return'text';if(values.every(value=>typeof value==='boolean'||value===0||value===1||/^(true|false|yes|no)$/i.test(String(value))))return'boolean';if(values.every(value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}(?:[T\s].*)?$/.test(value)&&!Number.isNaN(Date.parse(value))))return'date';if(values.every(value=>typeof value==='number'))return'number';return'text'}
function availableDataTypes(rows:any[],column:string,steps?:Step[]){const configured=configuredColumnType(steps,column).dataType;const group=configured?(['integer','decimal','currency','number','numeric','real'].includes(configured)?'number':['date','datetime'].includes(configured)?'date':configured==='boolean'?'boolean':'text'):inferredColumnGroup(rows,column);const allowed:Record<string,string[]>={number:['text','integer','decimal','currency'],date:['text','date','datetime'],boolean:['text','boolean'],text:['text']};return DATA_TYPES.filter(([,type])=>(allowed[group]||allowed.text).includes(type))}
function canConvertColumn(rows:any[],column:string,dataType:string){const values=rows.slice(0,200).map(row=>row[column]).filter(value=>value!==null&&value!==undefined&&value!=='');if(!values.length||dataType==='text')return true;const numeric=(value:any)=>Number.isFinite(Number(String(value).replace(/[$,\s]/g,'')));if(dataType==='decimal'||dataType==='currency')return values.every(numeric);if(dataType==='integer')return values.every(value=>numeric(value)&&Number.isInteger(Number(String(value).replace(/[$,\s]/g,''))));if(dataType==='date'||dataType==='datetime')return values.every(value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}(?:[T\s].*)?$/.test(value)&&!Number.isNaN(Date.parse(value)));if(dataType==='boolean')return values.every(value=>typeof value==='boolean'||value===0||value===1||/^(true|false|yes|no)$/i.test(String(value)));return true}
function powerQueryValue(value:any):string{if(value===null||value===undefined)return 'null';if(typeof value==='boolean')return value?'true':'false';if(typeof value==='number')return String(value);if(Array.isArray(value))return `{${value.map(powerQueryValue).join(', ')}}`;return JSON.stringify(String(value))}
function powerQueryStep(step:Step,previous:string){
 const field=(name='field')=>`[${String(step[name]||'Column').replaceAll(']',']]')}]`,quoted=(value:any)=>powerQueryValue(value),cols=(value:any)=>powerQueryValue(Array.isArray(value)?value:[]);
 switch(step.type){
  case 'source':return `VTAB.Source(${quoted(step.source||step.label?.replace(/^Source:\s*/,'')||'Current source')})`;
  case 'select_columns':return `Table.SelectColumns(${previous}, ${cols(step.columns)})`;
  case 'remove_columns':return `Table.RemoveColumns(${previous}, ${cols(step.columns)})`;
  case 'rename':return `Table.RenameColumns(${previous}, {{${quoted(step.field)}, ${quoted(step.newName)}}})`;
  case 'change_type':return `Table.TransformColumnTypes(${previous}, {{${quoted(step.field)}, type ${step.dataType||'any'}}})`;
  case 'bulk_change_type':return `Table.TransformColumnTypes(${previous}, {${(step.mappings||[]).map((m:any)=>`{${quoted(m.field)}, type ${m.dataType||'any'}}`).join(', ')}})`;
  case 'filter':{const op:Record<string,string>={eq:'=',neq:'<>',gt:'>',gte:'>=',lt:'<',lte:'<=',contains:'Text.Contains'};return step.operator==='contains'?`Table.SelectRows(${previous}, each Text.Contains(Text.From(${field()}), ${quoted(step.value)}))`:`Table.SelectRows(${previous}, each ${field()} ${op[step.operator]||step.operator||'='} ${quoted(step.value)})`;}
  case 'sort':return `Table.Sort(${previous}, {{${quoted(step.field)}, Order.${step.direction==='desc'?'Descending':'Ascending'}}})`;
  case 'replace':return `Table.ReplaceValue(${previous}, ${quoted(step.oldValue)}, ${quoted(step.newValue)}, Replacer.ReplaceValue, {${quoted(step.field)}})`;
  case 'top_n':return `Table.FirstN(${previous}, ${Number(step.value)||100})`;
  case 'distinct':return `Table.Distinct(${previous})`;
  case 'calculated_column':return `Table.AddColumn(${previous}, ${quoted(step.name||'Custom')}, each ${step.expression||'null'})`;
  case 'text_transform':return `VTAB.TextTransform(${previous}, ${quoted(step.field)}, ${quoted(step.operation)}, ${quoted(step.argument)}, ${quoted(step.outputName||step.field)})`;
  case 'date_part':return `Table.AddColumn(${previous}, ${quoted(step.name||`${step.field}_${step.part}`)}, each Date.${String(step.part||'year').replace(/^./,x=>x.toUpperCase())}(${field()}))`;
  case 'native_query':return `Value.NativeQuery(${previous}, ${quoted(step.sql||'')})`;
  case 'append':return `Table.Combine({${previous}, ${quoted(step.source||step.query||'Other query')}})`;
  default:{const args=Object.fromEntries(Object.entries(step).filter(([key])=>!['id','enabled','label','type'].includes(key)));return `VTAB.Transform(${previous}, ${quoted(step.type)}, ${quoted(JSON.stringify(args))})`;}
 }
}
function buildAdvancedScript(query:any){
 if(!query)return '';
 const steps=(query.steps||[]).filter((step:any)=>step.enabled!==false),used=new Map<string,number>();let previous='Source';const lines:string[]=[];
 steps.forEach((step:any,index:number)=>{let label=index===0?'Source':String(step.label||`Step ${index+1}`).replaceAll('"','""');const count=used.get(label)||0;used.set(label,count+1);if(count)label+=` ${count+1}`;const name=index===0?'Source':`#"${label}"`;lines.push(`    ${name} = ${powerQueryStep({...step,source:query.source},previous)}`);previous=name});
 const portable={version:1,source:query.source,steps:query.steps||[]};
 return `let\n${lines.join(',\n')}\nin\n    ${previous}\n\n/* VTAB_QUERY_V1\n${JSON.stringify(portable,null,2)}\n*/`;
}
function parseAdvancedScript(script:string){const match=script.match(/\/\*\s*VTAB_QUERY_V1\s*([\s\S]*?)\*\//);if(!match)throw new Error('The portable VTAB query definition is missing. Paste the complete script, including the VTAB_QUERY_V1 block.');const parsed=JSON.parse(match[1]);if(!parsed||typeof parsed.source!=='string'||!parsed.source.trim()||!Array.isArray(parsed.steps)||!parsed.steps.length)throw new Error('The portable query definition must contain a source and at least one transformation step.');return parsed}

export default function TransformWorkbench(){
 const{project,update,load,setView}=useStudio();
 const[active,setActive]=useState(project?.transform.queries[0]?.id||'');
 const[rows,setRows]=useState<any[]>([]);const[sql,setSql]=useState('');const[error,setError]=useState('');const[meta,setMeta]=useState<any[]>([]);const[folding,setFolding]=useState<any[]>([]);
 const[modal,setModal]=useState<ModalType>(null);const[selectedCol,setSelectedCol]=useState('');const[headerMenu,setHeaderMenu]=useState<string|null>(null);const[ctx,setCtx]=useState<{x:number,y:number,col:string}|null>(null);
 const[renameCol,setRenameCol]=useState<string|null>(null);const[renameValue,setRenameValue]=useState('');const[stepIndex,setStepIndex]=useState(-1);const[beforeRows,setBeforeRows]=useState<any[]>([]);const[afterRows,setAfterRows]=useState<any[]>([]);const[compare,setCompare]=useState(false);
 const[undoStack,setUndoStack]=useState<Step[][]>([]);const[redoStack,setRedoStack]=useState<Step[][]>([]);const[ai,setAi]=useState<any[]>([]);const[loading,setLoading]=useState(false);
 const[queriesPaneVisible,setQueriesPaneVisible]=useState(true);const[stepsPaneVisible,setStepsPaneVisible]=useState(true);
 const[querySearch,setQuerySearch]=useState('');const[queryMenu,setQueryMenu]=useState<string|null>(null);
 const[moreMenuOpen,setMoreMenuOpen]=useState(false);const[moreMenuPos,setMoreMenuPos]=useState({top:0,right:0});const moreMenuRef=useRef<HTMLButtonElement|null>(null);
 const[selectedCols,setSelectedCols]=useState<string[]>([]);
 const[stepEdit,setStepEdit]=useState<{id:string,index:number,step:Step}|null>(null);
 const[ribbonTab,setRibbonTab]=useState<'home'|'transform'|'add'|'combine'>('home');
 const[querySql,setQuerySql]=useState('');const[advancedScript,setAdvancedScript]=useState('');const[queryEditError,setQueryEditError]=useState('');const[querySaving,setQuerySaving]=useState(false);const[queryEditorTab,setQueryEditorTab]=useState<'steps'|'sql'>('steps');
 const previewSeqRef=useRef(0);
 const previewAbortRef=useRef<AbortController|null>(null);const previewCacheRef=useRef(new Map<string,any>());
 useEffect(()=>{const clear=()=>previewCacheRef.current.clear();window.addEventListener('vtab:clear-query-cache',clear);return()=>window.removeEventListener('vtab:clear-query-cache',clear)},[]);
 const queries=project?.transform.queries||[];
 const q=queries.find((x:any)=>x.id===active);const cols=useMemo(()=>rows[0]?Object.keys(rows[0]):[],[rows]);
 useEffect(()=>{if(!queries.length){if(active)setActive('');return}if(!active||!queries.some((x:any)=>x.id===active))setActive(queries[0].id)},[queries.map((x:any)=>x.id).join('|'),active]);
 useEffect(()=>setSelectedCols(s=>s.filter(c=>cols.includes(c))),[cols.join('|')]);
 useEffect(()=>{api<any[]>('/metadata').then(setMeta)},[]);
 const run=async(steps?:Step[], resetStep=true)=>{
   const state=useStudio.getState();const query=state.project?.transform.queries.find((x:any)=>x.id===active);if(!query){setRows([]);setSql('');setFolding([]);setError('');return}
   const snapshot=structuredClone(steps||query.steps||[]),limit=previewLimitFor(snapshot,Math.max(100,Math.min(5000,Number(state.project?.appPreferences?.previewRows)||500))),cacheEnabled=state.project?.appPreferences?.queryCache!==false;
   const cacheKey=JSON.stringify([query.source,snapshot,limit]);
   const requestId=++previewSeqRef.current;
   previewAbortRef.current?.abort();const controller=new AbortController();previewAbortRef.current=controller;
   if(resetStep)setStepIndex(-1);setCompare(false);setLoading(true);setError('');
   try{let r=cacheEnabled?previewCacheRef.current.get(cacheKey):undefined;if(!r){r=await api<any>('/transform/preview',{method:'POST',signal:controller.signal,body:JSON.stringify({source:query.source,steps:snapshot,limit})});if(cacheEnabled){previewCacheRef.current.set(cacheKey,r);const oldest=previewCacheRef.current.keys().next().value;if(previewCacheRef.current.size>20&&oldest)previewCacheRef.current.delete(oldest)}}if(requestId!==previewSeqRef.current)return;setRows(r.rows||[]);setSql(r.sql||'');setFolding(r.folding||[]);setError('')}catch(e:any){if(requestId===previewSeqRef.current&&!controller.signal.aborted)setError(e.message)}finally{if(requestId===previewSeqRef.current)setLoading(false)}
 };
 const queryRevision=q?JSON.stringify([q.id,q.source,q.steps]):'';
 useEffect(()=>{void run(q?.steps||[]);return()=>previewAbortRef.current?.abort()},[queryRevision,project?.appPreferences?.previewRows,project?.appPreferences?.queryCache]);
 useEffect(()=>{if(!compare||!q||stepIndex<0)return;const idx=stepIndex;Promise.all([
   api<any>('/transform/preview',{method:'POST',body:JSON.stringify({source:q.source,steps:q.steps.slice(0,idx),limit:20})}),
   api<any>('/transform/preview',{method:'POST',body:JSON.stringify({source:q.source,steps:q.steps.slice(0,idx+1),limit:20})})
 ]).then(([a,b])=>{setBeforeRows(a.rows);setAfterRows(b.rows)}).catch(()=>{})},[compare,stepIndex,q?.steps]);

 const mutateSteps=(fn:(steps:Step[])=>Step[])=>{if(!q)return;const old=structuredClone(q.steps);setUndoStack(s=>[...s.slice(-29),old]);setRedoStack([]);update(p=>{const x=p.transform.queries.find((z:any)=>z.id===active);x.steps=fn(structuredClone(x.steps));return p})};
 const add=(st:Step)=>mutateSteps(s=>[...s,{id:crypto.randomUUID(),enabled:true,...st}]);
 const undo=()=>{if(!q||!undoStack.length)return;const prev=undoStack[undoStack.length-1];setUndoStack(s=>s.slice(0,-1));setRedoStack(s=>[...s,structuredClone(q.steps)]);update(p=>{p.transform.queries.find((z:any)=>z.id===active).steps=structuredClone(prev);return p})};
 const redo=()=>{if(!q||!redoStack.length)return;const next=redoStack[redoStack.length-1];setRedoStack(s=>s.slice(0,-1));setUndoStack(s=>[...s,structuredClone(q.steps)]);update(p=>{p.transform.queries.find((z:any)=>z.id===active).steps=structuredClone(next);return p})};
 const open=(m:ModalType,col='')=>{
    if(m==='calculated'||m==='bulktypes')setStepEdit(null);
    if(m==='append')api<any[]>('/metadata').then(setMeta);
    setSelectedCol(col||selectedCol||cols[0]||'');
    setHeaderMenu(null);
    setCtx(null);
    setModal(m)
 };
 const replaceColumnRefs=(value:any,oldName:string,newName:string,key=''):any=>{if(typeof value==='string'){if(value===oldName)return newName;if(key==='expression')return value.replaceAll(`[${oldName}]`,`[${newName}]`);return value}if(Array.isArray(value))return value.map(v=>replaceColumnRefs(v,oldName,newName,key));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,replaceColumnRefs(v,oldName,newName,k)]));return value};
 const editStep=(step:Step,index:number)=>{setStepEdit({id:step.id,index,step:structuredClone(step)});setStepIndex(index);if(step.type==='calculated_column')setModal('calculated');else if(step.type==='bulk_change_type')setModal('bulktypes');};
 const saveStepEdit=(next:Step)=>{if(!stepEdit)return;mutateSteps(steps=>{const out=structuredClone(steps);const original=out[stepEdit.index];const oldName=String(original?.name||'');const newName=String(next.name||oldName);out[stepEdit.index]={...original,...next,id:original.id,enabled:original.enabled!==false};if(oldName&&newName&&oldName!==newName){for(let i=stepEdit.index+1;i<out.length;i++)out[i]=replaceColumnRefs(out[i],oldName,newName)}return out});setStepEdit(null);setModal(null)};
 const quickRename=(old:string,newName:string)=>{if(newName&&newName!==old)add({type:'rename',label:`Rename ${old} → ${newName}`,field:old,newName});setRenameCol(null)};
 const quickType=(field:string,dataType:string)=>{if(!canConvertColumn(rows,field,dataType)){alert(`${field} cannot be converted to ${dataType}. The current values are not compatible with this data type.`);return}add({type:'change_type',label:`Change ${field} to ${dataType}`,field,dataType,...(dataType==='currency'?{currency:'USD'}:{})})};
 const quickSort=(field:string,direction:'asc'|'desc')=>add({type:'sort',label:`Sort ${field} ${direction==='asc'?'ascending':'descending'}`,field,direction});
 const textOp=(field:string,operation:string)=>add({type:'text_transform',label:`${operation[0].toUpperCase()+operation.slice(1)} ${field}`,field,operation});
 const datePart=(field:string,part:string)=>add({type:'date_part',label:`Add ${part} from ${field}`,field,part,name:`${field}_${part}`});
 const removeCol=(field:string)=>add({type:'remove_columns',label:`Remove ${field}`,columns:[field]});
 const distinct=()=>add({type:'distinct',label:'Remove Duplicates'});
 const top=async()=>{const n=Number((await (window as any).vtabPrompt('Top number of rows','100'))||100);add({type:'top_n',label:`Top ${n} rows`,value:n})};
 const editCell=async(col:string,oldVal:any)=>{const nv=await (window as any).vtabPrompt(`Edit ${col}. This creates a Replace Value transformation step.`,String(oldVal??''));if(nv!==null&&String(oldVal??'')!==nv)add({type:'replace',label:`Replace value in ${col}`,field:col,oldValue:oldVal,newValue:nv,mode:'value'})};
 const removeStep=(id:string)=>mutateSteps(s=>s.filter((x:any)=>x.id!==id||x.type==='source'));
 const toggleStep=(id:string)=>mutateSteps(s=>s.map((x:any)=>x.id===id&&x.type!=='source'?{...x,enabled:x.enabled===false}:x));
 const moveStep=(idx:number,dir:number)=>mutateSteps(s=>{const n=[...s],to=idx+dir;if(idx<=0||to<=0||to>=n.length)return n;[n[idx],n[to]]=[n[to],n[idx]];return n});
 const renameStep=(id:string,label:string)=>mutateSteps(s=>s.map((x:any)=>x.id===id?{...x,label}:x));
 const apply=async()=>{const latest=useStudio.getState().project?.transform.queries.find((x:any)=>x.id===active);if(!latest)return;try{const snapshot=structuredClone(latest);const r=await api<any>('/transform/apply',{method:'POST',body:JSON.stringify({source:snapshot.source,steps:snapshot.steps,name:snapshot.name})});await load();alert(`Applied ${r.rows.toLocaleString()} rows as ${r.semanticName}. The processed table is now in this report's Model.`);setView('model')}catch(e:any){alert(e.message)}};
 const applyAll=async()=>{const queries=structuredClone(useStudio.getState().project?.transform.queries||[]);if(!queries.length)return;const failures:string[]=[];let applied=0,relationships=0;for(const item of queries){try{const r=await api<any>('/transform/apply',{method:'POST',body:JSON.stringify({source:item.source,steps:item.steps,name:item.name})});applied++;relationships+=(r.relationshipsAdded||[]).length}catch(e:any){failures.push(`${item.name}: ${e.message}`)}}await load();if(failures.length)alert(`Applied ${applied}/${queries.length} Transform tables.\n\nFailed:\n${failures.join('\n')}`);else alert(`All ${applied} Transform tables were materialized and registered in the Data Model.${relationships?` ${relationships} relationship${relationships===1?'':'s'} created automatically.`:''}`);setView('model')};
 const newQuery=async()=>{const source=(await (window as any).vtabPrompt('Source table',meta[0]?.name||''))?.trim();if(!source)return;const name=(await (window as any).vtabPrompt('Query name',source.replace('Imported_','')))?.trim()||source;const id='q-'+Date.now();update(p=>{p.transform.queries.push({id,name,source,steps:[{id:'src-'+id,type:'source',label:'Source: '+source,enabled:true}]});return p});setActive(id)};
 const removeQueryOnly=(item:any)=>{if(!confirm(`Remove query ${item.name} from Transform? The underlying source table will be kept.`))return;const next=project?.transform.queries.find((z:any)=>z.id!==item.id)?.id||'';update(p=>{p.transform.queries=p.transform.queries.filter((z:any)=>z.id!==item.id);return p});if(active===item.id)setActive(next);setQueryMenu(null)};
 const deleteSourceTable=async(item:any)=>{if(!confirm(`Delete source table ${item.source}?\n\nThis removes the physical managed table, dependent Transform queries, semantic-model table metadata, relationships and hierarchies that directly depend on it.`))return;try{await api<any>('/data/tables/'+encodeURIComponent(item.source),{method:'DELETE'});const next=project?.transform.queries.find((z:any)=>z.id!==item.id)?.id||'';setActive(next);setMeta(await api<any[]>('/metadata'));await load();setQueryMenu(null)}catch(e:any){alert(`Table could not be deleted. ${e.message}`)}};
 const duplicateQuery=async()=>{if(!q)return;const name=(await (window as any).vtabPrompt('Duplicate processed query as',q.name+' Copy'))?.trim();if(!name)return;const id='q-'+crypto.randomUUID();update(p=>{const original=p.transform.queries.find((z:any)=>z.id===active);if(!original)return p;const clone=structuredClone(original);clone.id=id;clone.name=name;clone.steps=clone.steps.map((s:any)=>({...s,id:crypto.randomUUID()}));p.transform.queries.push(clone);return p});setActive(id);setUndoStack([]);setRedoStack([])};
 const getAI=async()=>{const state=useStudio.getState(),latest=state.project?.transform.queries.find((x:any)=>x.id===active);if(!latest)return;if(state.project?.appPreferences?.copilotEnabled===false){alert('Copilot assistance is disabled in Application Settings.');return}const r=await api<any>('/transform/ai-suggestions',{method:'POST',body:JSON.stringify({source:latest.source,steps:latest.steps,limit:100})});setAi(r.suggestions||[])};
 const openQueryEditor=()=>{if(!q)return;const saved=q.steps.find((s:any)=>s.type==='native_query')?.sql;setQuerySql(saved||sql||`SELECT * FROM "${String(q.source).replaceAll('"','""')}"`);setAdvancedScript(buildAdvancedScript(q));setQueryEditError('');setQueryEditorTab('steps');setModal('query')};
 const saveAdvancedScript=async()=>{if(!q)return;setQuerySaving(true);setQueryEditError('');try{const parsed=parseAdvancedScript(advancedScript);const steps=parsed.steps.map((step:any,index:number)=>({...step,id:crypto.randomUUID(),enabled:step.enabled!==false,...(index===0?{type:'source'}:{})}));await api<any>('/transform/preview',{method:'POST',body:JSON.stringify({source:parsed.source,steps,limit:20})});update(project=>{const query=project.transform.queries.find((item:any)=>item.id===active);if(query){query.source=parsed.source;query.steps=steps}return project});setModal(null)}catch(e:any){setQueryEditError(e.message||'The pasted transformation script is not valid.')}finally{setQuerySaving(false)}};
 const saveQueryEditor=async()=>{if(!q||!querySql.trim())return;setQuerySaving(true);setQueryEditError('');const sourceStep=q.steps.find((s:any)=>s.type==='source')||{id:'src-'+q.id,type:'source',label:'Source: '+q.source,enabled:true};const next=[structuredClone(sourceStep),{id:crypto.randomUUID(),type:'native_query',label:'Advanced Query',sql:querySql.trim(),enabled:true}];try{await api<any>('/transform/preview',{method:'POST',body:JSON.stringify({source:q.source,steps:next,limit:20})});mutateSteps(()=>next);setModal(null)}catch(e:any){setQueryEditError(e.message)}finally{setQuerySaving(false)}};

 const contextMenu=(col:string,x:number,y:number)=>{setSelectedCol(col);setCtx({x,y,col});setHeaderMenu(null)};
 const menuItems=(col:string)=><>
   <button onClick={()=>{setRenameCol(col);setRenameValue(col);setCtx(null)}}>Rename</button>
   {availableDataTypes(rows,col,q?.steps).map(([icon,type])=><button key={type} onClick={()=>{quickType(col,type);setCtx(null)}}><b>{icon}</b> {type}</button>)}<hr/>
   <button onClick={()=>quickSort(col,'asc')}>Sort Ascending</button><button onClick={()=>quickSort(col,'desc')}>Sort Descending</button>
   <button onClick={()=>open('filter',col)}>Filter…</button><hr/>
   <button onClick={()=>open('replace',col)}>Replace Values / Nulls…</button><button onClick={()=>open('split',col)}>Split by Delimiter…</button><button onClick={()=>open('merge',col)}>Merge Columns…</button><hr/>
   <button onClick={()=>open('text',col)}>Text Functions…</button><button onClick={()=>textOp(col,'trim')}>Trim</button><button onClick={()=>textOp(col,'clean')}>Clean</button><button onClick={()=>textOp(col,'upper')}>UPPERCASE</button><button onClick={()=>textOp(col,'lower')}>lowercase</button><button onClick={()=>textOp(col,'capitalize')}>Capitalize</button><hr/>
   <button onClick={()=>open('date',col)}>Date Conversion…</button><button onClick={()=>datePart(col,'year')}>Add Year</button><button onClick={()=>datePart(col,'month')}>Add Month</button><button onClick={()=>datePart(col,'quarter')}>Add Quarter</button><hr/>
   <button onClick={()=>open('calculated',col)}>Add Column…</button><button onClick={()=>open('unpivot',col)}>Transpose (Unpivot)…</button><hr/>
   <button className="danger" onClick={()=>removeCol(col)}>Remove Column</button>
 </>;

 const activeFormulaStep=q?.steps?.[stepIndex>=0?stepIndex:Math.max(0,(q?.steps?.length||1)-1)];
 const formulaText=activeFormulaStep?`= ${activeFormulaStep.type}(${Object.entries(activeFormulaStep).filter(([k])=>!['id','enabled','label','type'].includes(k)).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):String(v)}`).join('; ')||'source'})`:'= Source';
 return <div className={'workspaceGlass transformShellGlass '+(!queriesPaneVisible?'queriesHidden ':'')+(!stepsPaneVisible?'stepsHidden ':'')} onClick={()=>{setHeaderMenu(null);setCtx(null);setQueryMenu(null);setMoreMenuOpen(false)}}>
  {queriesPaneVisible&&<div className="paneGlass leftPaneGlass transformQueriesGlass"><div className="paneTitleGlass"><span>Queries</span><div className="paneHeaderActionsGlass"><button className="iconGlass" onClick={newQuery} title="New query"><Plus size={15}/></button><button className="iconGlass" onClick={()=>setQueriesPaneVisible(false)} title="Hide queries pane"><PanelLeftClose size={15}/></button></div></div><div className="querySearchBoxGlass"><Search size={14}/><input className="inputGlass" style={{marginBottom:0, padding:'8px 12px', paddingLeft:'32px'}} value={querySearch} onChange={e=>setQuerySearch(e.target.value)} placeholder="Search queries..."/></div><div className="queryListGlass">{project?.transform.queries.filter((x:any)=>!querySearch.trim()||(x.name+' '+x.source).toLowerCase().includes(querySearch.toLowerCase())).map((x:any)=><div key={x.id} className={'queryRowGlass '+(active===x.id?'active':'')}><button className="queryItemGlass" title={`${x.name} · ${x.source}`} onClick={e=>{e.stopPropagation();setActive(x.id)}}><Rows3 size={15}/><div className="queryTextGlass"><b>{compactQueryName(x.name,x.source)}</b><small>{compactSourceName(x.source)}</small></div></button><div className="queryRowActionsGlass"><button title="Query actions" onClick={e=>{e.stopPropagation();setQueryMenu(queryMenu===x.id?null:x.id)}}><MoreVertical size={15}/></button>{queryMenu===x.id&&<div className="queryActionMenuGlass" onClick={e=>e.stopPropagation()}><button onClick={()=>removeQueryOnly(x)}><XCircle size={14}/><span><b>Remove Query</b><small>Keep the source table</small></span></button><button className="btnGlass danger" onClick={()=>deleteSourceTable(x)}><Trash2 size={14}/><span><b>Delete Source Table</b><small>Remove table and dependencies</small></span></button></div>}</div></div>)}</div><div className="hintGlass"><b>Direct manipulation</b><br/>Double-click a column header to rename. Click the type icon to convert.</div></div>}
  <div className="mainPanelGlass transformGlass">
   <div className="panelHeaderGlass transformCommandHeader"><div className="transformTitleBlock"><span className="eyebrowGlass">POWER QUERY WORKSPACE</span><h2>{q?.name||'No query selected'}</h2><p>{q?compactSourceName(q.source):'Load a source to begin transforming data.'}</p></div><div className="toolbarGlass transformPrimaryActions"><button className="btnGlass iconLabel" onClick={()=>setQueriesPaneVisible(v=>!v)} title="Show or hide Queries">{queriesPaneVisible?<PanelLeftClose size={16}/>:<PanelLeftOpen size={16}/>}<span>Queries</span></button><button className="btnGlass iconLabel" onClick={()=>setStepsPaneVisible(v=>!v)} title="Show or hide Applied Steps">{stepsPaneVisible?<PanelRightClose size={16}/>:<PanelRightOpen size={16}/>}<span>Steps</span></button><span className="commandDivider"/><button className="btnGlass iconOnly" disabled={!undoStack.length} onClick={undo} title="Undo"><Undo2 size={16}/></button><button className="btnGlass iconOnly" disabled={!redoStack.length} onClick={redo} title="Redo"><Redo2 size={16}/></button><button className="btnGlass iconLabel" disabled={!q} onClick={openQueryEditor} title="View the complete transformation sequence"><Braces size={16}/><span>Advanced Editor</span></button><button className="btnGlass iconLabel" onClick={()=>run()} title="Refresh preview"><Play size={16}/><span>{loading?'Running…':'Preview'}</span></button><div className="transformMoreMenu"><button ref={moreMenuRef} className={'btnGlass iconOnly '+(moreMenuOpen?'active':' ')} title="Query actions" aria-label="Query actions" onClick={e=>{e.stopPropagation();const r=moreMenuRef.current?.getBoundingClientRect();if(r)setMoreMenuPos({top:r.bottom+4,right:window.innerWidth-r.right});setMoreMenuOpen(x=>!x)}}><ChevronDown size={17}/></button>{moreMenuOpen&&<div className="transformMoreDropdown" style={{top:moreMenuPos.top,right:moreMenuPos.right}} onClick={e=>e.stopPropagation()}><button onClick={()=>{getAI();setMoreMenuOpen(false)}}><Sparkles size={15}/>AI clean suggestions</button><button onClick={()=>{apply();setMoreMenuOpen(false)}}><Check size={15}/>Apply current query</button></div>}</div><button className="btnGlass primary closeApplyAction" onClick={applyAll} title="Materialize every query and continue to the semantic model"><Check size={17}/><span>Close & Apply</span></button></div></div>
   <div className="powerQueryRibbon"><div className="powerQueryRibbonTabs" role="tablist" aria-label="Transform commands"><button className={ribbonTab==='home'?'active':''} onClick={()=>setRibbonTab('home')}>Home</button><button className={ribbonTab==='transform'?'active':''} onClick={()=>setRibbonTab('transform')}>Transform</button><button className={ribbonTab==='add'?'active':''} onClick={()=>setRibbonTab('add')}>Add Column</button><button className={ribbonTab==='combine'?'active':''} onClick={()=>setRibbonTab('combine')}>Combine</button></div><div className="stepRibbonGlass powerQueryCommands">{ribbonTab==='home'&&<><button onClick={()=>open('columns')}><Columns3 size={18}/><span>Choose<br/>columns</span></button><button onClick={()=>open('bulktypes')}><Type size={18}/><span>Data<br/>types</span></button><button onClick={()=>open('filter')}><Filter size={18}/><span>Filter<br/>rows</span></button><button onClick={()=>open('replace')}><Wand2 size={18}/><span>Replace<br/>values</span></button><button onClick={distinct}><Rows3 size={18}/><span>Remove<br/>duplicates</span></button><button onClick={top}><ArrowDownAZ size={18}/><span>Keep<br/>Top N</span></button></>}{ribbonTab==='transform'&&<><button onClick={()=>open('split')}><Scissors size={18}/><span>Split<br/>column</span></button><button onClick={()=>open('merge')}><Combine size={18}/><span>Merge<br/>columns</span></button><button onClick={()=>open('date')}><CalendarDays size={18}/><span>Date<br/>tools</span></button><button onClick={()=>open('text')}><TextCursorInput size={18}/><span>Text<br/>tools</span></button><button onClick={()=>open('unpivot')}><Columns3 size={18}/><span>Unpivot<br/>columns</span></button><button onClick={()=>open('bulktypes')}><Type size={18}/><span>Convert<br/>type</span></button></>}{ribbonTab==='add'&&<><button onClick={()=>open('calendar')}><CalendarPlus size={18}/><span>Calendar<br/>table</span></button><button onClick={()=>open('conditional')}><Wand2 size={18}/><span>Conditional<br/>column</span></button><button onClick={()=>open('calculated')}><Braces size={18}/><span>Calculated<br/>column</span></button></>}{ribbonTab==='combine'&&<><button onClick={()=>open('join')}><Link2 size={18}/><span>Merge<br/>queries</span></button><button onClick={()=>open('append')}><CopyPlus size={18}/><span>Append<br/>queries</span></button><button onClick={()=>open('group')}><Group size={18}/><span>Group<br/>by</span></button></>}<span className="ribbonSpacerGlass"/><button className={compare?'active':''} onClick={()=>setCompare(x=>!x)}><Columns3 size={18}/><span>Before /<br/>after</span></button></div></div>
   <div className="powerQueryFormulaBar" title={formulaText}><b>fx</b><button title="Cancel formula edit">×</button><button title="Apply formula">✓</button><code>{formulaText}</code></div>
   <div className="transformBodyGlass">
    <div className="previewGridGlass">
     {error&&<div className="validationGlass bad">{error}</div>}
     <div className="foldBarGlass"><div><Check size={14}/><b>Query folding</b><span>{folding.filter(x=>x.status==='pushdown'||x.status==='native').length}/{folding.length||1} steps pushed to source</span></div><button className="btnGlass" onClick={()=>navigator.clipboard?.writeText(sql)}>Copy SQL</button></div>
     <details className="sqlDetailsGlass"><summary>View generated SQL</summary><code>{sql}</code></details>
     {ai.length>0&&<div className="aiSuggestionsGlass"><div className="aiTitleGlass"><Sparkles size={15}/><b>AI transformation suggestions</b><button className="iconGlass" onClick={()=>setAi([])}>×</button></div>{ai.map((s,i)=><div className="aiSuggestionGlass" key={i}><div><b>{s.title}</b><small>{s.reason}</small></div><button className="btnGlass" onClick={()=>add(s.step)}>Apply</button></div>)}</div>}
     {compare&&stepIndex>=0?<div className="compareGridGlass"><div><h4>Before step {stepIndex+1}</h4><MiniTable rows={beforeRows}/></div><div><h4>After step {stepIndex+1}</h4><MiniTable rows={afterRows}/></div></div>:<div className="excelGridWrapGlass"><table className="tableGlass excelGridGlass"><thead><tr>{cols.map(c=><th key={c} className={selectedCols.includes(c)?'selectedTransformColumn':''} onContextMenu={e=>{e.preventDefault();e.stopPropagation();contextMenu(c,e.clientX,e.clientY)}}><div className="columnHeaderGlass">
       <button className="dtypeGlass" title="Change data type" onClick={e=>{e.stopPropagation();setSelectedCol(c);setHeaderMenu(headerMenu===`type:${c}`?null:`type:${c}`)}}>{dataTypeGlyph(rows,c,q?.steps)}</button>
       {renameCol===c?<input className="inputGlass smallInput" autoFocus value={renameValue} onChange={e=>setRenameValue(e.target.value)} onBlur={()=>quickRename(c,renameValue)} onKeyDown={e=>{if(e.key==='Enter')quickRename(c,renameValue);if(e.key==='Escape')setRenameCol(null)}}/>:<span title="Click to select · Double-click to rename" onClick={e=>{e.stopPropagation();setSelectedCol(c);setSelectedCols(s=>s.includes(c)?s.filter(x=>x!==c):[...s,c])}} onDoubleClick={e=>{e.stopPropagation();setRenameCol(c);setRenameValue(c)}}>{c}</span>}
       <button className="headDropGlass" onClick={e=>{e.stopPropagation();const r=e.currentTarget.getBoundingClientRect();setSelectedCol(c);setCtx({x:Math.min(r.left,window.innerWidth-252),y:Math.min(r.bottom+4,window.innerHeight-520),col:c});setHeaderMenu(null)}}><ChevronDown size={13}/></button>
       {headerMenu===`type:${c}`&&<div className="typeMenuGlass" onClick={e=>e.stopPropagation()}>{availableDataTypes(rows,c,q?.steps).map(([ic,t])=><button key={t} onClick={()=>{quickType(c,t);setHeaderMenu(null)}}><b>{ic}</b>{t}</button>)}</div>}
       </div></th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{cols.map(c=><td key={c} title="Double-click to edit (creates Replace Value step)" onDoubleClick={()=>editCell(c,r[c])}>{formatCell(r[c],configuredColumnType(q?.steps,c))}</td>)}</tr>)}</tbody></table></div>}
     <div className="gridStatusGlass"><span>{rows.length} preview rows</span><span>{cols.length} columns</span><span>{selectedCols.length} selected</span><span>Click column names to multi-select · Double-click cells to replace</span></div>
    </div>
    <div className="stepsPaneGlass powerBiAppliedSteps"><h3>Query Settings</h3><label className="formFieldGlass"><span>Name</span><input className="inputGlass" value={q?.name||''} readOnly/></label><small className="sourceHintGlass" title={q?.source}>Source: {q?compactSourceName(q.source):''}</small><h3>Applied Steps</h3><div className="appliedStepsList">{q?.steps.map((s:any,i:number)=>{const f=folding.find(x=>x.id===s.id);const editable=s.type==='calculated_column'||s.type==='bulk_change_type';return <div className={'stepGlass '+(stepIndex===i?'selected':'')+(s.enabled===false?' disabled':'')} key={s.id} draggable={i>0} onDragStart={e=>e.dataTransfer.setData('text/step-index',String(i))} onDragOver={e=>{if(i>0)e.preventDefault()}} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/step-index'));if(Number.isInteger(from)&&from>0&&from!==i)moveStep(from,i-from)}} onClick={()=>setStepIndex(i)} onDoubleClick={()=>{const label=window.prompt('Rename applied step',s.label);if(label?.trim())renameStep(s.id,label.trim())}}><span className={'stepStateLine '+(f?.status||'native')}/><span className="stepName" title={s.label}>{s.label}</span>{editable&&<button className="stepGear" title="Edit step settings" onClick={e=>{e.stopPropagation();editStep(s,i)}}><Settings2 size={13}/></button>}{s.type!=='source'&&<button className="stepEnable" title={s.enabled===false?'Enable step':'Disable step'} onClick={e=>{e.stopPropagation();toggleStep(s.id)}}>{s.enabled===false?<EyeOff size={13}/>:<Eye size={13}/>}</button>}{s.type!=='source'&&<button className="stepRemove" title="Delete step" onClick={e=>{e.stopPropagation();removeStep(s.id)}}>×</button>}</div>})}</div><div className="appliedStepsFooter"><span><i className="foldDot pushdown"/>Folds to source</span><span>Drag to reorder · double-click to rename</span></div></div>
   </div>
  </div>
   {ctx&&<div className="contextMenu" style={{left:ctx.x,top:ctx.y}} onClick={e=>e.stopPropagation()}>{menuItems(ctx.col)}</div>}
   {modal==='query'&&q&&<Modal title={`Advanced Editor — ${q.name}`} onClose={()=>setModal(null)} wide><div className="advancedQueryEditor"><div className="advancedEditorTabs"><button className={queryEditorTab==='steps'?'active':''} onClick={()=>setQueryEditorTab('steps')}>Transformation script</button><button className={queryEditorTab==='sql'?'active':''} onClick={()=>setQueryEditorTab('sql')}>Native SQL</button></div>{queryEditorTab==='steps'?<><p className="dialogHint">Edit or paste a complete exported transformation script. Keep the VTAB_QUERY_V1 definition at the end so the query can be validated and rebuilt safely.</p><textarea className="powerQueryScript" value={advancedScript} onChange={e=>setAdvancedScript(e.target.value)} spellCheck={false}/>{queryEditError&&<div className="validationGlass bad">{queryEditError}</div>}<div className="advancedEditorStatus"><Check size={15}/> Editable portable query · {q.steps.filter((s:any)=>s.enabled!==false).length} enabled steps</div><div className="dialogActions"><button onClick={()=>navigator.clipboard?.writeText(advancedScript)}><CopyPlus size={14}/>Copy</button><button onClick={()=>{setAdvancedScript(buildAdvancedScript(q));setQueryEditError('')}}>Reset</button><button className="primary" disabled={querySaving||!advancedScript.trim()} onClick={saveAdvancedScript}><Save size={14}/>{querySaving?'Validating…':'Save & Apply'}</button></div></>:<><p className="dialogHint">Optional expert mode. Saving a native SELECT or WITH query replaces transformation steps after Source. Data-changing and file-reading commands remain blocked.</p><textarea value={querySql} onChange={e=>setQuerySql(e.target.value)} spellCheck={false}/>{queryEditError&&<div className="validationGlass bad">{queryEditError}</div>}<div className="dialogActions"><button onClick={()=>setQueryEditorTab('steps')}>Back</button><button className="primary" disabled={querySaving||!querySql.trim()} onClick={saveQueryEditor}><Save size={14}/>{querySaving?'Validating…':'Validate & Save SQL'}</button></div></>}</div></Modal>}
   {modal==='bulktypes'&&<BulkTypesDialog cols={cols} rows={rows} initialMappings={stepEdit?.step.type==='bulk_change_type'?Object.fromEntries((stepEdit.step as any).mappings.map((m:any)=>[m.field,m.dataType])):null} onClose={()=>{setModal(null);setStepEdit(null)}} onApply={(x:any)=>{if(stepEdit)saveStepEdit(x);else{add(x);setModal(null)}}}/>}
  {modal==='columns'&&<ColumnManagerDialog cols={cols} initial={selectedCols} onClose={()=>setModal(null)} onSelect={(x:string[])=>{setSelectedCols(x);setModal(null)}} onApply={(x:any,chosen:string[])=>{setSelectedCols(chosen);add(x);setModal(null)}}/>}
   {modal==='filter'&&<FilterDialog col={selectedCol} cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='split'&&<SplitDialog col={selectedCol} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='merge'&&<MergeDialog cols={cols} initial={selectedCol} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='replace'&&<ReplaceDialog col={selectedCol} cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='date'&&<DateDialog col={selectedCol} cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='text'&&<TextFunctionsDialog col={selectedCol||cols[0]||''} cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
  {modal==='calendar'&&<CalendarTableDialog meta={meta} onClose={()=>setModal(null)} onCreated={async(r:any)=>{setModal(null);await load();setActive(r.queryId);alert(`Calendar table ${r.queryName} created with ${r.rows.toLocaleString()} rows. Review it in Transform, then Close & Apply.`)}}/>}
   {modal==='conditional'&&<ConditionalDialog cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='calculated'&&q&&<CalculatedDialog cols={cols} source={q.source} steps={stepEdit?q.steps.slice(0,stepEdit.index):q.steps} initialColumns={selectedCols} initialStep={stepEdit?.step||null} mode={stepEdit?'edit':'create'} onClose={()=>{setModal(null);setStepEdit(null)}} onApply={(x:any)=>{if(stepEdit)saveStepEdit(x);else{add(x);setModal(null)}}}/>}
   {modal==='join'&&q&&<JoinDialog source={q.source} steps={q.steps} cols={cols} meta={meta} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='append'&&<AppendDialog meta={meta} source={q?.source||''} queries={queries} currentQueryId={q?.id} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='group'&&<GroupDialog cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
   {modal==='unpivot'&&<TransposeDialog selectedCols={selectedCols} col={selectedCol} cols={cols} onClose={()=>setModal(null)} onApply={(x:any)=>{add(x);setModal(null)}}/>}
 </div>
}

function guessType(rows:any[],c:string){const vals=rows.slice(0,25).map(r=>r[c]).filter(v=>v!==null&&v!=='');if(!vals.length)return 'ABC';if(vals.every(v=>typeof v==='number'&&Number.isInteger(v)))return '123';if(vals.every(v=>typeof v==='number'))return '1.2';if(vals.every(v=>typeof v==='boolean'||v===0||v===1))return '✓';if(vals.every(v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}/.test(v)))return '📅';return 'ABC'}
function dataTypeGlyph(rows:any[],column:string,steps?:Step[]){const type=configuredColumnType(steps,column).dataType;const icons:Record<string,string>={text:'ABC',integer:'123',decimal:'1.2',currency:'$',date:'📅',datetime:'◷',boolean:'✓'};return icons[type]||guessType(rows,column)}
function formatCell(v:any,configured?:{dataType:string,currency:string}){if(v===null||v===undefined)return <span className="nullCell">null</span>;if(configured?.dataType==='currency'&&Number.isFinite(Number(v))){try{return new Intl.NumberFormat('en-US',{style:'currency',currency:configured.currency||'USD'}).format(Number(v))}catch{return `$${Number(v).toLocaleString()}`}}if(configured?.dataType==='integer'&&Number.isFinite(Number(v)))return Math.trunc(Number(v)).toLocaleString();if(configured?.dataType==='decimal'&&Number.isFinite(Number(v)))return Number(v).toLocaleString(undefined,{maximumFractionDigits:6});if(typeof v==='number')return v.toLocaleString();return String(v)}



function TextFunctionsDialog({col,cols,onClose,onApply}:any){
 const[field,setField]=useState(col||cols[0]||'');const[operation,setOperation]=useState('upper');const[arg,setArg]=useState('');const[arg2,setArg2]=useState('');const[output,setOutput]=useState('');
 const ops=[
  ['upper','UPPERCASE'],['lower','lowercase'],['trim','Trim'],['clean','Clean non-printing'],['proper','Capitalize / Proper'],['replace','Replace text'],['length','Length'],['index','Index / Position of text'],['contains','Contains text'],['starts_with','Starts with'],['ends_with','Ends with'],['before_delimiter','Text before delimiter'],['after_delimiter','Text after delimiter'],['prefix','Add prefix'],['suffix','Add suffix'],['pad_start','Pad start'],['pad_end','Pad end'],['extract_start','First N characters'],['extract_end','Last N characters'],['range','Text range'],['reverse','Reverse'],['remove_spaces','Remove spaces']
 ];
 const needsArg=['replace','index','contains','starts_with','ends_with','before_delimiter','after_delimiter','prefix','suffix','pad_start','pad_end','extract_start','extract_end','range'].includes(operation);
 const needsArg2=['replace','pad_start','pad_end','range'].includes(operation);
 const argLabel=operation==='replace'?'Text to find':['pad_start','pad_end','extract_start','extract_end','range'].includes(operation)?'Length / start position':'Text / delimiter / prefix';
 return <Modal title="Text Transformations" onClose={onClose} wide><div className="textFunctionDialog"><div className="textFunctionIntro"><b>Power Query-style text functions</b><span>Apply a function in place or create a new derived text column.</span></div><div className="twoCol"><FieldSelect label="Column" value={field} onChange={setField} cols={cols}/><label className="formField"><span>Function</span><select value={operation} onChange={e=>setOperation(e.target.value)}>{ops.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>{needsArg&&<div className="twoCol"><label className="formField"><span>{argLabel}</span><input value={arg} onChange={e=>setArg(e.target.value)} placeholder={operation.includes('delimiter')?'e.g. -':operation.startsWith('pad')?'e.g. 10':'value'}/></label>{needsArg2&&<label className="formField"><span>{operation==='replace'?'Replacement text':operation==='range'?'Number of characters':'Padding character'}</span><input value={arg2} onChange={e=>setArg2(e.target.value)} placeholder={operation==='replace'?'new value':operation==='range'?'5':'0'}/></label>}</div>}<label className="formField"><span>Output column name (optional)</span><input value={output} onChange={e=>setOutput(e.target.value)} placeholder="Leave blank to replace the selected column"/></label><div className="functionLibrary"><b>Available:</b><span>Upper</span><span>Lower</span><span>Trim</span><span>Clean</span><span>Proper</span><span>Replace</span><span>Length</span><span>Index</span><span>Contains</span><span>Starts/Ends With</span><span>Before/After Delimiter</span><span>Prefix/Suffix</span><span>Pad</span><span>Extract</span><span>Reverse</span></div></div><DialogActions onClose={onClose} disabled={!field||(needsArg&&!arg)} onApply={()=>onApply({type:'text_transform',label:`${ops.find(x=>x[0]===operation)?.[1]} ${field}`,field,operation,argument:arg,argument2:arg2,outputName:output.trim()||field})}/></Modal>
}

function CalendarTableDialog({meta,onClose,onCreated}:any){
 const[mode,setMode]=useState<'column'|'manual'>('column');const[name,setName]=useState('Calendar');const[startDate,setStartDate]=useState('2024-01-01');const[endDate,setEndDate]=useState('2026-12-31');const[sourceTable,setSourceTable]=useState(meta[0]?.name||'');const[sourceColumn,setSourceColumn]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const[catalog,setCatalog]=useState<any>({groups:[],columns:[],count:0,recommendedCount:0});const[selected,setSelected]=useState<Set<string>>(new Set());const[colSearch,setColSearch]=useState('');const[group,setGroup]=useState('All');
 const table=meta.find((m:any)=>m.name===sourceTable);const dateCols=(table?.columns||[]).filter((c:any)=>/date|time|created|updated/i.test(c.name+' '+c.type)).map((c:any)=>c.name);useEffect(()=>{if(dateCols.length&&!dateCols.includes(sourceColumn))setSourceColumn(dateCols[0])},[sourceTable,dateCols.join('|')]);
 useEffect(()=>{api<any>('/transform/calendar-columns').then(r=>{setCatalog(r);setSelected(new Set((r.columns||[]).filter((x:any)=>x.recommended).map((x:any)=>x.name))) }).catch((e:any)=>setError(e.message))},[]);
 const visible=useMemo(()=>{const q=colSearch.toLowerCase().trim();return (catalog.columns||[]).filter((x:any)=>(group==='All'||x.group===group)&&(!q||x.name.toLowerCase().includes(q)))},[catalog,colSearch,group]);
 const toggle=(n:string)=>setSelected(s=>{const x=new Set(s);x.has(n)?x.delete(n):x.add(n);return x});
 const selectRecommended=()=>setSelected(new Set((catalog.columns||[]).filter((x:any)=>x.recommended).map((x:any)=>x.name)));
 const selectAll=()=>setSelected(new Set((catalog.columns||[]).map((x:any)=>x.name)));
 const selectVisible=()=>setSelected(s=>{const x=new Set(s);visible.forEach((c:any)=>x.add(c.name));return x});
 const clear=()=>setSelected(new Set(['Date']));
 const create=async()=>{setBusy(true);setError('');try{const cols=Array.from(selected);if(!cols.includes('Date'))cols.unshift('Date');const r=await api<any>('/transform/calendar',{method:'POST',body:JSON.stringify({name,mode,startDate,endDate,sourceTable,sourceColumn,columns:cols})});onCreated(r)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const groups=['All',...(catalog.groups||[]).map((g:any)=>g.name)];
 return <Modal title="Create Business Calendar Table" onClose={onClose} wide><div className="calendarBuilder calendar360Builder selectableCalendarBuilder"><div className="calendarIntro360"><div><CalendarPlus size={22}/><div><b>Enterprise Date Dimension · choose only the columns you need</b><span>Derive the date range from an existing table/date field or enter Start and End dates. The full library contains 360 governed date attributes, but only your checked columns are materialized.</span></div></div><strong>{selected.size}</strong></div><div className="calendarMode"><button className={mode==='column'?'active':''} onClick={()=>setMode('column')}>Reference existing table / date column</button><button className={mode==='manual'?'active':''} onClick={()=>setMode('manual')}>Use Start Date / End Date</button></div><label className="formField"><span>Calendar query name</span><input value={name} onChange={e=>setName(e.target.value)}/></label>{mode==='column'?<div className="twoCol"><label className="formField"><span>Source table</span><select value={sourceTable} onChange={e=>setSourceTable(e.target.value)}>{meta.map((m:any)=><option key={m.name}>{m.name}</option>)}</select></label><label className="formField"><span>Date column</span><select value={sourceColumn} onChange={e=>setSourceColumn(e.target.value)}>{dateCols.map((c:string)=><option key={c}>{c}</option>)}</select></label></div>:<div className="twoCol"><label className="formField"><span>Start Date</span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label className="formField"><span>End Date</span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>}
 <div className="calendarColumnSelector"><div className="calendarSelectorTop"><div><b>Select Calendar Columns</b><span>{selected.size} selected from {catalog.count||360}. Date is always included.</span></div><div className="calendarSelectorActions"><button onClick={selectRecommended}>Select Recommended</button><button onClick={selectVisible}>Select Visible</button><button onClick={selectAll}>Select All 360</button><button onClick={clear}>Clear</button></div></div><div className="calendarSelectorFilters"><div className="calendarColumnSearch"><Search size={14}/><input value={colSearch} onChange={e=>setColSearch(e.target.value)} placeholder="Search date columns..."/></div><div className="calendarGroupTabs">{groups.map(g=><button key={g} className={group===g?'active':''} onClick={()=>setGroup(g)}>{g}</button>)}</div></div><div className="calendarCheckGrid">{visible.map((c:any)=><label key={c.name} className={'calendarCheck '+(selected.has(c.name)?'selected':'')}><input type="checkbox" checked={selected.has(c.name)} disabled={c.name==='Date'} onChange={()=>toggle(c.name)}/><span><b>{c.name}</b><small>{c.group}{c.recommended?' · Recommended':''}</small></span></label>)}</div></div>
 {error&&<div className="validation bad">{error}</div>}</div><div className="dialogActions"><button onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!name.trim()||selected.size<1||(mode==='column'&&!sourceColumn)||(mode==='manual'&&(!startDate||!endDate))} onClick={create}>{busy?'Creating…':`Create Calendar (${selected.size} columns)`}</button></div></Modal>
}

function BulkTypesDialog({cols,rows,onClose,onApply,initialMappings}:any){
 const infer=(c:string)=>{
   const vals=rows.slice(0,40).map((r:any)=>r[c]).filter((v:any)=>v!==null&&v!=='');
   if(/date|time/i.test(c)||vals.every((v:any)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}/.test(v)))return 'date';
   if(vals.length&&vals.every((v:any)=>typeof v==='number'&&Number.isInteger(v)))return 'integer';
   if(vals.length&&vals.every((v:any)=>typeof v==='number'))return 'decimal';
   if(vals.length&&vals.every((v:any)=>typeof v==='boolean'||v===0||v===1))return 'boolean';
   return 'text'
 };
 const[state,setState]=useState<Record<string,string>>(()=>Object.fromEntries(cols.map((c:string)=>[c,initialMappings?.[c]||infer(c)])));const[currency,setCurrency]=useState('USD');
 const set=(c:string,t:string)=>setState(x=>({...x,[c]:t}));
 return <Modal title="Change Data Types — All Columns" onClose={onClose} wide>
   <p className="dialogHint">Review and change the datatype for every column in one operation. Date columns will automatically receive a Year → Quarter → Month → Week → Day hierarchy after Close & Apply.</p>
   <div className="bulkTypeGrid">
    <div className="bulkTypeHead"><b>Column</b><b>Detected / Target Type</b></div>
    {cols.map((c:string)=><div className="bulkTypeRow" key={c}><span>{c}</span><select value={state[c]} onChange={e=>set(c,e.target.value)}>{availableDataTypes(rows,c).map(([ic,t])=><option value={t} key={t}>{ic}  {t}</option>)}</select></div>)}
    </div>
    {Object.values(state).includes('currency')&&<label className="formField"><span>Currency code for currency columns</span><select value={currency} onChange={e=>setCurrency(e.target.value)}>{['USD','EUR','GBP','INR','JPY','AUD','CAD','AED','SGD'].map(x=><option key={x}>{x}</option>)}</select></label>}
    <DialogActions onClose={onClose} onApply={()=>onApply({type:'bulk_change_type',label:`Set data types for ${cols.length} columns`,mappings:cols.map((field:string)=>({field,dataType:state[field],dateFormat:'auto',...(state[field]==='currency'?{currency}:{})}))})}/>
 </Modal>
}

function FilterDialog({col,cols,onClose,onApply}:any){const[field,setField]=useState(col||cols[0]||'');const[op,setOp]=useState('equals');const[value,setValue]=useState('');return <Modal title="Filter Rows" onClose={onClose}><div className="formGrid"><FieldSelect label="Column" value={field} onChange={setField} cols={cols}/><label className="formField"><span>Condition</span><select value={op} onChange={e=>setOp(e.target.value)}>{['equals','not_equals','contains','starts_with','ends_with','gt','gte','lt','lte','is_blank','is_not_blank'].map(x=><option key={x}>{x}</option>)}</select></label>{!op.includes('blank')&&<label className="formField"><span>Value</span><input value={value} onChange={e=>setValue(e.target.value)}/></label>}</div><DialogActions onClose={onClose} onApply={()=>onApply({type:'filter',label:`Filter ${field} ${op}${value?' '+value:''}`,field,operator:op,value})}/></Modal>}
function SplitDialog({col,onClose,onApply}:any){const[delimiter,setDelimiter]=useState(',');const[leftName,setLeft]=useState((col||'Column')+'_1');const[rightName,setRight]=useState((col||'Column')+'_2');return <Modal title="Split Column by Delimiter" onClose={onClose}><p className="dialogHint">Preview-safe transformation. The source column is replaced by two output columns.</p><label className="formField"><span>Column</span><input value={col} readOnly/></label><div className="delimiterChips">{DELIMS.map(([n,v])=><button className={delimiter===v?'active':''} key={n} onClick={()=>setDelimiter(v)}>{n}</button>)}</div><label className="formField"><span>Custom delimiter</span><input value={delimiter} onChange={e=>setDelimiter(e.target.value)}/></label><div className="formGrid two"><label className="formField"><span>First output</span><input value={leftName} onChange={e=>setLeft(e.target.value)}/></label><label className="formField"><span>Second output</span><input value={rightName} onChange={e=>setRight(e.target.value)}/></label></div><DialogActions onClose={onClose} onApply={()=>onApply({type:'split_delimiter',label:`Split ${col} by '${delimiter}'`,field:col,delimiter,leftName,rightName,occurrence:'first'})}/></Modal>}
function MergeDialog({cols,initial,onClose,onApply}:any){const[chosen,setChosen]=useState<string[]>(initial?[initial]:[]);const[delimiter,setDelimiter]=useState(' ');const[name,setName]=useState('Merged Column');const[remove,setRemove]=useState(false);return <Modal title="Merge Columns" onClose={onClose}><div className="checkList">{cols.map((c:string)=><label key={c}><input type="checkbox" checked={chosen.includes(c)} onChange={()=>setChosen(x=>x.includes(c)?x.filter(z=>z!==c):[...x,c])}/>{c}</label>)}</div><div className="formGrid two"><label className="formField"><span>Delimiter</span><input value={delimiter} onChange={e=>setDelimiter(e.target.value)}/></label><label className="formField"><span>Output column</span><input value={name} onChange={e=>setName(e.target.value)}/></label></div><label className="checkRow"><input type="checkbox" checked={remove} onChange={e=>setRemove(e.target.checked)}/>Remove original columns</label><DialogActions onClose={onClose} disabled={chosen.length<2} onApply={()=>onApply({type:'merge_columns',label:`Merge ${chosen.join(' + ')}`,fields:chosen,delimiter,name,removeOriginals:remove})}/></Modal>}
function ReplaceDialog({col,cols,onClose,onApply}:any){const[field,setField]=useState(col||cols[0]);const[mode,setMode]=useState('value');const[oldValue,setOld]=useState('');const[newValue,setNew]=useState('');return <Modal title="Replace Values / Nulls" onClose={onClose}><FieldSelect label="Column" value={field} onChange={setField} cols={cols}/><div style={{display:'flex',gap:8,marginBottom:16}}><button className={'btnGlass '+(mode==='value'?'primary':'')} onClick={()=>setMode('value')}>Replace value</button><button className={'btnGlass '+(mode==='null'?'primary':'')} onClick={()=>setMode('null')}>Replace blank / null</button></div>{mode==='value'&&<label className="formField"><span>Value to find</span><input value={oldValue} onChange={e=>setOld(e.target.value)}/></label>}<label className="formField"><span>Replace with</span><input value={newValue} onChange={e=>setNew(e.target.value)}/></label><DialogActions onClose={onClose} onApply={()=>onApply({type:'replace',label:`Replace ${mode==='null'?'blank/null':'values'} in ${field}`,field,mode,oldValue,newValue})}/></Modal>}
function DateDialog({col,cols,onClose,onApply}:any){const[field,setField]=useState(col||cols[0]);const[fmt,setFmt]=useState('auto');const[part,setPart]=useState('');return <Modal title="Date Conversion & Date Parts" onClose={onClose}><FieldSelect label="Date column" value={field} onChange={setField} cols={cols}/><label className="formField"><span>Input format</span><select value={fmt} onChange={e=>setFmt(e.target.value)}>{['auto','yyyy-mm-dd','dd/mm/yyyy','mm/dd/yyyy','dd-mm-yyyy','mm-dd-yyyy','yyyymmdd'].map(x=><option key={x}>{x}</option>)}</select></label><label className="formField"><span>Then optionally add</span><select value={part} onChange={e=>setPart(e.target.value)}><option value="">No extra date part</option>{['year','quarter','month','month_name','week','day','weekday','start_of_month','end_of_month'].map(x=><option key={x}>{x}</option>)}</select></label><DialogActions onClose={onClose} onApply={()=>{onApply({type:'date_parse',label:`Parse ${field} as Date (${fmt})`,field,format:fmt});if(part)setTimeout(()=>onApply({type:'date_part',label:`Add ${part} from ${field}`,field,part,name:`${field}_${part}`}),0)}}/></Modal>}
function ConditionalDialog({cols,onClose,onApply}:any){const[name,setName]=useState('Conditional Column');const[rules,setRules]=useState<any[]>([{field:cols[0]||'',operator:'gte',value:'',result:''}]);const[elseValue,setElse]=useState('');const set=(i:number,k:string,v:any)=>setRules(r=>r.map((x,j)=>j===i?{...x,[k]:v}:x));return <Modal title="Visual IF / ELSE / CASE Builder" onClose={onClose} wide><label className="formField"><span>New column name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><div className="caseBuilder">{rules.map((r,i)=><div className="caseRule" key={i}><b>{i===0?'IF':'ELSE IF'}</b><select value={r.field} onChange={e=>set(i,'field',e.target.value)}>{cols.map((c:string)=><option key={c}>{c}</option>)}</select><select value={r.operator} onChange={e=>set(i,'operator',e.target.value)}>{['equals','not_equals','contains','gt','gte','lt','lte','is_blank','is_not_blank'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Value" value={r.value} onChange={e=>set(i,'value',e.target.value)}/><span>THEN</span><input placeholder="Result" value={r.result} onChange={e=>set(i,'result',e.target.value)}/><button onClick={()=>setRules(x=>x.filter((_,j)=>j!==i))}>×</button></div>)}<button className="addRule" onClick={()=>setRules(x=>[...x,{field:cols[0]||'',operator:'equals',value:'',result:''}])}>+ Add ELSE IF</button><div className="caseElse"><b>ELSE</b><input value={elseValue} onChange={e=>setElse(e.target.value)} placeholder="Default result"/></div></div><DialogActions onClose={onClose} onApply={()=>onApply({type:'conditional_column',label:`Conditional column ${name}`,name,rules:rules.map(r=>({logic:'and',conditions:[{field:r.field,operator:r.operator,value:r.value}],result:r.result})),elseValue})}/></Modal>}
function TransposeDialog({col,selectedCols,cols,onClose,onApply}:any){const[chosen,setChosen]=useState<string[]>(selectedCols?.length?selectedCols:(col?[col]:[]));const[nameCol,setNameCol]=useState('Attribute');const[valCol,setValCol]=useState('Value');return <Modal title="Transpose / Unpivot Columns" onClose={onClose}><div className="checkList">{cols.map((c:string)=><label key={c}><input type="checkbox" checked={chosen.includes(c)} onChange={()=>setChosen(x=>x.includes(c)?x.filter(z=>z!==c):[...x,c])}/>{c}</label>)}</div><div className="formGrid two"><label className="formField"><span>Attribute Column Name</span><input value={nameCol} onChange={e=>setNameCol(e.target.value)}/></label><label className="formField"><span>Value Column Name</span><input value={valCol} onChange={e=>setValCol(e.target.value)}/></label></div><DialogActions onClose={onClose} disabled={!chosen.length} onApply={()=>onApply({type:'unpivot',label:`Transpose ${chosen.length} columns`,columns:chosen,nameColumn:nameCol,valueColumn:valCol})}/></Modal>}
function ColumnManagerDialog({cols,initial,onClose,onSelect,onApply}:any){
 const[search,setSearch]=useState('');const[chosen,setChosen]=useState<string[]>(initial||[]);
 const visible=cols.filter((c:string)=>c.toLowerCase().includes(search.toLowerCase()));
 const toggle=(c:string)=>setChosen(x=>x.includes(c)?x.filter(z=>z!==c):[...x,c]);
 return <Modal title="Select Columns" onClose={onClose} wide><div className="columnManagerDialog">
   <div className="columnManagerTop"><div className="columnSearch"><Search size={15}/><input autoFocus placeholder="Search columns..." value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{chosen.length} selected of {cols.length}</span></div>
   <div className="columnManagerActions"><button onClick={()=>setChosen(cols)}>Select all</button><button onClick={()=>setChosen([])}>Clear</button><button onClick={()=>setChosen(visible)}>Select search results</button></div>
   <div className="columnSelectionGrid">{visible.map((c:string)=><button className={chosen.includes(c)?'selected':''} key={c} onClick={()=>toggle(c)}><span className="columnCheck">{chosen.includes(c)?<Check size={13}/>:null}</span><b>{c}</b></button>)}</div>
   <div className="columnManagerFooter"><button onClick={onClose}>Cancel</button><button disabled={!chosen.length} onClick={()=>onApply({type:'remove_columns',label:`Remove ${chosen.length} selected columns`,columns:chosen},chosen)}>Remove Selected</button><button disabled={!chosen.length} onClick={()=>onApply({type:'select_columns',label:`Keep ${chosen.length} selected columns`,columns:chosen},chosen)}>Keep Only Selected</button></div>
 </div></Modal>
}

function CalculatedDialog({cols,source,steps,initialColumns,initialStep,mode='create',onClose,onApply}:any){
 const[name,setName]=useState(initialStep?.name||'Calculated Column');const[expression,setExpression]=useState(initialStep?.expression||'');const[search,setSearch]=useState('');
 const[prompt,setPrompt]=useState(initialStep?.aiPrompt||'');const[promptCursor,setPromptCursor]=useState(0);const[promptFocus,setPromptFocus]=useState(false);
 const[validation,setValidation]=useState<any>(null);const[aiResult,setAiResult]=useState<any>(null);const[busy,setBusy]=useState(false);const[availableCols,setAvailableCols]=useState<string[]>(cols||[]);
 const editorRef=useRef<HTMLTextAreaElement|null>(null);const promptRef=useRef<HTMLTextAreaElement|null>(null);
 useEffect(()=>{api<any>('/transform/preview',{method:'POST',body:JSON.stringify({source,steps,limit:1})}).then(r=>setAvailableCols(r.columns||Object.keys(r.rows?.[0]||{}))).catch(()=>{})},[source,JSON.stringify(steps)]);
 const filtered=availableCols.filter((c:string)=>c.toLowerCase().includes(search.toLowerCase()));
 const token=currentToken(prompt,promptCursor).toLowerCase();const suggestions=promptFocus&&token?availableCols.filter((c:string)=>c.toLowerCase().includes(token)).slice(0,8):[];
 useEffect(()=>{if(!expression&&initialColumns?.length){setExpression(initialColumns.map((c:string)=>`[${c}]`).join(' + '))}},[]);
 const insert=(text:string)=>{const el=editorRef.current;const pos=el?.selectionStart??expression.length;const next=expression.slice(0,pos)+text+expression.slice(pos);setExpression(next);requestAnimationFrame(()=>{if(editorRef.current){const p=pos+text.length;editorRef.current.focus();editorRef.current.setSelectionRange(p,p)}})};
 const insertPrompt=(c:string)=>{const pos=promptRef.current?.selectionStart??promptCursor;const tok=currentToken(prompt,pos);const start=pos-tok.length;const next=prompt.slice(0,start)+c+prompt.slice(pos);setPrompt(next);setPromptFocus(false);requestAnimationFrame(()=>{const p=start+c.length;promptRef.current?.focus();promptRef.current?.setSelectionRange(p,p)})};
 const validate=async()=>{setBusy(true);try{const r=await api<any>('/transform/calculated-column/validate',{method:'POST',body:JSON.stringify({source,steps,name,expression})});setValidation(r)}catch(e:any){setValidation({valid:false,error:e.message})}finally{setBusy(false)}};
 const generate=async()=>{setBusy(true);try{const r=await api<any>('/transform/calculated-column/ai-generate',{method:'POST',body:JSON.stringify({source,steps,prompt})});setAiResult(r);setName(r.name);setExpression(r.expression);setValidation({valid:true,rows:r.preview,sql:r.compiledSql})}catch(e:any){setAiResult({error:e.message});setValidation(null)}finally{setBusy(false)}};
 const funcs=['IF','CASE WHEN','COALESCE','NULLIF','UPPER','LOWER','TRIM','CONCAT_WS','REPLACE','LENGTH','ROUND','ABS','YEAR','MONTH','QUARTER','WEEK','DAY','DATE_DIFF','DATE_TRUNC','LAST_DAY','CAST'];
 return <Modal title={mode==='edit'?`Edit Calculated Column — ${initialStep?.name||name}`:"Calculated Column — Row Logic + AI"} onClose={onClose} wide><div className="calculatedProLayout">
   <aside className="calcColumnBrowser"><div className="calcPaneTitle"><Columns3 size={15}/><b>Columns</b></div><div className="columnSearch"><Search size={14}/><input placeholder="Search columns" value={search} onChange={e=>setSearch(e.target.value)}/></div><p>Click a field to insert its exact row reference.</p><div className="calcColumnList">{filtered.map((c:string)=><button key={c} onClick={()=>insert(`[${c}]`)}><span>ƒx</span><b>{c}</b><small>[{c}]</small></button>)}</div></aside>
   <section className="calcFormulaPane"><label className="formField"><span>{mode==='edit'?'Calculated column name':'New column name'}</span><input value={name} onChange={e=>setName(e.target.value)}/></label>{mode==='edit'&&<div className="editingObjectBanner"><Pencil size={14}/><span>Editing existing ETL calculated column. Saving updates this Applied Step in place.</span></div>}<div className="calcEditorHead"><div><Braces size={15}/><b>Row expression</b></div><button onClick={validate} disabled={busy||!expression.trim()}><Check size={14}/>{busy?'Checking…':'Validate & Preview'}</button></div><textarea ref={editorRef} className="calcExpressionEditor" value={expression} onChange={e=>{setExpression(e.target.value);setValidation(null)}} spellCheck={false} placeholder={`Examples:\nIF([Status] = 'Done', 'Closed', 'Open')\n[Story Points] * [Days Open]\nCOALESCE([Days Open], 0)`}/><div className="calcFunctionChips">{funcs.map(f=><button key={f} onClick={()=>insert(f==='CASE WHEN'?`CASE WHEN  THEN  ELSE  END`:`${f}()`)}>{f}</button>)}</div><div className="calcHelp"><b>Row-level only:</b> arithmetic, IF/CASE, comparisons, text functions, null handling and date logic. The step runs during ETL and is materialized before Model.</div>{validation&&<div className={'calcValidation '+(validation.valid?'ok':'bad')}>{validation.valid?<><Check size={15}/><div><b>Expression is valid</b><span>Preview of the new column:</span>{validation.rows&&<MiniTable rows={validation.rows} limit={5}/>}</div></>:<><Info size={15}/><div><b>Validation failed</b><span>{validation.error}</span></div></>}</div>}</section>
   <aside className="calcAiPane"><div className="calcAiTitle"><Sparkles size={17}/><div><small>AI ROW LOGIC BUILDER</small><b>Describe the calculated column</b></div></div><div className="calcPromptWrap"><textarea ref={promptRef} value={prompt} onFocus={e=>{setPromptFocus(true);setPromptCursor(e.currentTarget.selectionStart)}} onBlur={()=>setTimeout(()=>setPromptFocus(false),140)} onSelect={e=>setPromptCursor((e.target as HTMLTextAreaElement).selectionStart)} onChange={e=>{setPrompt(e.target.value);setPromptCursor(e.target.selectionStart);setPromptFocus(true)}} placeholder="Examples: If Status is Done then Closed else Open; days between Created and Updated; replace null Days Open with 0..."/>{!!suggestions.length&&<div className="calcPromptSuggestions">{suggestions.map((c:string)=><button key={c} onMouseDown={e=>{e.preventDefault();insertPrompt(c)}}><b>{c}</b><small>Current ETL column</small></button>)}</div>}</div><button className="calcGenerateBtn" onClick={generate} disabled={busy||!prompt.trim()}><Sparkles size={15}/>{busy?'Generating…':'Generate Row Formula'}</button><div className="calcAiGrounding"><b>Grounded to current transformation</b><span>{availableCols.length} available columns</span></div>{aiResult&&!aiResult.error&&<div className="calcAiResult"><b>{aiResult.name}</b><p>{aiResult.explanation}</p><code>{aiResult.expression}</code>{aiResult.warning&&<span className="calcWarning">{aiResult.warning}</span>}</div>}{aiResult?.error&&<div className="calcValidation bad"><Info size={14}/><span>{aiResult.error}</span></div>}</aside>
 </div><div className="dialogActions calculatedActions"><button onClick={onClose}>Cancel</button><button onClick={validate} disabled={!expression.trim()}>Validate</button><button className="primary" disabled={!name.trim()||!expression.trim()||validation?.valid===false} onClick={()=>onApply({type:'calculated_column',label:`Calculated column ${name}`,name,expression,aiPrompt:prompt})}>{mode==='edit'?<><Save size={14}/>Save Changes</>:'Add Calculated Column'}</button></div></Modal>
}

function JoinDialog({source,steps,cols,meta,onClose,onApply}:any){const[other,setOther]=useState(meta.find((m:any)=>m.name!==source)?.name||'');const[rightCols,setRightCols]=useState<string[]>([]);const[keys,setKeys]=useState<any[]>([]);const[joinType,setJoinType]=useState('left');const[profile,setProfile]=useState<any>(null);const[dragLeft,setDragLeft]=useState('');useEffect(()=>{const m=meta.find((x:any)=>x.name===other);setRightCols((m?.columns||[]).map((x:any)=>x.name));setKeys([]);setProfile(null)},[other]);const drop=(right:string)=>{if(!dragLeft)return;setKeys(k=>[...k.filter(x=>x.leftField!==dragLeft),{leftField:dragLeft,rightField:right}]);setDragLeft('')};const preview=async()=>{if(!keys.length)return;const r=await api<any>('/transform/join-profile',{method:'POST',body:JSON.stringify({source,steps,otherTable:other,keys})});setProfile(r)};return <Modal title="Drag-and-Drop Join Designer" onClose={onClose} wide><div className="joinTop"><label>Join type<select value={joinType} onChange={e=>setJoinType(e.target.value)}>{['left','inner','right','full'].map(x=><option key={x}>{x}</option>)}</select></label><label>Right table<select value={other} onChange={e=>setOther(e.target.value)}>{meta.filter((x:any)=>x.name!==source).map((x:any)=><option key={x.name}>{x.name}</option>)}</select></label></div><p className="dialogHint">Drag a field from the left table and drop it on the matching field in the right table.</p><div className="joinDesigner"><div className="joinTable"><h4>{source}</h4>{cols.map((c:string)=><div draggable onDragStart={()=>setDragLeft(c)} className={'joinField '+(keys.some(k=>k.leftField===c)?'linked':'')} key={c}><GripVertical size={12}/>{c}</div>)}</div><div className="joinLines"><Link2 size={28}/>{keys.map((k:any,i:number)=><div key={i}>{k.leftField} = {k.rightField}<button onClick={()=>setKeys(x=>x.filter((_:any,j:number)=>j!==i))}>×</button></div>)}</div><div className="joinTable"><h4>{other}</h4>{rightCols.map(c=><div onDragOver={e=>e.preventDefault()} onDrop={()=>drop(c)} className={'joinField drop '+(keys.some(k=>k.rightField===c)?'linked':'')} key={c}>{c}</div>)}</div></div><button className="profileBtn" disabled={!keys.length} onClick={preview}>Preview Join Match</button>{profile&&<div className="joinProfile"><div><b>{profile.matchRate}%</b><span>Match rate</span></div><div><b>{profile.matchedLeftRows.toLocaleString()}</b><span>Matched left rows</span></div><div><b>{profile.unmatchedLeftRows.toLocaleString()}</b><span>Unmatched left</span></div><div><b>{profile.unmatchedRightRows.toLocaleString()}</b><span>Unmatched right</span></div></div>}<DialogActions onClose={onClose} disabled={!keys.length} onApply={()=>onApply({type:'join',label:`${joinType.toUpperCase()} JOIN ${other}`,otherTable:other,joinType,keys})}/></Modal>}
function AppendDialog({meta,source,queries,currentQueryId,onClose,onApply}:any){const[chosen,setChosen]=useState<string[]>([]);const queryOptions=(queries||[]).filter((x:any)=>x.id!==currentQueryId);const tableOptions=(meta||[]).filter((x:any)=>x.name!==source);const toggle=(id:string)=>setChosen(c=>c.includes(id)?c.filter(z=>z!==id):[...c,id]);const apply=()=>{const selectedQueries=queryOptions.filter((x:any)=>chosen.includes('query:'+x.id)).map((x:any)=>({id:x.id,name:x.name,source:x.source,steps:x.steps}));const tables=tableOptions.filter((x:any)=>chosen.includes('table:'+x.name)).map((x:any)=>x.name);const labels=[...selectedQueries.map((x:any)=>x.name),...tables];onApply({type:'append',label:`Append ${labels.join(', ')}`,tables,queryOutputs:selectedQueries})};return <Modal title="Append / Union Wizard" onClose={onClose} wide><p className="dialogHint">Append processed query outputs to preserve calculated, renamed, and converted columns. Physical source tables remain available when raw append is intended.</p>{queryOptions.length>0&&<><h4>Processed query outputs</h4><div className="checkList">{queryOptions.map((x:any)=><label key={x.id}><input type="checkbox" checked={chosen.includes('query:'+x.id)} onChange={()=>toggle('query:'+x.id)}/><span>{x.name}</span><small>Includes all applied steps</small></label>)}</div></>}<h4>Physical source tables</h4><div className="checkList">{tableOptions.map((x:any)=><label key={x.name}><input type="checkbox" checked={chosen.includes('table:'+x.name)} onChange={()=>toggle('table:'+x.name)}/><span>{x.name}</span><small>{x.columns?.length||0} raw columns</small></label>)}</div><DialogActions onClose={onClose} disabled={!chosen.length} onApply={apply}/></Modal>}
function GroupDialog({cols,onClose,onApply}:any){const[groups,setGroups]=useState<string[]>([]);const[aggs,setAggs]=useState<any[]>([{field:cols[0]||'',aggregation:'sum',alias:'Total'}]);const upd=(i:number,k:string,v:string)=>setAggs(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x));return <Modal title="Group By" onClose={onClose} wide><div className="groupBuilder"><div><h4>Group by fields</h4><div className="checkList compact">{cols.map((c:string)=><label key={c}><input type="checkbox" checked={groups.includes(c)} onChange={()=>setGroups(g=>g.includes(c)?g.filter(x=>x!==c):[...g,c])}/>{c}</label>)}</div></div><div><h4>Aggregations</h4>{aggs.map((a,i)=><div className="aggRow" key={i}><select value={a.field} onChange={e=>upd(i,'field',e.target.value)}>{cols.map((c:string)=><option key={c}>{c}</option>)}</select><select value={a.aggregation} onChange={e=>upd(i,'aggregation',e.target.value)}>{['sum','avg','min','max','count','distinctcount'].map(x=><option key={x}>{x}</option>)}</select><input value={a.alias} onChange={e=>upd(i,'alias',e.target.value)}/><button onClick={()=>setAggs(x=>x.filter((_,j)=>j!==i))}>×</button></div>)}<button className="addRule" onClick={()=>setAggs(x=>[...x,{field:cols[0]||'',aggregation:'sum',alias:'Total'}])}>+ Add aggregation</button></div></div><DialogActions onClose={onClose} disabled={!aggs.length} onApply={()=>onApply({type:'group_by',label:`Group by ${groups.join(', ')||'(all rows)'}`,groupFields:groups,aggregations:aggs})}/></Modal>}
function DialogActions({onClose,onApply,disabled=false}:any){return <div className="dialogActions"><button onClick={onClose}><XCircle size={15}/>Cancel</button><button className="primary" disabled={disabled} onClick={onApply}><Check size={15}/>Apply Step</button></div>}
