export type VisualType='kpi'|'card'|'multirowcard'|'bar'|'column'|'stackedbar'|'stackedcolumn'|'line'|'area'|'combo'|'pie'|'donut'|'treemap'|'funnel'|'waterfall'|'scatter'|'bubble'|'radar'|'heatmap'|'histogram'|'boxplot'|'gauge'|'progress'|'table'|'matrix'|'slicer'|'textbox'|'button';
export type VisualFilter={field:string,operator:string,value:any,rankingField?:string,condition?:'and'|'or',operator2?:string,value2?:any};
export type DisplayUnits='auto'|'none'|'thousand'|'million'|'billion'|'trillion';
export type NumberStyle='number'|'currency'|'percentage';
export type NegativeStyle='minus'|'parentheses';
export type NumberFormat={
  style?:NumberStyle; currency?:string; decimals?:number; displayUnits?:DisplayUnits;
  thousandsSeparator?:boolean; negativeStyle?:NegativeStyle; prefix?:string; suffix?:string;
  dateFormat?:'default'|'dd/MM/yyyy'|'MM/dd/yyyy'|'yyyy-MM-dd'|'dd MMM yyyy';
};
export type VisualFormat={
  accent:string; fontSize:number; showTitle:boolean; dataLabels:boolean; background?:string; fontFamily?:string;
  fieldFormats?:Record<string,NumberFormat>; titleFontSize?:number; titleColor?:string; labelFontSize?:number;
  labelColor?:string; labelPosition?:'top'|'inside'|'outside'; legendVisible?:boolean;
  legendPosition?:'top'|'bottom'|'left'|'right'; borderVisible?:boolean; borderColor?:string; borderWidth?:number;
  cornerRadius?:number; cornerRadii?:CornerRadii; cornerLinked?:boolean; shadow?:boolean; backgroundTransparency?:number; gridLines?:boolean; borderStyle?:'solid'|'dashed'|'dotted'; borderEdges?:BorderEdges;
  showDataPoints?:boolean; dataPointSize?:number; tooltipEnabled?:boolean; tooltipBackground?:string; tooltipColor?:string; indicatorEnabled?:boolean;
  favorableDirection?:'up'|'down'; positiveColor?:string; negativeColor?:string; neutralColor?:string;
  subtitle?:string; subtitleVisible?:boolean; subtitleColor?:string; subtitleFontSize?:number;
  titleFontWeight?:number; titleAlignment?:'left'|'center'|'right'; titleFontStyle?:'normal'|'italic'; titleUnderline?:boolean; titleWrap?:boolean;
  subtitleFontWeight?:number; subtitleAlignment?:'left'|'center'|'right'; subtitleFontStyle?:'normal'|'italic'; subtitleUnderline?:boolean; subtitleWrap?:boolean;
  axisFontSize?:number; axisColor?:string; axisTitleVisible?:boolean;
  xAxisTitle?:string; yAxisTitle?:string; gridLineColor?:string; gridLineStyle?:'solid'|'dashed'|'dotted'; zoomSlider?:boolean;
  legendColor?:string; legendFontSize?:number; visibleCategoryCount?:number;
  referenceLineEnabled?:boolean; referenceLineValue?:number; referenceLineLabel?:string; referenceLineColor?:string;
  visualHeader?:boolean; responsive?:boolean; altText?:string;
  markerShape?:'circle'|'rect'|'roundRect'|'triangle'|'diamond'; lineWidth?:number; smoothLines?:boolean;
  barRadius?:number; barWidth?:number; padding?:number; chartOpacity?:number;
  textFontWeight?:number; textItalic?:boolean; textUnderline?:boolean; textAlign?:'left'|'center'|'right'|'justify'; textVerticalAlign?:'top'|'middle'|'bottom'; textWrap?:boolean; textLineHeight?:number;
  cardsPerRow?:number; cardAutoFit?:boolean; cardMinWidth?:number; cardMinHeight?:number; cardGapX?:number; cardGapY?:number; cardPadding?:number;
  cardHorizontalAlign?:'left'|'center'|'right'; cardVerticalAlign?:'top'|'middle'|'bottom'; cardTitlePosition?:'top'|'bottom'; cardValuePosition?:'top'|'middle'|'bottom'; cardIconPosition?:'left'|'top'|'right'; cardIconSize?:number;
  axesVisible?:boolean; backgroundEnabled?:boolean; lockAspectRatio?:boolean; maintainLayerOrder?:boolean;
  paddingTop?:number; paddingRight?:number; paddingBottom?:number; paddingLeft?:number;
  shadowColor?:string; shadowOffset?:number; altTextEnabled?:boolean;
  headerFilterIcon?:boolean; headerFocusIcon?:boolean; headerMoreIcon?:boolean; headerDrillIcon?:boolean; headerPersonalizeIcon?:boolean; headerSpotlightIcon?:boolean;
  tooltipMode?:'default'|'reportPage'; pieRotation?:number; donutInnerRadius?:number;
  tableTextColor?:string; tableFontSize?:number; tableRowPadding?:number; tableAlternatingRows?:boolean; tableAlternateColor?:string; tableFontFamily?:string; tableTextAlign?:'left'|'center'|'right'; tableBackground?:string;
  tableHeaderVisible?:boolean; tableHeaderColor?:string; tableHeaderBackground?:string; tableHeaderFontSize?:number; tableGridVisible?:boolean; tableGridColor?:string; tableGridWidth?:number; tableHeaderFontFamily?:string; tableHeaderTextAlign?:'left'|'center'|'right'; tableHeaderWordWrap?:boolean; tableVerticalGridVisible?:boolean; tableAutoWidth?:boolean; tableColumnWidth?:number; tableTotalBackground?:string; tableTotalTextColor?:string; tableGrandTotal?:boolean; tableTotalLabel?:string;
  matrixSteppedLayout?:boolean; matrixExpandIcons?:boolean; matrixRowPadding?:number; matrixSubtotals?:boolean; matrixGrandTotal?:boolean;
  slicerSearch?:boolean; slicerSingleSelect?:boolean; slicerSelectAll?:boolean; slicerOrientation?:'vertical'|'horizontal';
  cardLayoutDirection?:'vertical'|'horizontal'; cardBackground?:string; cardBackgroundTransparency?:number; cardBorderVisible?:boolean; cardBorderColor?:string; cardBorderWidth?:number; cardCornerRadius?:number;
  categoryLabelVisible?:boolean; categoryLabelText?:string; categoryLabelColor?:string; categoryLabelFontSize?:number; categoryLabelFontWeight?:number; categoryLabelPosition?:'above'|'below';
  calloutVisible?:boolean; calloutFontWeight?:number; calloutWrap?:boolean;
  cardImageEnabled?:boolean; cardImageUrl?:string; cardImagePosition?:'left'|'right'|'above'|'below'|'background'; cardImageFit?:'contain'|'cover'|'fill'; cardImageSize?:number;
  referenceLabelsVisible?:boolean; referenceLabelText?:string; referenceLabelColor?:string; referenceLabelFontSize?:number; referenceLabelPosition?:'above'|'below';
  conditionalColorsEnabled?:boolean; conditionalPositiveColor?:string; conditionalNegativeColor?:string; conditionalZeroColor?:string;
  areaOpacity?:number; pieOuterRadius?:number; pieSliceGap?:number;
  treemapGap?:number; treemapBorderWidth?:number; treemapGroupLabels?:boolean;
  funnelGap?:number; funnelSort?:'descending'|'ascending'|'none';
  radarFillOpacity?:number; radarGridVisible?:boolean; radarLabelVisible?:boolean;
  heatmapMinColor?:string; heatmapMaxColor?:string; heatmapCellGap?:number;
  histogramBinCount?:number; boxShowOutliers?:boolean;
  bubbleMinSize?:number; bubbleMaxSize?:number;
  comboSecondaryColor?:string; comboSecondaryAxisVisible?:boolean;
  gaugeMin?:number; gaugeMax?:number; gaugeTrackColor?:string; gaugeThickness?:number; gaugeTargetVisible?:boolean;
  progressTrackColor?:string; progressThickness?:number; progressShowPercent?:boolean;
  buttonBackground?:string; buttonTextColor?:string; buttonFontSize?:number; buttonCornerRadius?:number; buttonBorderVisible?:boolean; buttonBorderColor?:string;
};
export type VisualBindings={axis?:string[],values?:string[],target?:string[],legend?:string[],tooltips?:string[],hierarchy?:{id:string,level:number}};
export type VisualSort={field:string,direction:'asc'|'desc'};
export type BorderEdges={top?:boolean,right?:boolean,bottom?:boolean,left?:boolean};
export type CornerRadii={topLeft?:number,topRight?:number,bottomRight?:number,bottomLeft?:number};
export type VisualAction={type?:'none'|'navigate'|'toggleVisual'|'showVisual'|'hideVisual'|'clearFilters',targetPageId?:string,targetVisualId?:string};
export type SlicerStyle='list'|'dropdown'|'verticalTiles'|'horizontalTiles';
export type RichTextRun={text:string,bold?:boolean,italic?:boolean,underline?:boolean,fontFamily?:string,fontSize?:number,color?:string,align?:'left'|'center'|'right'|'justify',list?:'bullet'|'number'};
export type Visual={id:string,type:VisualType,title:string,x:number,y:number,w:number,h:number,geometryVersion?:2,rotation?:number,zIndex?:number,visible?:boolean,locked?:boolean,bindings:VisualBindings,filters?:VisualFilter[],sort?:VisualSort[],format:VisualFormat,text?:string,richText?:string,richTextRuns?:RichTextRun[],buttonLabel?:string,action?:VisualAction,slicerStyle?:SlicerStyle,hidden?:boolean,tabOrder?:number,drillLevel?:number,drillFilters?:VisualFilter[]};
export type PageHeader={visible:boolean,title:string,subtitle:string,fontSize:number,subtitleFontSize?:number,titleColor:string,subtitleColor:string,alignment:'left'|'center'|'right',background:string,height?:number,paddingTop?:number,paddingBottom?:number,paddingLeft?:number,paddingRight?:number,borderRadius?:number,showGeneratedInfo?:boolean,generatedInfoBackground?:string};
export type PageSettings={background:string,wallpaper?:string,backgroundImage?:string,backgroundImageFit?:'cover'|'contain'|'stretch'|'center',backgroundImageOpacity?:number,themeId?:string,pageWidth?:number,pageHeight?:number,pageSizePreset?:'16:9'|'4:3'|'Letter'|'Tooltip'|'HD 16:9'|'Full HD 16:9'|'QHD 16:9'|'16:10'|'A4 Landscape'|'A4 Portrait'|'Custom',pageAlignment?:'center'|'left',pageVerticalAlignment?:'top'|'middle'|'bottom',showGrid?:boolean,snapToGrid?:boolean,allowOverlap?:boolean,layoutMode?:'guided'|'freeform',autoFitHeight?:boolean,footerGap?:number,navigationPosition?:'outside'|'sticky',navigationTopMargin?:number,navigationBottomMargin?:number,header:PageHeader,showNavigation:boolean};
export type Page={id:string,name:string,visuals:Visual[],filters?:VisualFilter[],settings?:PageSettings,drillThroughFields?:string[]};
export type AppPreferences={autosave?:boolean,rememberWorkspace?:boolean,defaultPageSize?:'HD 16:9'|'Full HD 16:9'|'A4 Landscape',snapToGrid?:boolean,defaultShowGrid?:boolean,defaultFont?:'Segoe UI'|'Arial'|'Inter',previewRows?:number,queryCache?:boolean,copilotEnabled?:boolean,copilotContext?:boolean};
export type Project={id:string,name:string,appTheme?:'vtab'|'black'|'white',appAccent?:string,uiDensity?:'compact'|'comfortable'|'spacious',appPreferences?:AppPreferences,projectFile?:{fileName?:string;location?:string;description?:string;createdAt?:string},model:any,transform:any,report:{id:string,name:string,activePageId:string,pages:Page[],filters?:VisualFilter[]},security:any};
